### ISSUE TITLE
convert a Navisworks file

### ISSUE THREAD

**Issue by spookyfox** [iTwin/itwinjs-core#1014]
Hi,

I have converted a *.nwd file and opened it with your amazing viewer, but the most of the properties are missing. Is there something I can do to get these data as well? Thanks a lot, Henrik
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Create-a-snapshot-iModel---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/tutorials/create-test-imodel-offline/

**Comment by jffmarker** [comment]
Most NWD data is converted as element MultiAspects due to the unstructured nature of NWD. Are you checking for aspects as well as the element class for data?

**Comment by spookyfox** [comment]
'Are you checking for aspects as well as the element class for data?' How to do this checking?

**Comment by jffmarker** [comment]
I got this recommended API from @khanaffan to get an element's aspects: https://www.itwinjs.org/reference/imodeljs-backend/imodels/imodeldb.elements/getaspects/

**Comment by calebmshafer** [comment]
Closing this issue due to the inactivity. @spookyfox if you're still seeing an issue please feel free to re-open.
