### ISSUE TITLE
Issue in generating tile files using a non root user in container

### ISSUE THREAD

**Issue by PKASHYAP-BEC** [iTwin/itwinjs-core#179]
we are hosting our backend services on a linux(debian) container with a non-root user, and while opening a snapshot iModel we are getting Zero KB Tile file and it prevents me to render by model on frontends.

Can anyone suggest anything to get this problem fixed?

**Comment by pmconne** [comment]
Short-term, can you open your iModel from a directory for which the user has write permissions?
Slightly longer-term, if we gave you the option to specify that the tiles should be cached in [IModelHostConfiguration.cacheDir](https://github.com/imodeljs/imodeljs/blob/0a6c7827a6bd92d07e09cb2528f14597d33f27a1/core/backend/src/IModelHost.ts#L113), would that suffice?

**Comment by PKASHYAP-BEC** [comment]
A longer-term option will be better, but I am still facing the problem user have write access to that directory and it is able to create zero kb files, but there is no content.

What I am thinking is native C++ module is executing in some other context and it is creating this issue.

**Comment by calebmshafer** [comment]
We have identified the issue in the c++ code that is creating the directory and not honoring the `cacheDir`. We're working on a fix and will include it in a 2.11.x patch release.  I'll update this item once it's released.

**Comment by pmconne** [comment]
@calebmshafer was this fix ever released?

**Comment by calebmshafer** [comment]
this has been validated and fixed in the iTwin.js 3.x generation. Please update to the latest 3.x to use it.
