### ISSUE TITLE
Linux Desktop Authentication Error

### ISSUE THREAD

**Issue by rickhewes** [iTwin/itwinjs-core#1841]
Hi,

Just trying out iModel.js and having problems on linux. I would expect the desktop-starter to work out of the box. It does on Windows but on Linux (Fedora 32) I have the following issue.

![Screenshot from 2020-07-20 09-29-20](https://user-images.githubusercontent.com/1804586/87916847-eb869a80-ca6b-11ea-8114-a096a2f91389.png)

Any help appreciated!

Cheers,

Rick.

**Comment by calebmshafer** [comment]
@rickhewes this issue has been addressed in iTwin.js 3.0 and desktop apps should now work on Linux. Any desktop app using our Electron auth client will lack support for caching a password forcing you to sign-in each time the app is started. However, support for caching on Linux is in progress [here](https://github.com/iTwin/auth-clients/pull/44).

If you'd like to try it out, please give the release candidate of 3.0, details [here](https://github.com/iTwin/itwinjs-core/discussions/294).

**Comment by aruniverse** [comment]
Closing as the issue has been initially addressed with the 3.0 release; and theres been no update from the user since.
