### ISSUE TITLE
Using backend to generate Change Summaries on iModels

### ISSUE THREAD

**Issue by bradjamesgrant** [iTwin/itwinjs-core#2146]
Hi team,

I'm currently trying to collect changeset data through ECSQL commands. To do this I need to [generate change summaries](https://www.itwinjs.org/learning/changesummaries/) which requires some backend functions to be called. What is the minimum requirement or code needed to open an iModel to then attach these change cache files and change summaries? I've used some of [this](https://github.com/imodeljs/agent-starter) code and tried to run the functions there, though program doesn't seem to respond in any way, and therefore unable to tell if it was successful

**Comment by aruniverse** [comment]
Closing this issue due to lack of response; @bradjamesgrant we can reopen this later if you respond back with more details as previously requested
