### ISSUE TITLE
Branching and merging

### ISSUE THREAD

**Issue by rssahai** [iTwin/itwinjs-core#2349]
The concepts of branching and merging are absent from this glossary. Is their implementation for iModels hard or impossible?
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Glossary-of-terms-in-iTwin.js---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/glossary/

**Comment by rssahai** [comment]
Use case for branching and merging is a design-build-operate-maintain (DBOM) project that begins with existing survey and as-builts. The environmental permit package branches off during planning while concept design moves forward with new topographic surveys and plans toward a 30% review. When the environmental permit package reaches its first review milestone, the environmental branch updates its existing and as-built plans with the concept design's 30% review package and moves along its branch. The branch-synch-merge cycle, if and when implemented for iModels, can simplify work on projects where environmental permit and concept design efforts need to move in parallel with related but different data sets.

**Comment by rssahai** [comment]
Looks  like the Engineering Component Modeling initiative of the year 2000 (MicroStation/J, JMDL, ProjectBank) has finally found a commercially viable outlet in iTwin/iModel after 20-years!

**Comment by MichaelBelousov** [comment]
closing as this is implemented. It is documented here: https://www.itwinjs.org/learning/transformer/branching-imodels/
