### ISSUE TITLE
iTwins Viewer Side Panel Grab Handle

### ISSUE THREAD

**Issue by sweetld** [iTwin/itwinjs-core#2491]
I have noticed that when you have panels docked on the right hand side of the viewer, you can see a three dot "grab handle" which helps to show the user that they can drag this across to split the viewer and display the panels docked on the right hand side again.

This is useful, and works - however several of our users are complaining that it's difficult and confusing to use...

I believe that they are uncomfortable with the way this grab handle acts in a slightly "sticky" way, in that you have to drag it across to the left beyond a certain point for it to stay open when you let go of the handle, and once you have the right hand panels showing, you have to drag the handle to the right beyond a certain point for it to actually close again.

Personally, it seems to me as though this is useful, as it prevents the side panel being opened to such a narrow width for it to be useless, however I can understand my user's feedback that they find this difficult and annoying.

To that end, I simply wanted to know whether there was any way to turn off this feature / functionality, and make it work like a normal side panel that the user can make as narrow as they want without interference??

Any pointers, suggestions gratefully received!

**Comment by sweetld** [comment]
Hi, thanks, yes this is what I was referring to. Apologies if this was not clear.

**Comment by sweetld** [comment]
I don't want to turn off the "handle", as obviously the user would then not know that there was a side panel to view...

But rather as above, be able to set the minimum width in px for the side panels. That way we would be able to set it to 0px to effectively prevent the "sticky" behavior, so you don't have to drag the handle larger than 100px to make it open.

**Comment by FlyersPh9** [comment]
Oh my mistake, I didn't even notice this wasn't the iTwinUI repo I'm commenting in. 😅 My mistake, ignore what I said.

**Comment by raplemie** [comment]
@sweetld Since this issue was created, it is now possible to control the minimum width of a panel (which will still trigger this auto-close behavior, but you can put it to 0 if needed)

If your application uses the `StandardFrontstageProvider` to create your frontstage, you can provide the constructor with this configuration (along the required elements):
```ts
const frontstageProvider = new StandardFrontstageProvider({rightPanelProps: { minSize: 1 } });
```

**Comment by NancyMcCallB** [comment]
@sweetld, The grab handles on the side panels have undergone a redesign. Please reevaluate them with the 3.5 release.

Thanks!
Nancy McCall
