### ISSUE TITLE
Repository Move Announcement

### ISSUE THREAD

**Issue by skirby1996** [iTwin/itwinjs-core#2529]
# iModel.js Repo Transfer Announcement

On the 27th of October, the imodeljs repo will be transferred to the [iTwin Platform](https://github.com/iTwin) organization on Github and renamed to 'itwinjs-core'.

All branches, pull requests, issues, and discussions will be transferred along with the repository, and all links to the old repository will redirect to the new repository which will be found at <https://github.com/iTwin/itwinjs-core>.

Between 11:00 AM EST to 1:00 PM EST, there will be a period where no pull requests will be able to be completed while we update our CI/CD builds to use the new repository location.

Once the move is complete, while not required, we recommend that you update the git origin in your local copy of the repo to the new repository location using:

`git remote set-url origin https://github.com/iTwin/itwinjs-core.git`

## Repo Transfer Checklist

- [x] Make announcement
- [x] Update links to old name and location within the repo
- [x] Update build pipelines
  - [x] Internal CI build
  - [x] Public CI build
  - [x] Docs build
  - [x] Integration tests build
  - [x] Regression tests build
  - [x] Version bump build

**Comment by calebmshafer** [comment]
Closing this issue as it has been several days since the move. The thread will be left open for people to report any lingering problems going forward.
