### ISSUE TITLE
After using imodel-transformer to process model, the model texture was lost.

### ISSUE THREAD

**Issue by tony-tang** [iTwin/itwinjs-core#2944]
When I used imodel-transformer to process model, I found the texture was lost. Please try the attachment bim file.
[texture_test2.zip](https://github.com/iTwin/itwinjs-core/files/7741972/texture_test2.zip)

Thanks.

**Comment by MichaelBelousov** [comment]
Hi Tony, I'm going to start looking into this soon.

**Comment by MichaelBelousov** [comment]
@tony-tang what version of the transformer package were you using?

**Comment by aruniverse** [comment]
Closing this issue due to lack of response; @tony-tang we can reopen this later if you respond
