### ISSUE TITLE
Loading Orbit PointCloud with projection KrovakEN causes crash

### ISSUE THREAD

**Issue by alarkbentley** [iTwin/itwinjs-core#3027]
Projection name "KrovakEN" is not handled.
https://github.com/iTwin/itwinjs-core/blob/b1e6c76ad3fff65a354a758680d0b2d12a2ec194/core/orbitgt/src/spatial/ecrs/WellKnownText.ts#L279

It is however handled here:
https://github.com/iTwin/itwinjs-core/blob/b1e6c76ad3fff65a354a758680d0b2d12a2ec194/core/orbitgt/src/spatial/ecrs/WellKnownText.ts#L336

but gives nullpointer because parameterList is always empty.

Example projection:
https://epsg.io/8353

WKT:
`PROJCS[
	"S-JTSK [JTSK03] / Krovak East North",
	GEOGCS[
		"S-JTSK [JTSK03]",
		DATUM["System of the Unified Trigonometrical Cadastral Network [JTSK03]",
			SPHEROID["Bessel 1841",6377397.155,299.1528128,AUTHORITY["EPSG","7004"]],
			AUTHORITY["EPSG","1201"]
		],
		PRIMEM["Greenwich",0.0,AUTHORITY["EPSG","8901"]],
		UNIT["Degree",0.017453292519943278,AUTHORITY["EPSG","9102"]],
		AUTHORITY["EPSG","8351"]
	],
	PROJECTION["KrovakEN"],
	PARAMETER["latitude_of_center",49.5],
	PARAMETER["longitude_of_center",24.833333333333332],
	PARAMETER["azimuth",30.288139752777788],
	PARAMETER["pseudo_standard_parallel_1",78.5],
	PARAMETER["scale_factor",0.9999],
	PARAMETER["false_easting",0.0],
	PARAMETER["false_northing",0.0],
	UNIT["Metre",1.0,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","8353"]
]`

**Comment by stuartpb** [comment]
@alarkbentley It looks like changing line 279 to `if (Strings.equalsIgnoreCase(projectionName, "Krovak") || Strings.equalsIgnoreCase(projectionName, "KrovakEN")) {` would fix this; are you able to test if that's the case?

**Comment by alarkbentley** [comment]
I confirmed that this fix works.
