### ISSUE TITLE
Feature overrides on imodel load not applied

### ISSUE THREAD

**Issue by deanmarcussen** [iTwin/itwinjs-core#3265]
**Describe the bug**

We are trying to apply `FeatureOverrides` via the `EmphasizeElements` api when the iModel is loaded.

However the overrides aren't applied.

If I delay the call to the `EmphasizeElements` api by approx 2 seconds, after model load they are correctly set.

I can see the call to `addFeatureOverrides` being made early in the sequence, but calling it later doesn't redraw.
We set them overrides in a sequence, so many calls with different elements are made to
`this._emphasizedElements.overrideElements(elData.elements, vp, elData.color, FeatureOverrideType.ColorAndAlpha, false);`
but I can see only one call to `addFeatureOverrides` is actually made, and subsequent overrides are not being applied.

I suspect I need some way to invalidate the view, or delay the calls, but haven't found the approriate api.

This appeared for us after moving to v3, but I cannot be certain it wasn't occuring on the previous version.

**To Reproduce**

When iModel is initially loaded, i.e. `viewport.areAllTileTreesLoaded` returns `true`
call `this._emphasizedElements.overrideElements(elData.elements, vp, elData.color, FeatureOverrideType.ColorAndAlpha, false);`

**Expected behavior**
overrides are applied.

**Desktop (please complete the applicable information):**

- iTwin.js Version 3

**Comment by pmconne** [comment]
Please show your code and specify what app template you used.
@kckst8 @aruniverse  wasn't there an issue with one of the react app templates recreating the viewport after initial load?

**Comment by kckst8** [comment]
@deanmarcussen can you try upgrading @itwin/web-viewer-react to the latest version (2.0.7)? There were some fixes related to viewport rendering that may help here.

**Comment by deanmarcussen** [comment]
Looks like a package update resolved the issue thanks all.
