### ISSUE TITLE
Setting the background base map to a any color gives a white background

### ISSUE THREAD

**Issue by mdastous-bentley** [iTwin/itwinjs-core#3292]
**Describe the bug**
Using maplayers widget, switching from Bing maps to any solid color, gives a white background.

**To Reproduce**

1. Open ui-test-app with any imodel/bim.
2. Open map-layers widget (might me collapsed on the right side)
3. In the 'base' combo box, pick 'Solid Fill Color':

**Expected behavior**
Background color of the map should match the one shown by the color picker.

**Screenshots**
![image](https://user-images.githubusercontent.com/8309609/156454189-6e2d17f2-5033-4c32-be12-5236c4484a7b.png)

**Desktop (please complete the applicable information):**

chrome
- iTwin.js Version master (3/2/2022)

**Comment by pmconne** [comment]
Easier repro steps:
1. Open any geolocated iModel in display-test-app.
2. Ensure the background map is enabled.
3. Key in `fdt set map base color 255 0 0`

Expect: the background should be red.
Observe: the view's own background color displays instead (not necessarily white).

**Comment by pmconne** [comment]
This regression was introduced by @RBBentley's #2881 for model map layers.
I'll try to figure out what changed, and make sure we have tests to cover this.
