### ISSUE TITLE
Add SweepToSolid to the PolyfaceBuilder

### ISSUE THREAD

**Issue by FelixGirard** [iTwin/itwinjs-core#3455]
**Is your feature request related to a problem? Please describe.**
I have to show the extrusion from a mesh surface. 

**Describe the solution you'd like**
I would like a function `solidSweep(mesh, vector3d, wantside?)` to be added to the [PolyfaceBuilder](https://www.itwinjs.org/learning/geometry/polyfacebuilder/).
That function could take a polyface or a mesh and have an option to specify if we want the sides.
This function existed in the c++ codebase and could be ported.

**Describe alternatives you've considered**
Right now I draw the mesh, draw the mesh in the extruded direction using transform.
Then, I calculate the edges and perform a linearSweep to create the side.

**Comment by dassaf4** [comment]
Great suggestion! The native method is PolyfaceHeader::SweepToSolid(). I'll work on porting this to PolyfaceBuilder.

**Comment by FelixGirard** [comment]
Thank you again for working on this. @dassaf4 
Just wanted to know, do you have an ETA on this?

**Comment by dassaf4** [comment]
Looking like a couple more days.
