### ISSUE TITLE
Presentation getElementProperties return null when use pkg to exe

### ISSUE THREAD

**Issue by chaoslife** [iTwin/itwinjs-core#3464]
I use Presentation.getManager().getElementProperties to get element properties, it's ok at js,
but when I use pkg to exe, it return undefined, where did i go wrong?
(pkg -t win-x64 package.json)

others api seems well at exe file, only this api  return undefined.

and I changed it to Presentation.getManager().getContent by this: https://gist.github.com/grigasp/32131ec63c5132e7599c387e9a835330#file-main-ts-L127-L135

there are some properties and not return undefind. 
but I find another issue, it lost some properties when run after pkg exe file.

a certain element's detail info in js:  
{
  pc_bis_Element_Model: 'house',
  pc_bis_Element_CodeValue: undefined,
  pc_bis_Element_UserLabel: 'Geometry',
  pc_bis_GeometricElement3d_Category: 'NewWall',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_Width: '0.370m',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_Length: '1.686m',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_Height: '1.686m',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_RotationX: '0.000°',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_RotationY: '0.000°',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_RotationZ: '0.000°',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_Volume: '0.125 Cu.m',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_SurfaceArea: '2.070 Sq.m',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_Capped: 'Yes',
 rc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_bis_Model_bis_InformationContentElement_ncc_bis_RepositoryLink: [ { displayValues: [Object] } ],
  rc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_ncc_bis_ExternalSourceAspect: [ { displayValues: [Object] } ]
}

but when log at exe, it lost last 2 properties, and pc_bis_Element_Model, pc_bis_GeometricElement3d_Category values become to @RulesEngine:LABEL_General_NotSpecified@:
{
  pc_bis_Element_Model: '@RulesEngine:LABEL_General_NotSpecified@',
  pc_bis_Element_CodeValue: undefined,
  pc_bis_Element_UserLabel: 'Geometry',
  pc_bis_GeometricElement3d_Category: '@RulesEngine:LABEL_General_NotSpecified@',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_Width: '0.370m',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_Length: '1.686m',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_Height: '1.686m',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_RotationX: '0.000°',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_RotationY: '0.000°',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_RotationZ: '0.000°',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_Volume: '0.125 Cu.m',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_SurfaceArea: '2.070 Sq.m',
  pc_SolidGeometricalPropertiesSchema_SolidGeometricalPropertiesClass_BoxSolidElement_Capped: 'Yes'
}

is there some way to solve this problem?
very thx

**Comment by grigasp** [comment]
Hi. Most likely this happens because of missing presentation backend assets. Have a look at [`PresentationManagerProps.presentationAssetsRoot` docs](https://github.com/iTwin/itwinjs-core/blob/aac95427eefb766888b5911679cabbb3ab0dfe30/presentation/backend/src/presentation-backend/PresentationManager.ts#L166-L200) for information about where we look by default and how to specify custom paths, if necessary.

**Comment by chaoslife** [comment]
> Hi. Most likely this happens because of missing presentation backend assets. Have a look at [`PresentationManagerProps.presentationAssetsRoot` docs](https://github.com/iTwin/itwinjs-core/blob/aac95427eefb766888b5911679cabbb3ab0dfe30/presentation/backend/src/presentation-backend/PresentationManager.ts#L166-L200) for information about where we look by default and how to specify custom paths, if necessary.

Okey, is this fix ths getElementProperties  or detail info lost by getContent ?

it that means I will put presentation-backend and presentation-common folders copy to ./assets/ after ncc execution ?

**Comment by grigasp** [comment]
> > Hi. Most likely this happens because of missing presentation backend assets. Have a look at [`PresentationManagerProps.presentationAssetsRoot` docs](https://github.com/iTwin/itwinjs-core/blob/aac95427eefb766888b5911679cabbb3ab0dfe30/presentation/backend/src/presentation-backend/PresentationManager.ts#L166-L200) for information about where we look by default and how to specify custom paths, if necessary.
> 
> Okey, is this fix ths getElementProperties or detail info lost by getContent ?
> 
> it that means I will put presentation-backend and presentation-common folders copy to ./assets/ after ncc execution ?

Sorry, I don't understand what you're asking.

The assets should be at the right place at the time you're calling `Presentation.initialize`.

**Comment by chaoslife** [comment]
Sorry ,my english is not well, I attach some screenshot to descript it:
![image](https://user-images.githubusercontent.com/2386021/161704066-a8c6da83-b31e-4465-a596-90986c73db71.png)
This is js file I exported by NCC. and I put the presentations to here:
![image](https://user-images.githubusercontent.com/2386021/161704210-1b7e64e6-462f-4ef5-8915-51a8b3754e98.png)

Is this place right ? then I will use PKG index.js to exe

**Comment by grigasp** [comment]
As described [here](https://github.com/iTwin/itwinjs-core/blob/2f8ae50239f8b3a00528d4bec1212b266b005b69/presentation/backend/src/presentation-backend/PresentationManager.ts#L187-L191), when `presentation-backend` and `presentation-common` source is packed into a single `js` file, by default we expect to find the assets next to the `js` file at `./assets/**/*`. What I see in your screenshots doesn't match that requirement. To match the default paths requirement, the directory structure should be like this:

- index.js
- assets
  - locales (from [presentation-common assets](https://github.com/iTwin/itwinjs-core/tree/master/presentation/common/assets))
  - primary-presentation-rules (from [presentation-backend assets](https://github.com/iTwin/itwinjs-core/tree/master/presentation/backend/assets))
  - supplemental-presentation-rules (from [presentation-backend assets](https://github.com/iTwin/itwinjs-core/tree/master/presentation/backend/assets))

**Comment by chaoslife** [comment]
Thank you very much for the reply, now it can be solved that the single js file packaged by NCC can be executed correctly!

At present, after using PKG to package it as an EXE file, after placing the Assets folder in this EXE file, the output result is still incorrect. I will check the reason again.

**Comment by grigasp** [comment]
> At present, after using PKG to package it as an EXE file, after placing the Assets folder in this EXE file, the output result is still incorrect. I will check the reason again.

It looks like pkg requires special configuration to include assets into the package: https://www.npmjs.com/package/pkg#user-content-config.
