### ISSUE TITLE
Javascript heap out of memory error from @bentley/react-scripts

### ISSUE THREAD

**Issue by kckst8** [iTwin/itwinjs-core#3468]
**Describe the bug**
When starting a web application in dev mode using @bentley/react-scripts (i.e. the iTwin Viewer starter template)

**To Reproduce**

1. From an application that was created from the iTwin Viewer starter template, run "npm start"

**Expected behavior**
Code compiles and the application is served on localhost:3000

**Actual behavior**
OOM error:

**Screenshots**
<img width="924" alt="image" src="https://user-images.githubusercontent.com/6283674/161775834-1f8e1c44-b37a-4333-9a63-27e0c6b269d3.png">

**Desktop (please complete the applicable information):**

- OS: MacOS
- iTwin.js Version: 3.1.0

**Additional context**
The issue does not appear to be present in 3.0.x

**Workaround**
Adding the following environment variables helps to bypass the issue (i.e. in your .env file):

USE_FAST_SASS=true
TRANSPILE_DEPS=false
DISABLE_TERSER=true

However, this seems to be working around a larger problem

**Comment by aruniverse** [comment]
Fixed & published in 3.1.2
