### ISSUE TITLE
Is these already deprecated?

### ISSUE THREAD

**Issue by Snailya** [iTwin/itwinjs-core#3521]
In iModelConsole, SELECT ECClassId FROM bis.Element will output ECClassName automaticly.
So are these deprecated?

* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: ECSQL-Built-In-functions---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/ecsqltutorial/builtinfunctions/

**Comment by pmconne** [comment]
I think displaying class name instead of class Id is something iModelConsole does for your convenience, but someone like @khanaffan would know for certain.

**Comment by ColinKerr** [comment]
iModel Console does convert the ECClassId to the class name for you.  if you want to see the ECClassId rename the selected property:
`SELECT ECClassId as the_class_id FROM bis.Element`

**Comment by aruniverse** [comment]
@Snailya any update? We will close this issue to due to inactivity if there's no response in a week. We can always reopen afterwards.
