### ISSUE TITLE
rush cover error

### ISSUE THREAD

**Issue by bear1004** [iTwin/itwinjs-core#3551]
ITwin was built via "rush rebuild" command.
I ran the "rush cover" command to run the test, but an error occurred.
please can you help?

I tried in two environments.
In both environments, the build was successful, but the "rush cover" command gave an error.

Environment
OS : windows10
npm : 8.6
node : 14.17.1(LTS)

![windows](https://user-images.githubusercontent.com/62101255/165224424-18c27433-5e70-46cc-9870-6470d3c46c43.PNG)

Environment
OS : VMWare - Ubuntu20.04.3
npm : 8.5
node : 16.14.2(LTS)

![vm](https://user-images.githubusercontent.com/62101255/165224811-112f07d2-2d4e-443f-b0b5-556046974de3.PNG)

**Comment by pmconne** [comment]
Make sure you are using latest version of iTwin.js please, or specify which version you're using.
The first error is about two processes trying to interact with the same file simultaneously. I believe it is fixed in 3.2.0.
The second is somebody wrote a test that makes bad assumptions about the date-time formatting settings of the OS. Ignore it. @NancyMcCallB @bsteinbk has this been fixed?

**Comment by NancyMcCallB** [comment]
@pmconne I confess I did not know this was failing. We'll get a fix in ASAP. Thanks!

**Comment by bear1004** [comment]
It was almost a month ago that I tried this.  I haven't tried to update the version since the error occurred. 

Is version 3.2.0 currently in "https://github.com/iTwin/itwinjs-core"? Then I'll try the latest version again. 

Thank you. 👍

**Comment by calebmshafer** [comment]
@bear1004 yes, this repository has it's `master` branch currently working on the 3.3 release but if you'd like to test out from a 3.2.0 set of the source you can check out to the git tag, `git checkout tags/release/3.2.0`.

**Comment by bear1004** [comment]
@calebmshafer hi

thanks for letting me know.
I am a graduate student at Gyeongsang National University.

I'm currently doing performance analysis on a digital twin.

While researching currently publicly available and commercially available digital twins, I came across a platform called itwin.

I want to measure Twin's data transfer rate.

So I ran the ITwin tutorial but got an error.
"https://www.itwinjs.org/learning/tutorials/develop-web-viewer/"

I created the application and IModel in the order they appear in the documentation. After that the ".env" file was modified.

After running the "npm start" command, I accessed http://localhost:3000/. However, I got the error "User is not authenticated. Please provide valid authentication credentials".

please can you help me?

**Comment by aruniverse** [comment]
@bear1004 , please take a look at this reply to the same issue. If auth issues persist, please reply on that thread or open a GitHub Discussion.

As this original issue was about `rush cover` and that doesn't seem to be an issue anymore (I hope) i'm going to close this, but if the issue persists we can reopen it.
