### ISSUE TITLE
The user is unauthorized. Please provide valid authentication credentials.

### ISSUE THREAD

**Issue by umerfaruque** [iTwin/itwinjs-core#3567]
Hi I follow the above steps but I am getting error "Error opening the iModel connection: Unauthorized: The user is unauthorized. Please provide valid authentication credentials."  Please guide me how can I Fix it
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Developing-a-Web-Viewer---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/tutorials/develop-web-viewer/

**Comment by calebmshafer** [comment]
@umerfaruque can you please provide the version of iTwin.js and the iTwin Viewer you're using? In addition, could you please provide the x-correlation-id, from the network tab in dev tools, for the failed request?

**Comment by pauljneville** [comment]
I am also getting this error.
I don't know how to find the version of iTwin.js or how to find the version of iTwin Viewer that I am using.
The x-correlation-id, from the network tab in dev tools, for the failed request is 36e43c83-a968-47d3-957c-d4a23c2dc4ea

**Comment by aruniverse** [comment]
@umerfaruque @pauljneville any update? Will close this issue to due to inactivity if there's no response in a week. We can always reopen afterwards.

**Comment by tim-basic** [comment]
Hi there, 
I'm also getting this error - I've triple-checked that the config matches the dev portal client id. 

In the lockfile-
  "@itwin/core-bentley": "^3.5.5",
   "@itwin/web-viewer-react": "^3.1.2",

Please advise

**Comment by tim-basic** [comment]
Hmm, I cleared the local storage, session storage and cookies and now all is working as expected...

**Comment by XinJack** [comment]
I run into the same issue and I have tried clearing the local storage, session storage and cookies, it still complains about authorization credentials.

version infomation:
"@itwin/core-bentley": "^3.6.2",
"@itwin/web-viewer-react": "^3.1.2",

x-correlation-ids for failed requests:
c9d94aa1-6dc7-405b-89de-452fa50d30f0
283ef032-5402-4f56-b181-2c22bfe9adb1

Also I think this may be a general problem, and maybe a solution for this issue can be provided with the Tutorials
