### ISSUE TITLE
New beta connector-framework package has been published!

### ISSUE THREAD

**Issue by jchick-bentley** [iTwin/itwinjs-core#3677]
The connector-framework package provides interfaces, utilities, and a scaffold for writing iTwin Connectors in TypeScript.  To learn more about iTwin Connectors, please visit:

[Write A Connector - iTwin.js (itwinjs.org)](https://www.itwinjs.org/learning/writeaconnector/#what-is-a-connector)

The connector-framework package supersedes what was previously delivered in the @bentley/imodel-bridge package and works with the iTwin.js API version 3.x.

The beta package is available at:
https://www.npmjs.com/package/@itwin/connector-framework

All current connector developers are encouraged port their existing connectors which were developed against the older iTwin.js API version 2.x (i.e. using IModelBridge) and test this new connector-framework package.

Please share any issues, comments or questions at:

https://github.com/iTwin/connector-framework/issues

**Comment by jchick-bentley** [comment]
> The connector-framework package provides interfaces, utilities, and a scaffold for writing iTwin Connectors in TypeScript. To learn more about iTwin Connectors, please visit:
> 
> [Write A Connector - iTwin.js (itwinjs.org)](https://www.itwinjs.org/learning/writeaconnector/#what-is-a-connector)
> 
> The connector-framework package supersedes what was previously delivered in the @bentley/imodel-bridge package and works with the iTwin.js API version 3.x.
> 
> The beta package is available at: https://www.npmjs.com/package/@itwin/connector-framework
> 
> All current connector developers are encouraged port their existing connectors which were developed against the older iTwin.js API version 2.x (i.e. using IModelBridge) and test this new connector-framework package.
> 
> Please share any issues, comments or questions at:
> 
> https://github.com/iTwin/connector-framework/issues

FYI @PeterJBassett

**Comment by aruniverse** [comment]
Closing this issue, or rather announcement since its been a few months now.
