### ISSUE TITLE
Asserts thrown for pickable polyface decorations

### ISSUE THREAD

**Issue by ImVeryLost** [iTwin/itwinjs-core#3682]
**Describe the bug**
In the latest versions of iTwin.js, asserts are being thrown for pickable polyface decorations, specifically when zooming far enough that they become "invisible". Issue is present only for pickable decorations. 
Managed to reproduce the issue with one of the iTwin.js test apps, with a pretty minimal setup, but it is present elsewhere as well.

**To Reproduce**
1. Go to "presentation-test-app" in itwinjs-core test apps.
2. Add the following decorator that reproduces the issue, add it to the app via IModelApp.viewManager.addDecorator:
```
const decorator = new TestDecorator();
IModelApp.viewManager.addDecorator(decorator);
```
4. After starting the app and load a iModel, so a viewport is visible. There will be a small white "dot" at the center of the viewport.
5. Zoom out. As soon as the decoration becomes small enough, the whole app freezes due to a thrown assertion:
![image](https://user-images.githubusercontent.com/61872067/170224091-b60afe71-1aa5-4c8f-8e17-b17741372681.png)

**Decorator code**
```

import { Id64String } from "@itwin/core-bentley";
import { ColorDef, GeometryStreamProps } from "@itwin/core-common";
import {
  DecorateContext, Decorator, GraphicBranch,
  GraphicType, HitDetail
} from "@itwin/core-frontend";
import { IModelJson, IndexedPolyface, Point3d, PolyfaceBuilder, Sphere, Transform } from "@itwin/core-geometry";

export class TestDecorator implements Decorator {
  private _elementId = "0x20000000074"; //Dummy id

  public decorate(context: DecorateContext): void {
    const branch = new GraphicBranch(true); // If i dont use a branch, issue is still present.

    let builder = context.createGraphic({
      type: GraphicType.WorldDecoration,
      pickable: {
        id: this._elementId, // If its not a pickable decoration, everything is fine.
      },
    });

    builder.setSymbology(ColorDef.white, ColorDef.white, 1);
    builder.addPolyface(this.getGraphics(), false); // If decoration is a PointString or similar, everything is fine.
    branch.add(builder.finish());
    const graphic = context.createBranch(branch, Transform.identity);
    context.addDecoration(GraphicType.WorldDecoration, graphic);
  }

  /** Creates very simple polyface. */
  private getGraphics(): IndexedPolyface {
    const polyfaceBuilder = PolyfaceBuilder.create();
    // Issue is present no matter the radius, but its easier to notice with small items.
    const sphere = Sphere.createCenterRadius(Point3d.create(0, 0, 0), 0.02);
    polyfaceBuilder.addSphere(sphere);
    return polyfaceBuilder.claimPolyface();
  }

  public getDecorationGeometry(): GeometryStreamProps | undefined {
    const geometryJson = IModelJson.Writer.toIModelJson(this.getGraphics());
    return [geometryJson];
  }

  public testDecorationHit(id: Id64String): boolean {
    return id === this._elementId;
  }

  public overrideElementHit(hit: HitDetail): boolean {
    return hit.sourceId === this._elementId;
  }
}

```

**Expected behavior**
Asserts should not be thrown, or should describe the cause of the issue explicitly.

**Desktop (please complete the applicable information):**

- OS: [Windows]
- Browser [Chrome]
- Version [101.0.4951.67]
- iTwin.js Version [3.2.0]

**Additional context**
Since its an assert that's being thrown, rather than a exception, it is implied that something is going wrong on my side of the code. If so, i would appreciate any pointers.
Note that the issue was not present with iTwin.js 3.2.0-dev.62 and previous versions. I realize that dev versions are not stable at all, but it might help narrow down the cause.

Also, is there a way to temporarily disable asserts in dev environment? After they are thrown, the whole app freezes without any way to dismiss it and continue...

**Comment by pmconne** [comment]
Thanks for the detailed issue. This would have been introduced by #3598. We'll fix it.

**Comment by ImVeryLost** [comment]
Verified that it works with 3.3.0-dev.13, thank you for resolving this so quickly!
