### ISSUE TITLE
Implement maxBlendableType on WebGL capabilities

### ISSUE THREAD

**Issue by markschlosseratbentley** [iTwin/itwinjs-core#3708]
This PR works around an issue with Safari 14 caused by blending full 32-bit float textures without the presence of EXT_float_blend: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodeljs/pullrequest/115930

We actually want to work around this in a way where we can still utilize full-float rendering when we are not going to be blending.  The goal of this backlog item is to implement and properly utilize a maxBlendableType value on the WebGL capabilities.

We will probably rename maxRenderType to maxRenderableType, and introduce a new maxBlendableType.  maxBlendableType depends on EXT_float_blend.

When rendering translucency, we would consult maxBlendableType to decide whether to render to full 32-bit floats or not.

Shadows likely can consult maxRenderableType - investigate this.

**Comment by markschlosseratbentley** [comment]
Planning to leave this as-is since only Safari iOS lacks the extension it seems -- @eringram plans to fill some gaps in the tests for this situation.

**Comment by eringram** [comment]
^Data from [here](https://caniuse.com/mdn-api_ext_float_blend). Full float rendering is already [disabled in Safari iOS](https://github.com/iTwin/itwinjs-core/blob/93a9169fd58b08ec4496fa008f0b5979a66988a7/core/webgl-compatibility/src/Capabilities.ts#L313-L315), so this would only matter in the future anyway when it becomes enabled.
