### ISSUE TITLE
Support vertical (Z) scaling for reality data

### ISSUE THREAD

**Issue by markschlosseratbentley** [iTwin/itwinjs-core#3709]
It would be great if we could scale reality data in the Z dimension through some API.

For terrain and globe: this would scale the terrain and/or globe based on the imodel axis; would not stretch properly when leaving the area of the imodel and going elsewhere on the globe.  Is this desirable?

**Comment by AlainRobertAtBentley** [comment]
Elevation exaggeration is a feature that can be useful, but applying this Z-exaggeration to specific model elements would be complicated and not necessarily easy to grasp by a user. It would also complicate measurements. If Z-exaggeration is implemented I think it should be applied globally by adding a scale factor to the Z component of the model cartesian coordinate system. This would, of course, scale the Z ordinate of all elements.

**Comment by pmconne** [comment]
@markschlosseratbentley who asked for this - anyone?

**Comment by markschlosseratbentley** [comment]
> @markschlosseratbentley who asked for this - anyone? We already have elevation exaggeration for terrain - see `TerrainSettings.exaggeration`. Does `ModelDisplayTransformProvider` not work for reality models?

@pmconne It's an item that was on our old backlog that I ported to GH.  Any requester, if one exists, has not re-asked for quite some time.
Not sure about `ModelDisplayTransformProvider` and reality models - would have to check it out.
