### ISSUE TITLE
Drape models on the terrain tool with some issues

### ISSUE THREAD

**Issue by miguelsoares1624** [iTwin/itwinjs-core#3736]
We’ve started using model map layers in WaterSight to drape models on the terrain surface and have noticed a possible bug. If we enable 3D terrain and rotate away from the top view, we start getting jagged lines. If terrain heights are not applied to the map, rotating the model does not cause distortion.
The drape models tool is available on version 3.1, and basically puts any imodel (such as pipes) clamping to the ground when using 3D view, so they do not seem flying in the sky.

![image](https://user-images.githubusercontent.com/106761985/171669320-6e711d9f-12d9-498b-8c0c-22fb61e14e29.png)

**To Reproduce**

1. Go to https://watersight.bentley.com
2. On the left side menu, please click on Real time simulation >> Current simulation
![image](https://user-images.githubusercontent.com/106761985/171677670-b187ac13-da5e-44c8-8150-2745bc4aa76a.png)
3. On the Layers section, please enabled Show terrian
![image](https://user-images.githubusercontent.com/106761985/171677783-b02543d5-7924-490b-b8c6-8d8558683a47.png)
4. Rotate the model using the Shift + scroll button the mouse or use the rotate button 
![image](https://user-images.githubusercontent.com/106761985/171677912-9f14cf5b-277c-453c-acd4-69d36d8160a6.png)
located on the top right side to rotate the view  
5. You will notice those vertical lines being added below the pipes
![image](https://user-images.githubusercontent.com/106761985/171678029-77e1b975-4d96-4141-8cb7-5b6653dae9d5.png)
6. Important note, these particular pipes in the i-model were generated from an hydraulic model uploaded in WaterSight. We can also check the same is happening with the shapefiles we import and that are bridged to an i-model
7. So now lets disabled the pipes from the hydraulic model >> turn off the pipes
![image](https://user-images.githubusercontent.com/106761985/171678319-3a65870c-c54d-4262-8489-dc9d934c8dd5.png)
8 - Now lets turn on the pipes in the i-model that come from a shapefile >> in the layers tab please enabled the pipes 
![image](https://user-images.githubusercontent.com/106761985/171678409-ab9c1221-6a8c-45f5-ac0c-1cfbe9ecd3e1.png)
9 . You can see that  the pipe shapefiles that are bridged to an i-model have the same issue.
![image](https://user-images.githubusercontent.com/106761985/171678499-1b931b77-2471-4a74-8e39-cde6bfd19796.png)
10. This only happens if we use the draping/clamping to the ground tool. If we do not use that tool, the pipes will be flying in the sky but with no vertical lines.

**Expected behavior**
No vertical lines should appear below the pipes

**Screenshots**
See image above

**Desktop (please complete the applicable information):**

- Browser [e.g. chrome, safari] >> Any
- iTwin.js Version [e.g. 2.5.3] >> 3.1

**Additional context**
Please reach to anthony.barletta@bentley.com for questions.

**Comment by pmconne** [comment]
I can reproduce the problem in display-test-app if I attach the layer as an overlay instead of background layer. WaterSight attaches overlay layers.
@miguelsoares1624 please confirm the problem no longer occurs if you attach background layers instead.
@mdastous-bentley do you understand what if any difference there is between draping an overlay and background model map layer? [The documentation](https://www.itwinjs.org/reference/core-common/displaystyles/mapimagerysettings/) offers no description of the distinction between background and overlay.

**Comment by anthony-barletta** [comment]
@pmconne The problem no longer occurs when we attach background layers.
