### ISSUE TITLE
Shader errors should not necessarily block app startup

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#3740]
**Is your feature request related to a problem? Please describe.**
See #3737 for an example. In that specific case, the graphics driver has optimized away a uniform variable. The shader presumably would still operate correctly, but the error thrown essentially terminates the application on startup.

**Describe the solution you'd like**
We do want to be notified of such errors during unit tests and possibly in development builds, but they should not break production builds. We do probably want to log them in production builds.
There may be other, more severe errors that produce the same result. Even if a shader error would cause that shader to fail to operate correctly, that would probably be preferable to terminating the app.

**Describe alternatives you've considered**
None

**Additional context**
To unblock the user as quickly as possible, complete and backport either this issue or #3737 - whichever is faster.

**Comment by markschlosseratbentley** [comment]
@pmconne 

@DStradley thinks this would be the fastest way to unblock the user.

Questions:
- How do we know what mode we are running in?  Production / Unit Test / Development
- How do we log the errors in production builds?
