### ISSUE TITLE
Nodes and count mismatch when hiding similar ancestors

### ISSUE THREAD

**Issue by grigasp** [iTwin/itwinjs-core#3780]
**Repro:**

1. Open [this](https://presentationruleseditor.bentley.com/open-imodel?iTwinId=b27dc251-0e53-4a36-9a38-182fc309be07&iModelId=f30566da-8fdf-4cba-b09a-fd39f5397ae6#editor/N4IgTgrgNgpgzjALiAXCYAdAdgAhxkASwBMCV8QAFAZQIBps8DJY4ycBtRvHTXHpuGgwAKgE8ADjHYEASgHt5iAHLzi8etwEE4UgMaEAZoT0BDRIXlY2qTloG97Dirph7xUmSACS1xKaw9GFV1OAB5Q2p9IxMAYShTOAQbBn5nQT0EpI1bPnSHHT0ACxgAW1NlU1LpWwIAIUI4WPkwGtT87RBMxLhK6ptyLjSOwQBRWGqsRAIndIBdWYEAX3aOglNWynkoMVKWiSKTdkRIGFX8ggBzMHkICTqxeJ72Q1MoBHP0q5u7h4AZUwAIxgUBebw+ix4BEIfgCQQAYoQoIgYGAvIhDnAAHSjWK+OD+QIwbzEHAAXhwAAYAB4AFkpDMZDLq8Jmw2WswWwxW9jyBSEsA8NXIBFihygxBCOU+GSsxEIFisXkoGxgUylWO8cHxhKCUpwAEFlAARA1-ahhHAq1rqtQwTXhQxPJIACgw7pA4zKaumHro+A9DSaLWkHoAlJp2S5osYzIrrOwhvk+RcQK53JJhRRZCDzDBiDq4cE7SlIYJWgl43BDhIVRiBnYo84UyMKBXzJZrDX2C3Wy5imUKlUs-VGs1WpG+51ukk+iPPRMfTnDKi4CJ5F7JogbGWHDym18QPLWnp4146qY9ABrADuG1IIF3eH3fd7a3Auar3dyT-5cAH5RzueY4hpOU4ZFkvTDl4m5LjAK5gGuG6LlMO4Hs4L5TgQx5uGetQgPCLR3mAD6-ksu5zDK-LXLc9yPJBYLvGcu7fLR-xAiCjEIJCmHNixab6EKXg5pW+aFkSUqluhbafp21aELW5hFA2Satm+qbtl+Ck9r+nT-iUgHQfhQbjm0ulQl0kFAfhsFTGEN7WGKSLELZ25suBvGtthhAnnhIogBe17EaR0nPlRfGhRZmlyd+5Dqe++mDtZ-kmaBIDhe+M5QdUMEoYg9mOeKLl5WhHkZc43m+Z2XiEWAwXua25HSZR-E0b89HPLYrxMeVFBtXRALAqCXXgtIB5Nc4XIcvwXJNSASxAA)

2. Expand the hierarchy: 
  ![image](https://user-images.githubusercontent.com/35135765/173065371-c9f86735-b8ad-4fe1-adf2-cf9b04a1830a.png). 
  Notice how `P2` node is duplicated. 

**Investigation notes:** 

The ruleset is set up to contain a lot of duplication, as it traverses two relationships in both directions. To avoid infinite hierarchies we don't return a node if it has a similar ancestor node (produced using the same presentation rule, represents the same instances). However, we don't count the possibility of excluding such nodes when computing nodes count.

**Comment by MartynasStrazdas** [comment]
PR link https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/284431
