### ISSUE TITLE
`InstanceLabelOverride` with empty composite value creates empty labels

### ISSUE THREAD

**Issue by grigasp** [iTwin/itwinjs-core#3791]
Empty label is produced when `InstanceLabelOverride` is used with `CompositeValueSpecification` without any parts or all parts results in empty strings. `Not Specified` string should be used as label in those cases.

**Note:** this issue can't be reproduced in PRRE due to default BIS rules supplying non-empty label overrides.

**Comment by BernardasTe** [comment]
https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/275514
