### ISSUE TITLE
Support suspending/restoring presentation tree state

### ISSUE THREAD

**Issue by grigasp** [iTwin/itwinjs-core#3817]
In some cases there's a need to suspend tree state before a component unmounts and restore it afterwards when a component mounts. The presentation-driven trees currently don't support this. It seems the following things need to be added:
- [ ] Allow constructing `MutableTreeModel` out of an immutable `TreeModel`.
- [ ] Allow users to provide their own `TreeModelSource` to `usePresentationTreeNodeLoader` hook.

**Comment by roluk** [comment]
Related PR: https://github.com/iTwin/itwinjs-core/pull/4030
