### ISSUE TITLE
Presentation NavigationPropertyInfo Type Mismatch

### ISSUE THREAD

**Issue by bingjiez** [iTwin/itwinjs-core#3825]
**Describe the bug**
A new field 'NavigationPropertyInfo' was added to descriptor returned by presentation. It has a property 'classInfo' which is defined as ClassInfo type. But presentation api returns a string for this field.
![image](https://user-images.githubusercontent.com/88792140/174116807-8111014f-39ac-4924-bf08-ecbf7d00585c.png)
![image](https://user-images.githubusercontent.com/88792140/174116887-f6b04273-2c82-4181-9985-2e51b666b25f.png)

**To Reproduce**

1. Open any iModel in viewer
2. Select an element
3. In network tab of developer tool, check on getPageContent request

**Desktop (please complete the applicable information):**

- OS: windows
- Browser chrome
- Version 3.2

**Comment by saskliutas** [comment]
[PresentationRpcInterface](https://github.com/iTwin/itwinjs-core/blob/9a26879daffa15279d2904c52743b582a807dbbc/presentation/common/src/presentation-common/PresentationRpcInterface.ts#L189) returns descriptor in JSON form which type is defined as [DescriptorJSON](https://github.com/iTwin/itwinjs-core/blob/9a26879daffa15279d2904c52743b582a807dbbc/presentation/common/src/presentation-common/content/Descriptor.ts#L156). It is returned in compressed format to avoid duplicating data like `ClassInfo` for property fields created from the same class. In this case `navigationPropertyInfo` type is [NavigationPropertyInfoJSON\<Id64String\>](https://github.com/iTwin/itwinjs-core/blob/9a26879daffa15279d2904c52743b582a807dbbc/presentation/common/src/presentation-common/EC.ts#L193).

If you are using PresentationRpcInterface directly you should parse it from JSON like this: 
``` ts
const descriptor = Descriptor.fromJSON(descriptorResponse);
````

If you are using [PresentationManager](https://github.com/iTwin/itwinjs-core/blob/9a26879daffa15279d2904c52743b582a807dbbc/presentation/frontend/src/presentation-frontend/PresentationManager.ts#L96) on [PresenationPropertyDataProvider](https://github.com/iTwin/itwinjs-core/blob/9a26879daffa15279d2904c52743b582a807dbbc/presentation/components/src/presentation-components/propertygrid/DataProvider.ts#L74) to get content descriptor then it will be parsed from JSON before return.
