### ISSUE TITLE
Add an API to query whether a Viewport's scene is complete (tiles done loading)

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#3828]
**Is your feature request related to a problem? Please describe.**
As described in #3827, we want to read the viewport's image but we have no straightforward way of determining if the image will contain the complete scene or if some geometry will be missing or unrefined.

**Describe the solution you'd like**
A function that will return true if the viewport's scene is complete, such that we can defer reading the image until that function returns true.

**Describe alternatives you've considered**
See hacked-up example code in #3827. Note that it may fail in some cases if for example no tile content has been requested but some child tiles need to be loaded; and that it inappropriately relies on implementation details.

**Additional context**
None.

**Comment by markschlosseratbentley** [comment]
https://github.com/iTwin/itwinjs-core/pull/4199
