### ISSUE TITLE
MiteredPipes with small radius do not render completely

### ISSUE THREAD

**Issue by ImVeryLost** [iTwin/itwinjs-core#3891]
**Describe the bug**
When displaying polyfaces created using 'addMiteredPipes', some faces do not render properly if the pipe radius is very small (10-25mm).  iTwin.js sandboxes don't render the pipes at all (when radius is <=10mm), even after zooming in...

Pipe with 0.05m radius:
![image](https://user-images.githubusercontent.com/61872067/176913004-b426d342-c65c-45bb-86e9-b7f6418e1c94.png)

Pipe with 0.02m radius:
![image](https://user-images.githubusercontent.com/61872067/176912957-eb85d74d-7f06-4af2-a160-81e6759ccc3d.png)
![msedge_aFGu8Rgj1G](https://user-images.githubusercontent.com/61872067/176916082-3a5bf706-0944-4fcf-83de-4484a0814551.png)

Is there a different way to display thin wires and such? 
Or maybe I should be using some specific stroke options?
Tried increasing the `viewport.antialiasSamples` just in case, but it did not have any noticeable effect.

**To Reproduce**
Modified the [iTwin.js sample "simple 3D"](https://www.itwinjs.org/sandboxes/iTwinPlatform/Simple%203d) to draw the following:
```
const curve = [Point3d.create(0,0,1), Point3d.create(5,0,0.8), Point3d.create(10,0,1), Point3d.create(15,0,0.7)];
const pipeBuilder = PolyfaceBuilder.create(StrokeOptions.createForFacets());
pipeBuilder.addMiteredPipes(curve, 0.01);
const pipe = pipeBuilder.claimPolyface();

// Drawing logic
decoratorState.setEdges(false);
decoratorState.setColor(ColorDef.red);
decoratorState.addGeometry(pipe);
```

**Expected behavior**
Would expect all the faces to render regardless of the pipe radius.

**Desktop (please complete the applicable information):**
- iTwin.js Version [3.2.3]

**Comment by pmconne** [comment]
Hi,

When GraphicBuilder creates meshes from the geometry supplied to it, it needs to know a chord tolerance indicating the level of detail to use. By default, this is computed automatically based on the geometry's position within the viewport -- the further it is from the camera, the less detailed it will be. For the 10mm pipe, your pipe builder is producing many very small facets (12 around each section of the center line); the chord tolerance computed by the GraphicBuilder causes these to collapse into degenerate facets.

In [this fork of the sample](https://www.itwinjs.org/sandboxes/new) I reduced the number of facets around the center line to 4. You should see the pipe now, but when you zoom in it will be unacceptably blocky.

This is partly the sample decorator's fault: it computes the tolerance *once* when the viewport first opens (zoomed out) and then reuses those graphics. If instead it created new graphics each time, you would see the pipe appear at a more appropriate level of detail as you zoomed in. However it still wouldn't be visible in the initial zoomed-out view.

You have the option to create a GraphicBuilder via [RenderSystem.createGraphic](https://www.itwinjs.org/reference/core-frontend/rendering/rendersystem/creategraphic/), passing in a [CustomGraphicBuilderOptions](https://www.itwinjs.org/reference/core-frontend/rendering/customgraphicbuilderoptions/) that computes its own chord tolerance. Unfortunately I can't edit the GeometryDecorator.ts file in that sample to illustrate this.

Very long, skinny triangles like yours do have a tendency to get rasterized such that gaps appear where they should be continuous. As you noted, AA is one way to reduce that effect. Another trick is to enable edges for your graphics -- those are always guaranteed to be at least one pixel wide regardless of how far out you zoom.

**Comment by ImVeryLost** [comment]
@pmconne thank you for the detailed explanation! I will look into computing custom chord tolerance. I am already using the createGraphic locally, so hopefully it will be straightforward. 
I have tried displaying edges in the past, same way the GeometryDecorator does in the sample, but unfortunately, it lead to a significant performance drop, and the application became laggy whenever there were more than a hand-full of pipes drawn.
