### ISSUE TITLE
Status bar's "Snap Modes" not having expected effect

### ISSUE THREAD

**Issue by Ellord207** [iTwin/itwinjs-core#3892]
The "Snap Modes" menu is not having the expected effect on tools. This behavior is different than what is observed in Design Review.

**Steps:**

Open viewer app with default ui or [Frontstage Sample](https://www.itwinjs.org/sandboxes/iTwinPlatform/Viewport%20Frontstage).
Start "Measure Tool"
Open "Snap Mode" menu
Select a different mode than "keypoints"

**Expected:**

The measure tool snap will respect the snap mode selected in the "Snap Mode" menu.

**Observed:**

The measure tool snap will continue to snap to keypoints.

- OS: Windows 10
- Browser Chrome & Edge
- Test in Viewer
-- iTwin.js Version: 3.1.2
-- web-viewer-react: 2.0.9

**Comment by calebmshafer** [comment]
@bbastings @NancyMcCallB can you take a look?

**Comment by NancyMcCallB** [comment]
Aha! Looks as though this was fixed recently, in this PR: https://github.com/iTwin/viewer/pull/199, that's why it looks fine to me in the source.
Updating to the latest Viewer source should fix things.
