### ISSUE TITLE
Use Vite for display test app

### ISSUE THREAD

**Issue by kckst8** [iTwin/itwinjs-core#3894]
Replace usage of react-scripts in [display-test-app](https://github.com/iTwin/itwinjs-core/tree/master/test-apps/display-test-app) with [Vite](https://vitejs.dev/). Read the README.md file within the app for instructions on how to run and build for web and/or desktop (electron). Ensure that all works with Vite. The frontend should use Vite, but the backend scripts can remain as is and they are setup to use commonjs modules. You can use the [vite.config.ts](https://github.com/iTwin/studio/blob/main/packages/app/vite.config.ts) file from iTwin Studio as a starting point. Can also use the Studio app for guidance in general, but keep in mind it is electron only.

**Comment by pmconne** [comment]
Please update description to indicate the motivation behind and ramifications of this change.
