### ISSUE TITLE
Document constraints of volume classifiers

### ISSUE THREAD

**Issue by markschlosseratbentley** [iTwin/itwinjs-core#3920]
References need to explain all the constraints for volume classifiers:

API reference for spatial classifiers: https://www.itwinjs.org/reference/core-common/displaystyles/spatialclassifier/
learning articles about features of display system: https://www.itwinjs.org/learning/display/classification/

**Comment by MarcNeely** [comment]
Changes were made to the API reference and the learning article on display/classification.
