### ISSUE TITLE
`core-common` does not compile; Interface 'HttpServerRequest' incorrectly extends interface 'Readable'

### ISSUE THREAD

**Issue by jackson-at-bentley** [iTwin/itwinjs-core#3947]
**Describe the bug 🐛**

I'm using `core-common` as a dependency in a project.

```ts
import * as common from '@itwin/core-common';
```

**To reproduce**

```ts
npm install @itwin/core-common
```

```json
"dependencies": {
  "@itwin/core-common": "^3.2.6"
}
```

**Expected behavior**

The qualified import

```ts
import * as common from '@itwin/core-common';
```

does not produce a compiler error.

```
node_modules/@itwin/core-common/lib/cjs/rpc/web/WebAppRpcProtocol.d.ts:16:18 - error TS2430: Interface 'HttpServerRequest' incorrectly extends interface 'Readable'.
  The types returned by 'destroy(...)' are incompatible between these types.
    Type 'void' is not assignable to type 'this'.
      'this' could be instantiated with an arbitrary type which could be unrelated to 'void'.

16 export interface HttpServerRequest extends Readable {
                    ~~~~~~~~~~~~~~~~~
```

Was `@types/node` accidentally bumped or am I misunderstanding the problem? The return type of `destroy` has changed, please [see the DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/stream.d.ts#L434).

```ts
// Implementors should not override this method, but instead implement `readable._destroy()`.
```

Why is `common` [redeclaring the signature of `destroy`](https://github.com/iTwin/itwinjs-core/blob/master/core/common/src/rpc/web/WebAppRpcProtocol.ts#L37)?

**Comment by pmconne** [comment]
@swbsi

**Comment by swbsi** [comment]
I will try this. Hopefully, the issue will just go away with my forthcoming new packages...
