### ISSUE TITLE
`core-backend` does not compile; Could not find a declaration file for module 'ws'

### ISSUE THREAD

**Issue by jackson-at-bentley** [iTwin/itwinjs-core#3948]
**Describe the bug 🐛**

I'm using `core-backend` as a dependency in a project.

```ts
import * as backend from '@itwin/core-backend';
```

**To reproduce**

```ts
npm install @itwin/core-backend
```

```json
"dependencies": {
  "@itwin/core-backend": "^3.2.6",
}
```

**Expected behavior**

The qualified import

```ts
import * as backend from '@itwin/core-backend';
```

does not produce a compiler error.

```
node_modules/@itwin/core-backend/lib/cjs/IModelSchemaLoader.d.ts:2:43 - error TS2307: Cannot find module '@itwin/ecschema-metadata' or its corresponding type declarations.

2 import type { Schema as SchemaType } from "@itwin/ecschema-metadata";
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@itwin/core-backend/lib/cjs/LocalhostIpcHost.d.ts:4:21 - error TS7016: Could not find a declaration file for module 'ws'. '/home/jackson/bentley/sync/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

4 import * as ws from "ws";
                      ~~~~
```

These all look like unmet dependencies, but as a user of the package I'm not sure it should be my responsibility to add them. Is there documentation that specifies how Bentley expects the iTwin libraries to be used?

**Comment by aruniverse** [comment]
As we had discussed, 

re "@itwin/ecschema-metadata", since it's an optional peer dep and you're importing the entire core-backend package and indirectly using ecschema-metadat you need to explicitly add a dependency on it yourself.

re, ws you can either manually add a dep on @types/ws or enable [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) in your tsconfig.json.

**Comment by jackson-at-bentley** [comment]
I agree about the peer dependency. I'm having second thoughts about `ws` though.

[This line](https://github.com/iTwin/itwinjs-core/blob/4c29314fd547b8b46e4815f4d70dacb7b6489376/core/backend/src/LocalhostIpcHost.ts#L9) dumps everything from `ws` into `core-backend`. If I try to compile `LocalhostIpcHost.ts` with `strict` as a compiler option it becomes my problem.

If I don't use `strict`, everything's okay. But I think `strict` isn't an unusual use case.

**Comment by calebmshafer** [comment]
A `@types/*` package should never be a real dependency of a package as it is only required in order to compile the typescript code directly. However, the fact we're exposing `ws` in this way and it's causing the compiler error for consumers is an issue.

**Comment by calebmshafer** [comment]
@swbsi mind taking a look at this? Not quite sure why it's acting this way currently. We do this in a number of other places so not sure what's unique about this one.

**Comment by swbsi** [comment]
Seems the signature of Readable.destroy changed since @types/node v16 (which we are using).

It returned void then and this now (as of v18).

**Comment by swbsi** [comment]
I tried and all our packages actually compile with the node v18 types.

@calebmshafer Should I keep the node types at v16 and just patch this issue? I know we are officially on node 16 still.

**Comment by calebmshafer** [comment]
@swbsi go ahead and update to v18. If it's compatible we should be able to update, we're going to need to start supporting Node 18 soon anyway.
