### ISSUE TITLE
Improve reality tile purge and preloading

### ISSUE THREAD

**Issue by markschlosseratbentley** [iTwin/itwinjs-core#4000]
Review + integrate this PR into iTwin.js: https://github.com/iTwin/itwinjs-core/pull/4009

Current hurdles:
- increased memory usage (hence increased risk of context loss)
- additive tile selection no longer works properly

**Comment by pmconne** [comment]
#4009

**Comment by markschlosseratbentley** [comment]
Need to revisit the changes.

**Comment by calebmshafer** [comment]
removing from 3.4 due to other priorities
