### ISSUE TITLE
Remove renderer-specific logic from Gradient.Symb getImage() for thematic images

### ISSUE THREAD

**Issue by markschlosseratbentley** [iTwin/itwinjs-core#4024]
Gradient.Symb.getImage() for some reason always returns a width of 1 for thematic images.  This is likely a holdover from when the rendering subsystem used that method to get an image to send to the GPU -- which is no longer the case.  This can be fixed.

**Comment by pmconne** [comment]
The reason is that all the pixels in each row will be identical. This doesn't sound like a bug (but has bug label), it sounds like an enhancement intended to enable @eringram's sample to produce a legend with a width > 1. If that is the use case, couldn't the same be achieved by using CSS to stretch the 1-pixel-wide image to the desired width?

**Comment by markschlosseratbentley** [comment]
@pmconne We use Gradient.Symb.getThematicImageForRenderer() to get a 1px wide image for the GPU, not the public getImage().  The public getImage() does not need a 1px wide enforcement any longer - it was holdover from when the GPU used the public method.  IMO, it makes sense for the public method to return whatever dimensions are requested.

**Comment by markschlosseratbentley** [comment]
@pmconne And yes, CSS can stretch it, and that was done and works. This is incidental cleanup.

**Comment by pmconne** [comment]
I don't see the point. Will you also provide the option to get a horizontal instead of vertical gradient?

**Comment by markschlosseratbentley** [comment]
> I don't see the point.

@pmconne We don't necessarily have to remove the 1px width limit if you have strong objections.  However, there is other weirdness also held over from when this method returned an image to be utilized by the GPU: marginColor shows up as the very bottom and top pixel of the gradient, which may not exactly be what is expected when calling this function to get an image. Do you think that should be changed or left as-is?

> Will you also provide the option to get a horizontal instead of vertical gradient?

Not sure - there is currently no argument specifying that in `ThematicGradientSettingsProps` - I'm guessing a user could rotate it after getting back an image.

FYI @eringram

**Comment by pmconne** [comment]
I guess I see the complaint: the function accepts a `width` parameter but ignores it for thematic gradients, which is surprising and undocumented. I suppose it makes sense to remove that restriction. However, I would also document that specifying a width > 1 is hugely wasteful for thematic gradients.

**Comment by markschlosseratbentley** [comment]
> I guess I see the complaint: the function accepts a `width` parameter but ignores it for thematic gradients, which is surprising and undocumented. I suppose it makes sense to remove that restriction. However, I would also document that specifying a width > 1 is hugely wasteful for thematic gradients.

@pmconne I agree about the problem of the behavior being undocumented. If it behaves this way, it should have been noted originally.
@eringram Mind adding some documentation as part of your PR as Paul suggests above?
