### ISSUE TITLE
Fix Webpack tests after new 3.4.0 native addon

### ISSUE THREAD

**Issue by aruniverse** [iTwin/itwinjs-core#4031]
- [ ] Figure out why tests are failing after new addon and why snapshots only differ on windows
- [x] #4032

Originally posted by @pmconne in https://github.com/iTwin/itwinjs-core/pull/3161#discussion_r938819425

**Comment by calebmshafer** [comment]
@aruniverse is this completed now and can be closed?

**Comment by aruniverse** [comment]
Yea lets close it out, i might create a separate issue for the first item; but sounded like we were going to move away from snapshots so might not be worth the effort
