### ISSUE TITLE
Intermittent test failure calling purgeTileTrees

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#4044]
**Describe the bug**

Relatively frequently, CI jobs will fail running the chrome version of core-full-stack-tests with the following output:
```
TypeError: Cannot read properties of undefined (reading 'purgeTileTrees')
    at IModelTileRpcImpl.purgeTileTrees (/Volumes/Builds/vsts_work_a/73/s/core/backend/src/rpc-impl/IModelTileRpcImpl.ts:202:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RpcSessionInvocation.resolve (/Volumes/Builds/vsts_work_a/73/s/core/common/src/rpc/core/RpcInvocation.ts:165:14)
    at RpcHandler.request (/Volumes/Builds/vsts_work_a/73/s/core/backend/src/LocalhostIpcHost.ts:68:25)
    at /Volumes/Builds/vsts_work_a/73/s/core/backend/src/IpcHost.ts:160:26
    at IpcWebSocketBackend.dispatch (/Volumes/Builds/vsts_work_a/73/s/core/common/src/ipc/IpcWebSocket.ts:165:22)
```

**To Reproduce**

Queue a CI job, e.g. as part of PR process. Observe test failure, if unlucky.
I have failed to reproduce locally. @MichaelBelousov claims to have done so.

**Expected behavior**
The tests should pass

**Desktop (please complete the applicable information):**

- OS: Ununtu 20.04.4
- Browser: chrome (via certa/puppeteer)
- Version 
- iTwin.js Version: appears to have started during development of 3.3.

**Additional context**

The raw log for the failure shows a bit more context:
```
  BriefcaseTxns
WARNING: Tests attempted to load missing asset: "/locales/en-US/Editor.json"
WARNING: Tests attempted to load missing asset: "/locales/en/Editor.json"
    ✔ receives events from TxnManager (740ms)

  Cached decorations
TypeError: Cannot read properties of undefined (reading 'purgeTileTrees')
    at IModelTileRpcImpl.purgeTileTrees (/agent/_work/1/s/core/backend/src/rpc-impl/IModelTileRpcImpl.ts:202:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RpcSessionInvocation.resolve (/agent/_work/1/s/core/common/src/rpc/core/RpcInvocation.ts:165:14)
    at RpcHandler.request (/agent/_work/1/s/core/backend/src/LocalhostIpcHost.ts:68:25)
    at /agent/_work/1/s/core/backend/src/IpcHost.ts:160:26
    at IpcWebSocketBackend.dispatch (/agent/_work/1/s/core/common/src/ipc/IpcWebSocket.ts:165:22)

Returned error code: 1
```

[BriefcaseTxns tests](https://github.com/iTwin/itwinjs-core/blob/fb645c6e5b40ad7b058b150d39c5c0bf51ee1aa7/full-stack-tests/core/src/frontend/standalone/BriefcaseTxns.test.ts#L13) involve modifying the briefcase's contents from the frontend, which triggers the backend to dispatch messages to the frontend, which cause the frontend to `await IModelApp.tileAdmin.purgeTileTrees`.
It appears that IModelApp can get shut down, then one of those messages is received.

#3723 may be related as it modifies backend-frontend communication in browser context and seems to roughly coincide with when the failures began to be observed.

**Comment by MichaelBelousov** [comment]
Finally confirmed a reproduction again. I fresh cloned itwinjs core to commit fb645c6e5b40ad7b058b150d39c5c0bf51ee1aa7"
Then ran the following:

```sh
rush install
rush build
rush build:webpack 
for i in {1..100}; do echo $i; rush cover || break; done; 
```

This reproduces fairly often in my experience.
I am currently trying to reproduce with a loop of `rush cover -o core-full-stack-tests` to reproduce faster.

**Comment by pmconne** [comment]
@swbsi I reverted #3723 in #4045 and run 3 builds (times 3 platforms = 9 runs). The error did not occur. During that time, the error occurred 2 more times in other PRs. In general probably one of every two recent PRs has failed with this error.

Can you please review the changes in #3723 for a potential explanation for this regression?

**Comment by swbsi** [comment]
Will do. That PR definitely affects the ordering and timing of our frontend/backend communication...

**Comment by swbsi** [comment]
Reproduces every time locally if I increase the timeout in the expectEvents function (in BriefcaseTxns.test.ts) to 1000.

Many other tests appear to be opening and closing this imodel (planprojection.bim). Not sure yet how we avoided this in HTTP mode...trying a few things...

**Comment by swbsi** [comment]
Tried in HTTP mode with timeout = 1000 and no issue. So, there is definitely something different...will keep digging.
