### ISSUE TITLE
Support FutureOn texture mapping

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#4297]
**Is your feature request related to a problem? Please describe.**
FutureOn uses a technique for pattern mapping that generates UV coords in the fragment shader to tile the texture and blend it, interpolating between two levels of detail. iTwin.js currently does not support this mode.

**Describe the solution you'd like**
Implement support for this mapping mode.

**Describe alternatives you've considered**
Continue to use UVs pregenerated by the FutureOn connector. This produces a less desirable result. It also prevents us from using different UV coords for normal mapping.

**Additional context**
The technique is described [here](https://github.com/iTwin/itwinjs-core/issues/3989#issuecomment-1228135985).

**Comment by markschlosseratbentley** [comment]
On track for 4.0. (Still need to come up with a name).

**Comment by markschlosseratbentley** [comment]
Still on track.

**Comment by markschlosseratbentley** [comment]
Currently working the backend -- ready to make PRs for these things.
