### ISSUE TITLE
Overlapping component calculations

### ISSUE THREAD

**Issue by YangMieEr** [iTwin/itwinjs-core#4303]
In the actual modeling process, different components will have some overlapping parts, we need to extract, save, highlight or isolate the overlapping parts, etc., or calculate some results such as volume, length, and area of the overlapping parts.

Could iTwin have the ability to fulfill this task？

**Comment by aruniverse** [comment]
Can you elaborate more on your use case? Have you seen iTwin Platform's [clash detection](https://developer.bentley.com/apis/clash-detection/) apis?
