### ISSUE TITLE
Support Eye-Dome Lighting for Point Clouds

### ISSUE THREAD

**Issue by markschlosseratbentley** [iTwin/itwinjs-core#4341]
**Is your feature request related to a problem? Please describe.**
Point clouds are currently unlit.  If they lack color data, their features can be difficult to discern.

**Describe the solution you'd like**
iTwin.js should implement the shader-based EDL (Eye-Dome Lighting) algorithm to improve the depth perception of point clouds.

**Describe alternatives you've considered**
We could just apply the current Ambient Occlusion algorithm to point clouds.  However, based on some research, this would provide an inadequate fuzziness and not distinguish the edges as much as proper EDL.

**Additional context**
- ESRI EDL [description](https://www.esri.com/arcgis-blog/products/arcgis-pro/3d-gis/eye-dome-lighting/)
- Cesium EDL [demo](https://sandcastle.cesium.com/?src=3D%20Tiles%20Point%20Cloud%20Shading.html) and [source code](https://github.com/CesiumGS/cesium/commit/095e152081619c7118d49f412f59006895dfb131#diff-804af0a13ada3fac4f5c32efadf1496b7065d929c66081733817e7e1e5409414)
- Unreal Engine EDL [description](https://docs.unrealengine.com/4.27/en-US/WorkingWithContent/LidarPointCloudPlugin/EnableEyeDomeLightingMode/)
- [EDL for Three.js](https://github.com/potree/potree)

**Comment by markschlosseratbentley** [comment]
Have to decide which approach to take.
What about selectively applying EDL settings to different point clouds in the same view?

**Comment by pmconne** [comment]
Here are two copies of the same point cloud in Cesium rendered with independent EDL settings.
![image](https://user-images.githubusercontent.com/22944042/193807966-ba2694fd-4baf-443a-b956-3b7a46f551b1.png)

**Comment by calebmshafer** [comment]
Released in 3.5.1
