### ISSUE TITLE
Add display settings for point clouds

### ISSUE THREAD

**Issue by markschlosseratbentley** [iTwin/itwinjs-core#4342]
**Is your feature request related to a problem? Please describe.**
When rendering point clouds, iTwin.js currently automatically decides the point size. In some cases, it would be useful to be able to scale this size as a user in order to discern various properties of the scene.

**Describe the solution you'd like**
Add an API to scale the size of the points used by the point cloud shader.

**Describe alternatives you've considered**
None.

**Additional context**
TBD.

**Comment by pmconne** [comment]
I think this is more about applying a scale to the points than about specifying a maximum point size.

**Comment by markschlosseratbentley** [comment]
> I think this is more about applying a scale to the points than about specifying a maximum point size.

@pmconne Adjusted title + description.
