### ISSUE TITLE
electron app / URL scheme 'electron' is not supported with Fetch API

### ISSUE THREAD

**Issue by a-gagnon** [iTwin/itwinjs-core#4377]
**Describe the bug**
Running an electronhost with `ElectronHostOptions.developmentServer = false` will fail to properly load the 'technical preview' badge (aka BetaBadge) from the `core-react` package because it uses the `fetch()` API. Although this problem has surfaced because of the badge, it likely is a problem for any `fetch` request.

**To Reproduce**

1. Create an electron app.
2. Pass `developmentServer: false` in the `ElectronHostOptions`
3. Attempt to use the `fetch()` API to obtain some resource.

**Expected behavior**
The `fetch` call succeeds and returns the expected result.

**Screenshots**
![image](https://user-images.githubusercontent.com/3418768/192587279-26dd057a-cb0c-4d6c-a92e-b2fb5b6c1507.png)

**Desktop (please complete the applicable information):**

- OS: Windows 10
- Browser: electron
- Version: ^14.2.7
- iTwin.js Version: 3.4.0-dev.3

**Additional context**
The problem is likely in `core/electron/src/backend/ElectronHost.ts` as there are various `if` statements that check if we're using the electron protocol.

**Comment by aruniverse** [comment]
@a-gagnon can you try the latest 3.4 dev release? This mightve been fixed already, [see](https://github.com/iTwin/itwinjs-core/blame/master/core/electron/src/backend/ElectronHost.ts#L269)
