### ISSUE TITLE
Svelte Viewer

### ISSUE THREAD

**Issue by kckst8** [iTwin/itwinjs-core#4413]
Create a basic Viewer sample with Svelte similar to the [Angular](https://github.com/iTwin/viewer-sample-angular) and [vanilla typescript](https://github.com/iTwin/viewer-sample-typescript) ones.

**Comment by aruniverse** [comment]
> Check out the Svelte implementation here: [iTwin/viewer-sample-svelte](https://github.com/iTwin/viewer-sample-svelte)

Repo is now public
