### ISSUE TITLE
Incorrect filtering results when filter contains underscores

### ISSUE THREAD

**Issue by grigasp** [iTwin/itwinjs-core#4418]
When filtering Models Tree and the filter contains a "_" character, the backend returns an invalid "occurances" property, which causes the display states control to work incorrectly.

![Image](https://user-images.githubusercontent.com/35135765/193763448-42f36caa-1c9e-41be-a11e-ab86f0910a8c.png)

Similar issue, related to letter casing, was fixed a while ago: https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/272566.

**Comment by BernardasTe** [comment]
https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/286562

**Comment by grigasp** [comment]
> https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/286562

Will need to backport to `3.4.x` when this completes.
