### ISSUE TITLE
Attaching a map-layer with invalid formatId will freeze viewport

### ISSUE THREAD

**Issue by mdastous-bentley** [iTwin/itwinjs-core#4436]
**Describe the bug**
Adding an invalid map-layer definition makes the viewport freeze.  Following uncaught exception is generated:
Error | core-frontend.unhandledException | TypeError: Cannot read properties of undefined (reading 'isOpaque')
    at MapTileTreeReference.initializeLayers (MapTileTree.ts:808:24)
    at MapTileTreeReference.addToScene (MapTileTree.ts:832:37)
    at TiledGraphicsProvider.ts:44:66
    at MapTiledGraphicsProvider.forEachTileTreeRef (MapTiledGraphicsProvider.ts:25:7)
    at Object.addToScene (TiledGraphicsProvider.ts:44:16)
    at ScreenViewport.createScene (Viewport.ts:2258:29)
    at ScreenViewport.renderFrame (Viewport.ts:2356:14)
    at ViewManager.renderLoop (ViewManager.ts:403:10)
    at eventLoop (IModelApp.ts:525:29) 

You must call the API to reproduce the issue:
`const activeViewport = IModelApp.viewManager.selectedView;`
`        const settings  = ImageMapLayerSettings.fromJSON({`
`          formatId: "BadFormat",`
`          url: "https://sampleUrl",`
`          name: "test",`
`          subLayers: [{id: 0, name: "test", visible: true }],`
`        });`
`activeViewport.attachMapLayer({settings});`

**Expected behavior**
It's unclear to me if the 'attachMapLayer' should return an error (because  `MapLayerSource.validateSource` can always be used to validate a layer) but at least the viewport should remain stable and the status of the layer/tiletree should indicate clearly there is something wrong with the layer, so that UI can report it to end-user

**Additional context**
If you add an incorrectly configured layer, say passing an invalid format Id, `MapLayerTileTreeReference.createMapLayerTreeReference` will return undefined, and adds an undefined value to the `MapTileTreeReference._layerTrees` array.
 
Then, it starts failing from everywhere since the code is not expecting an undefined value from on `MapTileTreeReference. _layerTrees`.  I don’t think the solution is simple as not adding a value `MapTileTreeReference. _layerTrees` since the design appears to be assuming `MapTileTreeReference._layerSettings` is a parallel array with `MapTileTreeReference. _layerTrees`.

**Comment by mdastous-bentley** [comment]
@pmconne  My feeling is that the design will need to be adjusted, and would like at least to get your feedback/advice on it, rather than a complete fix.  That will depends how much 're-design' is needed.

**Comment by pmconne** [comment]
@mdastous-bentley that's fine, I'll assign it to myself.
Is this currently causing problems in production?

**Comment by mdastous-bentley** [comment]
No, I detected it while testing other stuff.

**Comment by pmconne** [comment]
Your sample code does not compile. You meant `activeViewport.displayStyle.attachMapLayer`?
