### ISSUE TITLE
`DiagnosticsProps.perf` type should match type of `DiagnosticsOptions.perf`

### ISSUE THREAD

**Issue by grigasp** [iTwin/itwinjs-core#4442]
https://github.com/iTwin/itwinjs-core/pull/4098 missed the `DiagnosticsProps.perf` and now `DiagnosticsOptions` doesn't convert to `DiagnosticsProps` trivially. Type of `DiagnosticsProps.perf` should match type of `DiagnosticsOptions.perf`.

**Comment by pmconne** [comment]
Minor change
