### ISSUE TITLE
Promote and document APIs required to implement a MapLayerFormat

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#4479]
Applications can in theory inject their own map layer formats by implementing `MapLayerFormat`, which is `@beta`. But the guts of that interface and the APIs required to properly implement them are largely `@internal`.
Identify the APIs that need to be promoted. Clean them up and simplify where appropriate and document them thoroughly.
Ideally, produce an example implementation of a custom map layer format, using only `beta` and `public` APIs.

@mdastous-bentley indicated he is doing (a subset of?) this as part of his vector map tiles PR.

**Comment by markschlosseratbentley** [comment]
Also MapLayerImageryProvider.

**Comment by markschlosseratbentley** [comment]
@eringram will see priority

**Comment by markschlosseratbentley** [comment]
fixing no-internal rule first, in order to enable this item.
