### ISSUE TITLE
getCustomViewState3dData should return a pending response

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#4517]
**Is your feature request related to a problem? Please describe.**
#4516 changes this function to query model ranges in a separate thread rather than inside the main JavaScript thread.
This raises the possibility that an extremely long query could cause the request to time out and the frontend to retry.

**Describe the solution you'd like**
Memoize the requests and return a pending response so the frontend will not enqueue another request for the same information.

**Describe alternatives you've considered**
Ignore the problem and hope it doesn't cause significant issues.

**Additional context**
The potential for this issue is exacerbated by some highly-fragmented iModels caused by a temporary inability to vacuum checkpoints.

We probably want to backport this (and related changes) to 3.4.x.

**Comment by aruniverse** [comment]
> We probably want to backport this (and related changes) to 3.4.x.

maybe we should test this out in gpb qa before backporting?

**Comment by pmconne** [comment]
I was just asking @nick4598 if he has a good way to test. I found no tests for it in itwinjs-core repo.

**Comment by aruniverse** [comment]
once a new nightly is published tn, i can update dev env tomorrow and myabe we can use that. not ideal for sure

**Comment by nick4598** [comment]
Yep, I'll open that tomorrow
