### ISSUE TITLE
Tiles are not requested from backend after blob storage request fails

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#4532]
### Discussed in https://github.com/iTwin/itwinjs-core/discussions/4531

@aruniverse @calebmshafer @paulius-valiunas @wgoehrig @swbsi @nick4598
`IModelTileRpcInterface.requestTileTreeProps` succeeds and returns tile trees. We then attempt and fail to download tiles from blob storage, as expected. No subsequent requests are made to `IModelTileRpcInterface` to generate the tiles.

In [TileRequest.dispatch](https://github.com/iTwin/itwinjs-core/blob/e9cda85a63437b1d09644fed8432d2b90ff9ee35/core/frontend/src/tile/TileRequest.ts#L89) an error is caught:
```
"RestError: The specified blob does not exist.
RequestId:82eb8eb2-601e-0035-3a34-e640d4000000
Time:2022-10-22T16:39:51.4561057Z
    at new RestError (http://localhost:3000/static/js/vendors~object-storage.chunk.js:3418:28)
    at handleErrorResponse (http://localhost:3000/static/js/vendors~object-storage.chunk.js:1962:17)
    at http://localhost:3000/static/js/vendors~object-storage.chunk.js:1898:18"
```

Previously, I believe `requestContent` would have returned `undefined` instead of throwing an error, and we would have proceeded via [onNoContent](https://github.com/iTwin/itwinjs-core/blob/e9cda85a63437b1d09644fed8432d2b90ff9ee35/core/frontend/src/tile/IModelTileRequestChannels.ts#L25) to request the tile via rpc.
I recall some changes were made to HTTP status handling in 3.4 which may be relevant.
We need to figure out how this went undiscovered until just now.

**Comment by aruniverse** [comment]
This might be the issue @nick4598 and I was seeing when testing out the 3.5.0-dev.22

**Comment by pmconne** [comment]
I suppose I will update `TileRequest.dispatch` to handle 404 errors.
