### ISSUE TITLE
Fix slow unit tests after switch to i18n-http-backend

### ISSUE THREAD

**Issue by ben-polinsky** [iTwin/itwinjs-core#4546]
This was initially noticed by @raplemie - after #4250. 

When requests for localization resources fail, they are retried. After this PR, unit tests began to retry failed i18n requests. 
An easy fix for unit tests which do not need to test localizations is to use mocks (`EmptyLocalization` works)

**Comment by ben-polinsky** [comment]
@mattbjordan I've done some work on this, let's discuss it tomorrow.

**Comment by aruniverse** [comment]
Will need to cherry pick whatever changes to appui repo
