### ISSUE TITLE
Add documentation for Query Binder and other conncurrent query api

### ISSUE THREAD

**Issue by khanaffan** [iTwin/itwinjs-core#4607]
### Discussed in https://github.com/iTwin/itwinjs-core/discussions/4606

<div type='discussions-op-text'>

<sup>Originally posted by **Adu2120** November  7, 2022</sup>
Can you please describe the indexOrName parameter of all bind function in QueryBinder?

Also please describe the respective index of the name.</div>

**Comment by aruniverse** [comment]
https://github.com/iTwin/itwinjs-core/pull/4667
