### ISSUE TITLE
Bug in the Datasmith Export of animation to Unreal

### ISSUE THREAD

**Issue by hinchmonster** [iTwin/itwinjs-core#4608]
As confirmed by @MichaelBelousov there is a bug in the export of the itwin animation as a combined mesh.

It doesnt export growth simulations correctly as described and shown in the discussion:

https://github.com/iTwin/itwinjs-core/discussions/4599

**Comment by aruniverse** [comment]
We launched the iTwin Exporter for Datasmith last year as a Technology Preview; we received great feedback from early adopters. One of the most significant drawbacks of the iTwin Exporter for Datasmith that we received feedback about was that the file format is unsuitable for large-scale infrastructure projects. One of the core tenets of the iTwin Platform is scalable support for large-scale modern infrastructure projects. With this limitation identified, we have developed the 3DFT technology, which supports large-scale infrastructure model streaming in Unreal Engine.

To get started with 3DFT, register an application on the iTwin Platform by following [these steps](https://developer.bentley.com/tutorials/quickstart-web-and-service-apps/#12-register-your-application).

You can get more information about how to load your iTwin in Unreal at our [Unreal plugin's page](https://github.com/iTwin/unreal-engine-3dft-plugin)
