### ISSUE TITLE
DPTA uses wrong displayedExtents when loading and rendering point cloud tile trees

### ISSUE THREAD

**Issue by markschlosseratbentley** [iTwin/itwinjs-core#4618]
**Describe the bug**
DPTA uses the wrong displayedExtents for point cloud datasets (most likely could happen to all reality data).

**To Reproduce**

1. Use display-performance-test-app to render a local point cloud data set in PNTS format.
4. Observe that the image snapped by DPTA contains a partially rendered point cloud scene
5. If you put some diagnostic code in place, you can see that the displayedExtents of the iModel get expanded -- but too late in the process -- this is because the displayExtents expands when the tile tree loads and notifies all view-managed viewports (which DPTA does not have).

**Expected behavior**
The point cloud should fully render, using the proper expanded displayedExtents.  Viewports should register an event listener for when display extents expand and react by invalidating the controller.

**Screenshots**
TBD

**Desktop (please complete the applicable information):**

- OS: Tested on MacOS and Windows
- Browser: Electron
- iTwin.js Version: 3.x

**Additional context**
N/A

**Comment by pmconne** [comment]
Need to determine whether it's a problem with Orbit, PNTS 3d tiles, or both.

**Comment by markschlosseratbentley** [comment]
We have additionally observed that point cloud waiting also did not work in DPTA before the introduction of the waitForSceneCompletion API.  Unsure if it has worked before in the past.

**Comment by markschlosseratbentley** [comment]
> Need to determine whether it's a problem with Orbit, PNTS 3d tiles, or both.

According to testing done by @DStradley it is both types of point clouds which exhibit the problem.

**Comment by pmconne** [comment]
> According to testing done by @DStradley it is both types of point clouds which exhibit the problem.

That is surprising. PNTS 3d tiles use the same code path as other types of 3D tiles, whereas Orbit uses a completely different code path.
Are reality mesh 3d tiles also affected?

In any case, please be more specific in repro steps than "open a point cloud".
