### ISSUE TITLE
Context reality models don't reuse tile trees

### ISSUE THREAD

**Issue by markschlosseratbentley** [iTwin/itwinjs-core#4654]
**Describe the bug**
When recalling a saved view containing a context reality model, all tiles completely reload, even when the recalled view is the exact same as the current view.

**To Reproduce**

1. Open display-test-app and attach a point cloud reality dataset.  Create and recall some external saved view of the point cloud.
2. Wait for all tiles to load.
3. Recall the same external saved view.
4. Observe that all tiles completely reload.

**Expected behavior**
When recalling a point cloud saved view which shows the same tiles as are currently being viewed, tiles should not reload.

**Screenshots**
N/A

**Desktop (please complete the applicable information):**

- OS: MacOS / Windows
- Browser: Chrome / Electron
- Version N/A
- iTwin.js Version: 3.x branch 'eye-dome-lighting'

**Additional context**
The problem is not reproducible with persistent reality models (those associated with a geometric model).
`RealityTreeId` has a `modelId`. Tile trees are compared by Id - if the model Ids don't match, the tile trees are considered "different" so cannot be shared.
The model Id for a context reality model is generated at run-time from `IModelConnection.transientIds` in `RealityModelTileTree.Reference`'s constructor. Therefore every reference to the same tileset gets a unique model Id and unique TileTree.

Ideally the model Id would be generated for the `TileTree`, not the `TileTreeReference`. However, `ContextRealityModelState` has a `modelId` property that is `@public`. It is used to apply symbology overrides - though that's not meaningful until the tile tree is loaded. It is possible some code outside of itwinjs-core is relying on that modelId being defined before the tile tree loads, though. We might consider having the `RealityModelTileTree.Reference` constructor try to find a matching TileTree and use its model Id, instead of generating a new one.

**Comment by markschlosseratbentley** [comment]
@DStradley FYI

**Comment by markschlosseratbentley** [comment]
TODO: verify if this happens on master, or just 'eye-dome-lighting' branch.

**Comment by markschlosseratbentley** [comment]
@DStradley will check if it happens on master.

**Comment by DStradley** [comment]
Yes, it happens on current master.
(@pmconne I did not assign it to you after realizing that I don't really need this fixed for the demo I am doing)

**Comment by markschlosseratbentley** [comment]
Does this happen only with ESVs?  What about built-in internal views?  Surprising if there is a difference.

**Comment by markschlosseratbentley** [comment]
Look where we are comparing tile tree IDs.

**Comment by DStradley** [comment]
We found that this only occurs for attached models, and therefore is lower priority.
Also, it happens for attached reality meshes, not just point clouds.
Attached models get assigned transient model ids, and that causes a compare to fail which causes the tiles to reload.
