### ISSUE TITLE
in processChanges don't download changesets past the source's current change in IModelTransformer

### ISSUE THREAD

**Issue by simsta6** [iTwin/itwinjs-core#4672]
**Is your feature request related to a problem? Please describe.**
Our product supports transforming iModel from one changeset to other changeset. Currently, IModelTransformer supports transforming iModel from one changeset to the newest one. If this gets implemented it would improve performance for large iModels

**Describe the solution you'd like**
I want small changes in ```remapDeletedSourceElements``` function. First change would involve changing InitFromExternalSourceAspectsArgs interface. We need to add optional string parameter that would indicate end changeset id:

```ts
export interface InitFromExternalSourceAspectsArgs {
  accessToken?: AccessToken;
  startChangesetId?: string;
  endChangesetId?: string;
}
```

The second change would involve ```remapDeletedSourceElements``` itself. First one is to query end change set index. The second one is to add argument to ```createChangeSummaries``` function.

```ts
  private async remapDeletedSourceElements(args: InitFromExternalSourceAspectsArgs) {
    // we need a connected iModel with changes to remap elements with deletions
    if (this.sourceDb.iTwinId === undefined)
      return;

    try {
      const startChangesetId = args.startChangesetId ?? this.sourceDb.changeset.id;
      const endChangesetId = args.endChangesetId;
      const firstChangesetIndex = (
        await IModelHost.hubAccess.queryChangeset({
          iModelId: this.sourceDb.iModelId,
          changeset: { id: startChangesetId },
          accessToken: args.accessToken,
        })
      ).index;
      const lastChangesetIndex = endChangesetId ? (
        await IModelHost.hubAccess.queryChangeset({
          iModelId: this.sourceDb.iModelId,
          changeset: { id: endChangesetId },
          accessToken: args.accessToken,
        })
      ).index : undefined;
      const changesetIds = await ChangeSummaryManager.createChangeSummaries({
        accessToken: args.accessToken,
        iModelId: this.sourceDb.iModelId,
        iTwinId: this.sourceDb.iTwinId,
        range: { first: firstChangesetIndex, end: lastChangesetIndex },
      });
```

**Comment by MichaelBelousov** [comment]
@simsta6 your implementation has a bug. If you process a subset of changes from a source iModel, where in that subset an element was added, but later outside of your processing changeset range but before the current changeset of the source, it was deleted, then the transformer will not correctly insert the element that doesn't exist in the source.

That is the reason the current suggestion, [documented here](https://www.itwinjs.org/reference/core-transformer/imodels/imodeltransformer/processchanges/), is to manually checkout/open the source at the version you want to sync to. Is that something you can do instead? Do you believe there's a way that it could be done better? I am planning in 4.x to introduce a branching API to the transformer, which would do that for you (as well as handling the other low-level transformer options required to perform a branching operation). Would that be sufficient?

**Comment by mindaugasdirg** [comment]
@MichaelBelousov we are opening source at the final changeset which should be processed. However, I think @simsta6 intention was to optimize `remapDeletedSourceElements` that it wouldn't download newer changesets than what source iModel is opened at. [Current implementation](https://github.com/iTwin/itwinjs-core/blob/master/core/transformer/src/IModelTransformer.ts#L482) doesn't do it and without it [createChangeSummaries](https://github.com/iTwin/itwinjs-core/blob/master/core/backend/src/ChangeSummaryManager.ts#L550) will download and process all changesets from the starting changeset including the latest one. So the change summaries will also contain "future" changes that opened source iModel doesn't currently have.

Replacing current `createChangeSummaries` call with the code extract below would only download and extract changes summaries of what's actually being transformed, avoiding the bug you mentioned and would contain suggested optimization:
```ts
const endChangesetIndex = (
  await IModelHost.hubAccess.queryChangeset({
    iModelId: this.sourceDb.iModelId,
    changeset: { id: this.sourceDb.changeset.id },
    accessToken: args.accessToken,
  })
).index;
const changesetIds = await ChangeSummaryManager.createChangeSummaries({
  accessToken: args.accessToken,
  iModelId: this.sourceDb.iModelId,
  iTwinId: this.sourceDb.iTwinId,
  range: { first: firstChangesetIndex, end: endChangesetIndex },
});
```

**Comment by MichaelBelousov** [comment]
@mindaugasdirg thanks for the explanation, that sounds reasonable, I will look into doing that.

**Comment by mindaugasdirg** [comment]
@MichaelBelousov thanks for addressing this.
