### ISSUE TITLE
Accessing iModel metadata

### ISSUE THREAD

**Issue by grigasp** [iTwin/itwinjs-core#4695]
**Is your feature request related to a problem? Please describe.**

We're planning to dynamically create queries which is going to require accessing iModels' metadata - classes, relationships, properties and relationships between them.

**Describe the solution you'd like**

iTwin.js seems to have the API I want in the form of [@itwin/ecschema-metadata](https://github.com/iTwin/itwinjs-core/tree/master/core/ecschema-metadata) package. There are a couple of pieces that I think are missing:

- Using the API on the frontend requires the backend and frontend to support [ECSchemaRpcInterface](https://github.com/iTwin/itwinjs-core/blob/master/core/ecschema-rpc/common/src/ECSchemaRpcInterface.ts). ~~This means the metadata API is useless on frontends using the [general purpose imodel access backend](https://github.com/iTwin/imodel-access-backend).~~ I think the metadata services should be exposed through [IModelReadRpcInterface](https://github.com/iTwin/itwinjs-core/blob/master/core/common/src/rpc/IModelReadRpcInterface.ts) or be automatically registered by the core.

- The API caches the metadata it pulls from the backend, which is great. However, there's no single access point for it, so every component is likely to have its own cache. I addition, they have to track when iModel is closed to make sure to clear the cache. I believe it would be best if the API was accessible through `IModelDb`/`IModelConnection`, which would solve both problems.

**Describe alternatives you've considered**

- Using metadata ECSQL queries to query required information. Downsides:
  - Error prone
  - Inconvenient
  - No caching of frequently accessed information

- Home-grown API like [this](https://github.com/iTwin/itwinjs-core/blob/f94be271286771069d77f9e9981e4a9aaa969a9c/presentation/components/src/presentation-components/instance-filter-builder/ECClassesHierarchy.ts#L45). Downsides:
  - Everyone has to write their own API (error prone, inconvenient)
  - Component-specific caches possibly storing the same information

- [@itwin/ecschema-metadata](https://github.com/iTwin/itwinjs-core/tree/master/core/ecschema-metadata) package. Not really an option since we need the metadata to be accessible using any iTwin.js backend.

**Comment by ColinKerr** [comment]
The general purpose imodel access backend registers the [ECSchemaRpcInterface](https://github.com/iTwin/imodel-access-backend/blob/cf792f86a56351f7a42218c8b86dc04e15b9aef4/src/GeneralPurposeImodeljsBackend.ts#L286) and the schema explorer uses it when you connect to see the schemas in an iModel.

The quantity code on the frontend also uses this the ECScehmaRpcInterface to get schemas with unit definitions.  This exposes a downside with the current approach, you must register the ECSchemaRpcInterface on the frontend as it is not enabled by default.

I agree it would be nice if the schema rpc interface was more integrated.  One way we could go about this would be to use the ecschema-metadata implementation to replace the partial metadata implementation in core-backend.  This would make it easier to get the full metadata, remove the complexity of registering the ECSchemaRpcInterface manually and remove duplicate code.  The downside sis that the core-backend and core-frontend packages would have to consume the ecschema-metadata package.

**Comment by grigasp** [comment]
> The general purpose imodel access backend registers the [ECSchemaRpcInterface](https://github.com/iTwin/imodel-access-backend/blob/cf792f86a56351f7a42218c8b86dc04e15b9aef4/src/GeneralPurposeImodeljsBackend.ts#L286) and the schema explorer uses it when you connect to see the schemas in an iModel.

My bad, didn't test before writing this down - updated the issue description. Still, using this metadata API on the frontend introduces a requirement for the backend. GPB supporting this RPC definitely makes it less of a problem.

> The quantity code on the frontend also uses this the ECScehmaRpcInterface to get schemas with unit definitions. This exposes a downside with the current approach, you must register the ECSchemaRpcInterface on the frontend as it is not enabled by default.

We're thinking about creating a components' package that uses this API. It sounds like the metadata RPC dependency on both the backend and the frontend would need to be documented and that's the most we can do unless it's integrated into `IModelReadRpcInterface`.

> I agree it would be nice if the schema rpc interface was more integrated. One way we could go about this would be to use the ecschema-metadata implementation to replace the partial metadata implementation in core-backend. This would make it easier to get the full metadata, remove the complexity of registering the ECSchemaRpcInterface manually and remove duplicate code. The downside sis that the core-backend and core-frontend packages would have to consume the ecschema-metadata package.

I'm not sure if the footprint of the package is large enough for us to worry about it. Especially since, as you mentioned, that would allow to remove some duplicate code that currently exists in the backend / frontend code. Not to mention metadata cache sharing between different consumers.

**Comment by grigasp** [comment]
I'm closing the issue as `ECSchemaRpcInterface` together with latest improvements to `SchemaContext` are sufficient for our needs.
