### ISSUE TITLE
Update ESLint to version 8.x

### ISSUE THREAD

**Issue by paulius-valiunas** [iTwin/itwinjs-core#4705]
ESLint 7 is quite old and I think they're already working on a v9 release. We should update to v8 very soon. All the ESLint plugins we use should be updated at the same time.

I also think we should enable this new feature to reduce the clutter: https://eslint.org/docs/latest/user-guide/configuring/rules#report-unused-eslint-disable-comments

If there are many breaking changes, we might want to do that after #4046 and then gradually roll out usage of the new config.

**Comment by calebmshafer** [comment]
The update is going to take place in the new [iTwin/eslint-plugin](https://github.com/iTwin/eslint-plugin) repo instead of continuing in the core repo.

**Comment by yashincontrol** [comment]
Set up a cospace and worked on the updates. Was going to raise a PR, but @wgoehrig already has a PR https://github.com/iTwin/eslint-plugin/pull/6 and several others on core to fix the linting errors that accompany the update.
