### ISSUE TITLE
Deprecate all APIs to be removed in 5.0

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#4724]
A `@public` API marked `@deprecated` in major version N must continue to be supported in major version N+1 and can be removed in version N+2.
Any APIs we wish to remove in 5.0 (the earliest possible according to this rule) must be marked deprecated in 3.x before release of 4.0.

**Comment by calebmshafer** [comment]
Presentation: https://github.com/iTwin/itwinjs-backlog/issues/592

**Comment by khanaffan** [comment]
@pmconne Following api need to be deprecated or removed. This mislead some user into calling it which result in performance issue. They should use ste() or query instead.

```ts
  /** @internal added this back in for testing purposes */
  public async stepAsync(): Promise<DbResult> {
    return new Promise((resolve, _reject) => {
      this._stmt!.stepAsync(resolve); // eslint-disable-line @typescript-eslint/no-non-null-assertion
    });
  }```

**Comment by pmconne** [comment]
@khanaffan it's `@internal`. It could be deleted right now without violating any API support policy.

**Comment by ColinKerr** [comment]
> @khanaffan it's `@internal`. It could be deleted right now without violating any API support policy.

Since we are so close to 4.0 why not wait and remove it in 4.0 just in case there are any callers

**Comment by calebmshafer** [comment]
closing this issue as completed. We will have a limited 3.7 release but it should not be a big shift in API from 3.6 as most of our attention has now shifted to 4.0 development.
