### ISSUE TITLE
remove `xml-js` dep in core-frontend

### ISSUE THREAD

**Issue by aruniverse** [iTwin/itwinjs-core#4762]
`xml-js` has a dep on `sax` which uses node's `stream` apis.
with webpack 5 nodejs core polyfills were removed, also newer modern bundlers like vite dont polyfill node apis by default.

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/11051042/205725818-618378da-548c-4ee7-845a-697931ec6128.png">

we only use `xml-js` in `WmtsCapability`; I havent investigated any further, but since this is a client side library, we could probably be able to just use [window.DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) and remove the dep

**Comment by mdastous-bentley** [comment]
@aruniverse Started looking into this, but looks like the frontend tests wont start from VS code, any idea?

**Comment by aruniverse** [comment]
I've never ran the core-frontend tests from vscode before so dont know why its broken now
![image](https://user-images.githubusercontent.com/11051042/205981444-f4c1353b-a0a1-4b01-a52b-e458794a5014.png)

Have you tried changing the `type` ?
![image](https://user-images.githubusercontent.com/11051042/205981524-91c006eb-7c8b-49ae-9a4e-0f3f5014c91d.png)

**Comment by pmconne** [comment]
Need to run `npm run webpack:test`
