### ISSUE TITLE
Drop Node@12, Node@14, Node@16 support

### ISSUE THREAD

**Issue by aruniverse** [iTwin/itwinjs-core#4777]
See node support https://github.com/nodejs/release#release-schedule

Node12 reached end of life a while back
Node14 reaches end of life 4/30/23, which should be close enough to our hopeful 4.0 release
Node16 reaches end of life later this yr, was moved up due to [OpenSSL](https://nodejs.org/ar/blog/announcements/nodejs16-eol/)
	- instead of dropping it later in another major (which we don't know when it will be) get ahead and do it now

- [x] Drop Node 12
- [x] Drop Node 14
- [x] Drop Node 16
- [x] ~drop custom core-bentley guid in favor of using crypto.randomUUID (available both in node & web) ?~ `crypto` is not available in browsers and `Crypto` is only supported from Node 19.
- [ ] #5078

**Comment by paulius-valiunas** [comment]
Interesting note here, seems like the Node API is slightly different than the browser API... it would be good to keep this in mind when migrating:
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID#browser_compatibility

**Comment by paulius-valiunas** [comment]
what is our support policy for browser versions? The browser API seems to be relatively new, let's make sure we support the versions we're promising to support.

**Comment by GytisCepk** [comment]
@aruniverse Electron is still running on Node 16 ([version table](https://github.com/electron/electron/blob/main/docs/tutorial/electron-timelines.md#timeline)).

**Comment by aruniverse** [comment]
> @aruniverse Electron is still running on Node 16 ([version table](https://github.com/electron/electron/blob/main/docs/tutorial/electron-timelines.md#timeline)). 

Aww man. Thanks for letting me know. Hopefully they'll have it updated by the time we release 4.0. If not we will need to continue supporting 16 then :/ 

Gytis, mind making an issue for the 4.0 backlog to drop electron support for the version electron doesn't support/maintain anymore based on that table?

**Comment by pmconne** [comment]
We should probably update our matrix of supported platforms in docs/learning/SupportedPlatforms.md to break it down by major release.
That information might also need to be made more visible, perhaps in api-support-policies.md.
Our README simply says "Node 18".

**Comment by aruniverse** [comment]
Should we also update our es target? right now we target es2019, but if we're saying we support node18+ then we could bump to es2021 or es2022. https://kangax.github.io/compat-table/es2016plus/

**Comment by GytisCepk** [comment]
> Should we also update our es target? right now we target es2019, but if we're saying we support node18+ then we could bump to es2021 or es2022. https://kangax.github.io/compat-table/es2016plus/

Upgrading to es2021 makes sense to me. 

Not sure about es2022: es2022 compatibility seems to be a bit "spotty" at the moment.

**Comment by aruniverse** [comment]
when we start working on this task, id first drop 12 & 14, and then drop 16 a bit later

**Comment by GytisCepk** [comment]
PR for dropping Node 12 and Node 14: https://github.com/iTwin/itwinjs-core/pull/5012.

**Comment by GytisCepk** [comment]
PR for dropping Node 16: https://github.com/iTwin/itwinjs-core/pull/5077.
