### ISSUE TITLE
Update release tags

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#4851]
**Is your feature request related to a problem? Please describe.**
iTwin.js employs [release tags](https://www.itwinjs.org/learning/guidelines/release-tags-guidelines/) to convey API stability to consumers of the library. Notably, we discourage consumers from using `beta` APIs in production and from using `alpha` APIs at all. The goal is for the APIs to evolve based on testing and feedback until they can be promoted to `public`, or abandoned.

Unfortunately, API release tags frequently remain static, leading consumers to either ignore non-`public` APIs assuming they are not ready for broader adoption; or ignore release tags, consuming non-`public` APIs in production and risking stability if the API changes in the future.

**Describe the solution you'd like**
We need to evaluate our non-`public` APIs and update their release tags appropriately to match their current levels of maturity.
Note: any API that is already in broad production use or intended for third-party consumption is a strong candidate for promotion to `public`. For each such API, file a new issue and a PR to adjust the tags. While doing so, ensure documentation is up to date and sufficient.

**Describe alternatives you've considered**
None.

**Additional context**
A related issue is needed for marking APIs as `deprecated` for 3.6 prior to 4.0 release.

Categories with my best guesses at who should review + address them:
- [x] accudraw @bbastings
- [x] appui @NancyMcCallB @raplemie 
- [ ] devtools - @calebmshafer do you know who owns this?
- [X] display @markschlosseratbentley @pmconne
- [x] crash reporting @swwilson-bsi? @nick4598?
- [X] frontend @pmconne
- [X] backend @pmconne
- [x] markup @bbastings?
- [X] ~~ecdb @ColinKerr? @khanaffan? ECJsonTypeMap.~~
- [X] geocoord @pmconne 
- [x] geometry @dassaf4
- [ ] i18n @calebmshafer who owns this now?
- [x] map-layers @eringram @mdastous-bentley 
- [x] presentation @grigasp 
- [ ] quantity @ColinKerr @calebmshafer is there a separate issue for quantity formatting package yet?
- [x] rpc @swbsi 
- [x] telemetry @paulius-valiunas 
- [x] tools @bbastings 

[categorized.txt](https://github.com/iTwin/itwinjs-core/files/11017849/categorized.txt)

**Comment by pmconne** [comment]
@paulius-valiunas @wgoehrig Our OpenTelemetry APIs are intended for use by applications, yet they remain `alpha`. Please evaluate.

**Comment by pmconne** [comment]
@calebmshafer what's up with [FeatureGates](https://github.com/iTwin/itwinjs-core/blob/master/core/common/src/FeatureGates.ts)? We only use it in one example snippet, and it's `@internal` so apps shouldn't use it.
@swwilson-bsi uses it in [RobotWorldEngine](https://github.com/iTwin/itwinjs-core/blob/master/example-code/app/src/backend/RobotWorldEngine.ts) but example code should not use `@internal` APIs.

**Comment by calebmshafer** [comment]
@pmconne I suggest we completely remove that API if that only use in the sample and currently marked `internal`. We can add it back later if we feel there is a need in the future.

**Comment by aruniverse** [comment]
Feature Gating should probably be done at the app/product level imo

**Comment by paulius-valiunas** [comment]
> @paulius-valiunas @wgoehrig Our OpenTelemetry APIs are intended for use by applications, yet they remain tagged as `alpha`, indicating applications should not use them. Please evaluate.

We should have promoted them to beta a while ago. @wgoehrig what do you think, should we go straight to public? The only thing I'm worried about is how different package managers would treat the peerDependenciesMeta field - some might install opentelemetry packages automatically even when the user doesn't want them. But I guess we can change that later, even if the typescript API is public.

**Comment by calebmshafer** [comment]
@paulius-valiunas I agree with going to beta. Not sure if we have enough experience with it, and the issue you raised, to go to beta. However, it would be good to document them and let people know they're open to start using.

**Comment by calebmshafer** [comment]
@wgoehrig @paulius-valiunas @nick4598 another API that I'd like to take a look at is the [hubAccess](https://github.com/iTwin/itwinjs-core/blob/master/core/backend/src/IModelHost.ts#L110) that's currently marked as beta in IModelHost. It's critical to almost all workflows and we've been fairly liberal with making breaking changes to it for the v2 checkpoint work. However, we need to get to a place where that is stable from release to release. Any idea where we stand for that one? Maybe warrants its own item to start ironing it out?

**Comment by calebmshafer** [comment]
@paulius-valiunas for 4.0 can we remove the [IModelHost.tileCacheService](https://github.com/iTwin/itwinjs-core/blob/master/core/backend/src/IModelHost.ts#L121) and clean up those APIs now that we have teh replacements out there?

**Comment by nick4598** [comment]
> @wgoehrig @paulius-valiunas @nick4598 another API that I'd like to take a look at is the [BackendHubAccess](https://github.com/iTwin/itwinjs-core/blob/master/core/backend/src/BackendHubAccess.ts#L189) and [hubAccess](https://github.com/iTwin/itwinjs-core/blob/master/core/backend/src/IModelHost.ts#L110) that's currently marked as beta in IModelHost. It's critical to almost all workflows and we've been fairly liberal with making breaking changes to it for the v2 checkpoint work. However, we need to get to a place where that is stable from release to release. Any idea where we stand for that one? Maybe warrants its own item to start ironing it out?

I created a separate item to track this: https://github.com/iTwin/itwinjs-core/issues/4885

**Comment by paulius-valiunas** [comment]
> @paulius-valiunas for 4.0 can we remove the [IModelHost.tileCacheService](https://github.com/iTwin/itwinjs-core/blob/master/core/backend/src/IModelHost.ts?rgh-link-date=2023-01-06T17%3A46%3A05Z#L121) and clean up those APIs now that we have teh replacements out there?

yup, at least that was my plan initially. Here's an issue for that: https://github.com/iTwin/itwinjs-core/issues/4887

**Comment by calebmshafer** [comment]
@pmconne anything specific you want to do with this Issue still or can we close this general one out?

**Comment by pmconne** [comment]
We have API usage reports from appui and some of the apps to go through.
Also, telemetry is still alpha.

**Comment by pmconne** [comment]
I am removing from these outdated reports references to APIs that have migrated out of itwinjs-core repo.

**Comment by pmconne** [comment]
Removed outdated items, categorized, and sorted.
Categories with my best guesses at who should review + address them:
- accudraw @bbastings
- appui @NancyMcCallB @raplemie 
- devtools - @calebmshafer do you know who owns this?
- display @markschlosseratbentley @pmconne 
- crash reporting @swwilson-bsi? @nick4598?
- frontend
- backend
- markup @bbastings?
- ecdb @ColinKerr? @khanaffan? ECJsonTypeMap.
- geocoord @AlainRobertAtBentley
- geometry @dassaf4
- i18n @calebmshafer who owns this now?
- map-layers @eringram @mdastous-bentley 
- presentation @grigasp 
- quantity @ColinKerr @calebmshafer is there a separate issue for quantity formatting package yet?
- rpc @swbsi 
- telemetry @paulius-valiunas 
- tools @bbastings 

[categorized.txt](https://github.com/iTwin/itwinjs-core/files/11017849/categorized.txt)

**Comment by paulius-valiunas** [comment]
I think there's some confusion between OpenTelemetry and iTwin.js TelemetryClient. @calebmshafer who should pick up the latter one? I see it's unchanged since early 2.x, does anyone still use it? Does anyone still own it? :D

**Comment by pmconne** [comment]
> I think there's some confusion between OpenTelemetry and iTwin.js TelemetryClient.

That happens when the same name is used for two different things. :)

> does anyone still use it?

According to the usage reports, both appui and pineapple do.

**Comment by paulius-valiunas** [comment]
> According to the usage reports, both appui and pineapple do.

ok good point... but they only use the `TelemetryManager` and I can't find any actual implementation of `TelemetryClient`. If that's actually true, the manager isn't actually doing anything so we should probably just remove it.

**Comment by paulius-valiunas** [comment]
> I think our OpenTelemetry references should mostly be named to tracing today as that's what they're exposing (at least from my look at the API). Since we implement Logging and Tracing separately, I think they should be handled separately in the API.

Technically you're right, but in practice they're much more intertwined. Our logs are attached as span events to OpenTelemetry traces, and our traces wouldn't be useful at all without logs attached to them. I like to think of our OpenTelemetry as an augmentation of our logging system rather than a completely separate concept. Also, "tracing" is not very clear either, it could be confused with trace level logging or something similar. I think `enableOpenTelemetry` is good as it is - even if people don't know what OpenTelemetry is, the "open" in the name will probably spark their curiosity and they'll look it up. Everything else already has "tracing" in its name.

**Comment by pmconne** [comment]
@calebmshafer there were several questions for you (and some for others) in my categorized checklist. I have moved that checklist to the issue description. Please review.

**Comment by calebmshafer** [comment]
> crash reporting
@wgoehrig thoughts on where this one is at currently and what is left for us to start promoting this, to at least beta?

> It might sound crazy but we could instrument frontends to send telemetry data through OpenTelemetry, and then TelemetryManager or its replacement would just be the frontend equivalent of enableOpenTelemetry.

@paulius-valiunas good point, I tend to agree with the points you made here. Mind breaking that out into its own Issue with some of the details you have here and the proposal to align both of our different telemetry APIs?

> i18n

@pmconne mind sending me separately the usages of those APIs? Want to understand how the unregister methods are being used.

> quantity

@pmconne, no I have not created one yet. I will do that now, although it will branch in many directions I assume and will not move for 4.0 release out of alpha. However, will need to be addressed in 4.x to move forward (and a goal we should have with major release).

**Comment by NancyMcCallB** [comment]
- viewState.getStandardViewMatrix
+ StandardView.getStandardViewMatrix

Should be
+StandardView.getStandardRotation

Any verdict on Viewport.synchWithView()? Will it be promoted or is there a public alternative?

**Comment by paulius-valiunas** [comment]
> Mind breaking that out into its own Issue with some of the details you have here and the proposal to align both of our different telemetry APIs?

I didn't have much to go by because I'm unfamiliar with the `TelemetryManager` API and its usage, but I guess this is a start: https://github.com/iTwin/itwinjs-core/issues/5278

**Comment by grigasp** [comment]
@pmconne, what are we expected to do with APIs that are **and should be** `@internal`, but are in the list?

**Comment by pmconne** [comment]
> what are we expected to do with APIs that are and should be @internal, but are in the list?

Suggest alternative ways to achieve what the offending code is trying to do, such as using a different, public API.
For example, some teams were doing weird stuff with internal APIs to make canvas decorations be included when reading a viewport's image. I suggested they file an issue for a new public API that would support this feature. For the rest of the internal APIs they were using, I provided the following adjustments:
```
- for (const [id, model] of iModel.models.loaded)
+ for (const modelState of iModel.models)

- viewport.changeModelDisplay(iModel.models.loaded, false)
+ viewport.replaceViewedModels([])

- viewport.view.createScene
+ viewport.createScene

- viewport.view.forEachTileTreeRef
+ viewport.forEachTileTreeRef

- viewState.getStandardViewMatrix
+ StandardView.getStandardViewMatrix

- viewport.viewingSpace.getPixelSizeAtPoint
+ viewport.getPixelSizeAtPoint

- MockRender.App.startup
- MockRender.App.shutdown
+ NoRenderApp.startup
+ IModelApp.shutdown
```

**Comment by tm-zub** [comment]
@calebmshafer, as this issue was tied with 4.0 milestone release that is completed a long ago, are you OK for closing this issue and marking as done?

**Comment by calebmshafer** [comment]
yes, I'm good with closing. We already opened new issues for some of the outstanding changes that are needed.
