### ISSUE TITLE
Issue converting latitude and longitude to spatial coordinates

### ISSUE THREAD

**Issue by DRHoltman** [iTwin/itwinjs-core#4901]
I'm creating a "Locate Me" function and I have the lat/longs but I'm seeing inconsistent results when converting them to spatial coordinates.

For testing I'm using the lat/longs for the Bentley's Austin Texas office for all tests:
Lat: 30.36936664900865 Long: -97.74329476841908

I can only get it to work in the following sandbox:
   https://www.itwinjs.org/sandbox/DerekHoltman/Derek%20Testing
Using cartographicToSpatialFromEcef and the Metrostation model I get the correct results:
   1134495.7502543565, -1951322.9502983307
Using cartographicToSpatialFromGcs and the Metrostation model I get the wrong results:
   1198251.9361718288, -2025549.2996983863   
   This is north of San Antonio and affects the current sessions orientation of the model which is seen when selecting Top of the cube.
Note: I do not know how to  check the itwin version in the sandbox.

I also have the following test app that has the same code:
   https://dev.azure.com/bentleycs/AssetWise%20-%20Energy%20Infrastructure/_git/powerbi-report-grouping?version=GBUpgraded-grouping-mapping-widget-to-0.8.2-package-lock
It is using itwin 3.2.8 but I have seen the following results with itwin 3.5.1 in another app.
Using cartographicToSpatialFromEcef and the QA-RockyMountCircuits-LatestChangeset model I get the wrong results:
   -1155569.9807568148, -202005.6185020086	South Carolina
Using cartographicToSpatialFromGcs and the QA-RockyMountCircuits-LatestChangeset model I get the wrong results:
   -1187585.3929570804, -205278.5211527112	Pacific Ocean

To start test app:
   npm install
   npm start

To test in both sandbox and test app:
A decorator tab has been added to the right side panel.
select decorate to run the code above and watch debug output for coordinates.
There is a useEcef constant that is used to control which code it hits.

Note: the imodels are geolocated.
Does this have something to do with the imodels? my environment? or something else?

**Comment by markschlosseratbentley** [comment]
@mdastous-bentley do you have any suggestions?

**Comment by mdastous-bentley** [comment]
Couple of points:

- The testing point is located in Texas while the dataset is in North Carolina, that's far away.  Do we get the same result if the testing point is location near the model data?  ECEF transformation should only be used near the imodel data location.
- I see this iModel is geo located (EPSG:3404), so based on the [documentation](https://www.itwinjs.org/learning/geolocation/)  `cartographicToSpatialFromGcs` should be used to get accurate result from the backend, I really don't understand why its not the case with the sandbox.
- I would suggest testing with another iModel generated using the MicroStation connector, using the same area and GCS, that way we can check if it's an iModel data issue.

**Comment by DRHoltman** [comment]
Using hard coded NC Englewood Recreation Park location:
	Lat: 35.954177 Long: -77.829353
Which is in the same area as the data.
cartographicToSpatialFromEcef and cartographicToSpatialFromGcs both return the correct location: 
	715204.1659459114, 245139.30506102668

I also tried using cartographicToSpatialFromGcs going to the Austin Office on the following model that was generated from the MicroStation Connector: http://localhost:3000/?iTwinId=cb6b9001-96ff-4af8-aa4d-8571973a6e45&iModelId=cb64c9a2-8296-4aef-bcd3-787912e91aa1
It is using the same area and GCS.
It also returned the coordinates in the Pacific: -1187585.3929570804, -205278.5211527112

**Comment by mdastous-bentley** [comment]
`IModelConnection.cartographicToSpatialFromGcs` is mostly a wrapper on top of `getIModelCoordinatesFromGeoCoordinates` RPC.

@pmconne Who maintains this API?

**Comment by pmconne** [comment]
@mdastous-bentley it has no dedicated maintainer.

**Comment by markschlosseratbentley** [comment]
@DRHoltman Not 100% sure on the timing -- but we are now internally aware of the issue you are seeing and are asking around.  We'll update this item with findings.

**Comment by mdastous-bentley** [comment]
Hey Derek,

Myself and @AlainRobertAtBentley looked into this.

**First thing:**
Your iModel's GCS is set to EPSG:3404, which domain of validity look like this:
![image](https://user-images.githubusercontent.com/8309609/213747211-372b7f12-91b3-4e4b-a039-6643c394ea34.png)

You cannot expect a point located in Texas to be accurate with this GCS.  In my tests, the point was located near Austin, but not exactly where it should be.
You might consider setting your iModel's GCS to something like EPSG:5070 which cover the United States:
![image](https://user-images.githubusercontent.com/8309609/213748183-aeccd164-5049-448c-9a1a-6d569aad8555.png)

**Another point**, 
I noticed some display issues with decorations when the Globe mode of your view was set to 'Ellipsoid' you might consider using 'Plane' for now by using something like this:
` activeViewport?.view.displayStyle.changeBackgroundMapProps({globeMode: GlobeMode.Plane});`

**Comment by DRHoltman** [comment]
Thanks guys for looking into this...
I'm not sure if we can require our users to use this GCS so we are going to add a check to see if the lat/long is within the GCS extents (converted to lat/longs)  and error out only if outside the area.
I guess what is still confusing, is why this worked in v2.
Here is a link to V2 working on the same area:
https://openutilities-dts.qa.aw-au.bentley.com/852f17d6-5a8b-423b-9ee9-d2cb17722de4/viewer/https%3A%2F%2Fopenutilities.qa.aw-au.bentley.com%2F%3Fproject%3D852f17d6-5a8b-423b-9ee9-d2cb17722de4%26isEmbedded%3Dtrue%26resultId%3D425ba9f6-7b81-40d7-99ec-cc0182e0cee5

**Comment by mdastous-bentley** [comment]
Do you know which method you were using to translate your lat,long coords?  I cannot see any request to the backend.

**Comment by DRHoltman** [comment]
I just ran it. 8:10AM Central time. It should be using cartographicToSpatialFromEcef.

**Comment by mdastous-bentley** [comment]
That's interesting, this tool uses Bing services... and calls `ViewState3d.lookAtGlobalLocationFromGcs` to adjust the view, would be interesting to see if call directly this method would work too.

**Comment by markschlosseratbentley** [comment]
Can this item be closed?

**Comment by DRHoltman** [comment]
Yes as I found a work around.
