### ISSUE TITLE
Add version info to deprecated tags

### ISSUE THREAD

**Issue by aruniverse** [iTwin/itwinjs-core#4909]
@aruniverse @calebmshafer know anyone who's bored and wants to write a script to add `@deprecated in 3.x` to existing tags?

_Originally posted by @pmconne in https://github.com/iTwin/itwinjs-core/issues/4907#issuecomment-1379214584_
      
Our API deprecation policy mandates a minimum number of major releases before a deprecated API can be removed. We need to make it clear to users in what version an API became deprecated so that they can understand when it becomes eligible for removal.

Replace existing `@deprecated` tags with `@deprecated in 2.x` or `@deprecated in 3.x`.

UI APIs contain many 2.x deprecations and will be handled separately in https://github.com/iTwin/itwinjs-backlog/issues/613.

**Comment by pmconne** [comment]
Consider adding a lint rule to enforce this.

**Comment by MichaelBelousov** [comment]
just a thought:

```sh
git checkout release/2.x
git checkout -b deprecated-2.x
sed 's/@deprecated/@deprecated in 2.x/' $(g ls-files '*.ts')
git add . && git commit -m "deprecations for 2.x"
git checkout -b deprecated-3.x master
git merge deprecated-2.x
perl -pie 's/@deprecated(?! in 2.x)/@deprecated in 3.x/' $(g ls-files '*.ts')
git add . && git commit -m "deprecations for 3.x"
```

no guarantee it will work and the merge won't be a massive pain. If we already have a list of deprecated APIs from 2.x or the resulting list is small, may be easier to do manually

**Comment by raplemie** [comment]
Do we want to add minor as we go, or stay at the version ? (I will deprecated stuff in upcoming days and I'm not sure if we want to go `@deprecated in 3.6.0` or stay at `@deprecated in 3.x` ?)

**Comment by pmconne** [comment]
I did the easy part -- a lint rule will be useful to ensure future deprecations include version info. For example, in #4923.
