### ISSUE TITLE
Background map-layers does not blend with base map when is set to solid color

### ISSUE THREAD

**Issue by mdastous-bentley** [iTwin/itwinjs-core#4980]
map-layer imagery tiles are not blended with base map when it's set to a solid color.  Same map-layer blends correctly when base map is a map-layer definition, such as bing. Also moving this cannot be reproduced if map-layer is added to overlay map  instead of background map.

1. Open a geo-referenced imodel and fit the view around the Philadelphia area.
2. Run the following key-in to add a background map-layer:
`fdt attach arcgis maplayer https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer hydro`
3. Use this key-in to set the background to solid red color: 
 `fdt set map base color 255 0 0`

It currently looks like this:
![image](https://user-images.githubusercontent.com/8309609/214683389-4bc47fd6-014f-44db-8593-1d30fc95782d.png)

Instead it should blend with the red background color:
![image](https://user-images.githubusercontent.com/8309609/214684562-ab4465e7-b1bf-4332-9c07-e6e58b37ba06.png)

This has been tested with master version.  I can confirm it was working fine with 3.0.2 and it's broken since at least 3.2.3.

**Comment by markschlosseratbentley** [comment]
@mdastous-bentley do you need help looking into this?

**Comment by markschlosseratbentley** [comment]
@mdastous-bentley is a user experiencing this?

**Comment by mdastous-bentley** [comment]
> @mdastous-bentley is a user experiencing this?

No, it was discovering during internal testing.

**Comment by markschlosseratbentley** [comment]
Erin is taking a look.

**Comment by markschlosseratbentley** [comment]
did image tests run --- resolving the issues found in the image tests run.
