### ISSUE TITLE
Experiment with tile decoding in web worker

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#5030]
**Is your feature request related to a problem? Please describe.**
Currently we decode all tile content on the main JavaScript thread. This introduces framerate hiccups/stalls while navigating the view, negatively impacting responsiveness, fluidity, and perceived performance.

**Describe the solution you'd like**
Determine what parts of tile content decoding could be moved to a web worker to improve responsiveness.

**Describe alternatives you've considered**
None

**Additional context**
A framerate of 60 FPS would require that we spend no more than ~16 ms executing JavaScript per frame (in total - not just for tile-related stuff).

**Comment by pmconne** [comment]
Decoding iModel tiles and glTF content is not a good candidate for web workers, because the data is already in a format ready to be uploaded to the GPU and allocation of WebGL resources (textures, buffers, etc) must occur on the main JavaScript thread.

Operations that transform the content are good candidates for web workers. In particular:
- When OpenStreetMap Buildings are displayed, I recorded an average of 34ms and a maximum of 67ms decoding time per tile. I have not yet identified where that time is spent.
- When 3d terrain is enabled, average 3mx but max 55ms. The prime offender is upsampling, which creates new vertices.
- When frontend schedule scripts are enabled, the disassembly and reassembly of the iModel tile contents should be done on a worker thread.
- #4474 suggests that some map layer tile contents ought to be generated in a worker.

Additional considerations for use of web workers:
- Currently, section-cut geometry (including for schedule script cutting planes as described in https://github.com/iTwin/itwinjs-backlog/issues/151) require specially-made tiles, where the geometry is produced on the backend. It may be possible to include in the tile content information about which meshes are open or closed, and produce the section-cut geometry on the frontend. If so, it should be done in a web worker.
- Currently, visible edges are computed on the backend. It could be possible to include edge visibility information in the tile content and produce the edges on the frontend; if so, it should be done in a web worker. This is relevant to our experiments with using mesh export service to produce tiles in 3d tiles 1.1 format from iModels.

**Comment by pmconne** [comment]
When decoding OSM building content, most of the time is spent converting to a VertexTable.
![image](https://user-images.githubusercontent.com/22944042/219395363-84310981-d94a-46ec-98c7-04f5245bb25d.png)

**Comment by markschlosseratbentley** [comment]
> Currently, visible edges are computed on the backend. It could be possible to include edge visibility information in the tile content and produce the edges on the frontend; if so, it should be done in a web worker. 

FYI @DStradley has also talked about EDL (Eye-Dome Lighting) being able to be enhanced / customized to produce generic edges (not just point clouds) on the frontend with much more minimal overhead than currently is the case.

**Comment by pmconne** [comment]
Yes, those would not be real edges though (unsuitable for wireframe).

**Comment by markschlosseratbentley** [comment]
Need to create separate issues from findings.

**Comment by pmconne** [comment]
See linked issues for follow-up actions.
