### ISSUE TITLE
Use older disjoint timer if the newer one fails

### ISSUE THREAD

**Issue by DStradley** [iTwin/itwinjs-core#5031]
Firefox still only supports the WebGL EXT_disjoint_timer_query extension under WebGL2 (and not the WebGL EXT_disjoint_timer_query_webgl2 Extension).  (This can easily by verified by looking at extensions at https://webglreport.com/?v=2).

We need to fall back and try WebGL EXT_disjoint_timer_query when WebGL EXT_disjoint_timer_query_webgl2 is not available.  This fallback check was lost in [#4999](https://github.com/iTwin/itwinjs-core/pull/4999/).

Until this is fixed, this will affect our Firefox performance tests accuracy.

**Comment by pmconne** [comment]
> We need to fall back and try WebGL EXT_disjoint_timer_query when WebGL EXT_disjoint_timer_query_webgl2 is not available. This fallback check was lost in https://github.com/iTwin/itwinjs-core/pull/4999/.

@DStradley was it?

```
  public get disjointTimerQuery() {
    const ext = this._capabilities.queryExtensionObject<any>("EXT_disjoint_timer_query_webgl2");
    return ext ?? this._capabilities.queryExtensionObject<any>("EXT_disjoint_timer_query");
  }
```

**Comment by DStradley** [comment]
That was missed during the review, and not pointed out in the comment on this.

**Comment by pmconne** [comment]
Sorry - I thought your comment was suggesting I **should** remove the fallback, not that you thought I **had** removed it. Thanks for investigating.
