### ISSUE TITLE
Toast notifications are not displayed when passing a react node as briefMessage

### ISSUE THREAD

**Issue by Maxime-Brassard** [iTwin/itwinjs-core#5081]
**Describe the bug**
When passing a ReactNode as briefMessage to display a toast notification, the toast notification is not displayed.

**To Reproduce**

1. Create a ReactnotifyMessageDetails with a reactNode as parameter for the briefMessage:
**ex:** 
const msg = new ReactNotifyMessageDetails(OutputMessagePriority.Info, { reactNode });
2. Set display time and make sure the message type is toast:
**ex:**
msg.displayTime = BeDuration.fromSeconds(7.0);
msg.msgType = OutputMessageType.Toast;
3. Output the message:
**ex:**
MessageManager.outputMessage(msg);

**Expected behavior**
The toast notification should be displayed

**Desktop (please complete the applicable information):**

- OS: Windows
- Browser Chrome
- Version 109.0.5414.120
- iTwin.js Version 3.6.0

**Additional context**
Same problem if I try using MessageManager.displayMessage instead.
This behavior worked on previous versions

**Comment by raplemie** [comment]
The fix will be available in `@itwin/appui-react@3.6.1`.

**Comment by raplemie** [comment]
`@itwin/appui-react@3.6.1` was released on Feb 24th.
