### ISSUE TITLE
Batch reprojection requests

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#5097]
**Is your feature request related to a problem? Please describe.**
As described in https://github.com/iTwin/itwinjs-backlog/issues/641, when displaying reality models there can be many small, frequent requests to the backend to reproject tile centers. This appears to negatively impact performance.

**Describe the solution you'd like**
Batch requests without negatively affecting performance.

**Describe alternatives you've considered**
None really.

**Additional context**
For reality models, for each parent tile, `reprojectAndResolveChildren` makes one request to reproject the center of each child tile's volume. Many such requests are observed during a single traversal of the tile tree for tile selection, within one frame. It would be preferable to send at most one request per frame.

For map tiles, there's some pre-loading of reprojected points that are expected to be needed soon; when they are actually needed, they are expected to be extracted directly (and synchronously) from the GeoConverter's cache. This can still involve multiple requests per frame. It's possible that the pre-loading optimization may become obsolete after batching is implemented.

**Comment by MarcBedard8** [comment]
As a complemement of information, I've remarked that request get stalled for a long time. This might gives some explanation: https://stackoverflow.com/questions/29206067/understanding-chrome-network-log-stalled-state
