### ISSUE TITLE
Review `core-electron` and `core-mobile` dependency on `presentation-common`

### ISSUE THREAD

**Issue by grigasp** [iTwin/itwinjs-core#5129]
At the moment both `core-electron` and `core-mobile` have a dependency on `presentation-common`, because they automatically register the `PresentationRpcInterface`. I think that should be reconsidered, because:

- `PresentationRpcInterface` is not registered in case of web RPC, so there might be confusion why some hosts do that automatically others don't. And the web RPC can't automatically register `PresentationRpcInterface` because of circular dependencies between `core-backend` and `presentation-backend`.

- There may be applications that don't need a Presentation RPC, e.g. imodel-console. In that case we have those dependencies unnecessarily.

4.0 seems like a good time to make the change.

**Comment by calebmshafer** [comment]
I agree, we should be consistent with the way we handle this going forward and it should have minimal impact overall. Let's try to get this in this week for the 4.0 release.

We'll need to make sure to update the Mobile SDK (@tcobbs-bentley and @toddsouthenbentley) as well as the iTwin Viewer desktop app (@aruniverse @ben-polinsky).
