### ISSUE TITLE
Fit view tool makes iTwin viewer download thousands of background map tiles until it freezes/crashes

### ISSUE THREAD

**Issue by mdastous-bentley** [iTwin/itwinjs-core#5139]
This was first reported in the Design Review application and can be reproduced in [production deployment](https://connect-imodelweb.bentley.com/imodeljs/?projectId=75a13263-1157-4246-bbd0-49e7f76b0622&iModelId=77c9c016-a44f-4bd2-b6c6-1ee4af60b608&ChangeSetId=7ccde65edf7c85c661e140c5ad494e9a284f02ab) : 
![image](https://user-images.githubusercontent.com/8309609/221599757-543657c8-71a3-4d01-a592-6d71600c94f8.png)

After chose all models from the 3d models tab, you must click on the 'Fit view' tool.

iTwin.js version used: 3.5.5

**Comment by mdastous-bentley** [comment]
Following BIM was extracted [exton1.zip](https://github.com/iTwin/itwinjs-core/files/10841034/exton1.zip)

After opening it in display-test-app, we can see the 'ellipsoid' globe mode is causing the issue.  Switching to 'planar' globe mode, problem disappear. 

Further investigations shown that tile selection mechanism fails to compute a valid pixel size, as a result, a large amount level 20 tiles (last available LOD) are downloaded.

In `TileDrawArgs.getPixelSizeFromProjection()` world coordinates tile corners get transformed to what appear to be invalid view coordinates, such as: `-18065963.37771991, 54691207.63877826, -928203.68`

Call stack:
```
getPixelSizeFromProjection (TileDrawArgs.ts:157)
getPixelSize (TileDrawArgs.ts:125)
computeVisibilityFactor (RealityTile.ts:374)
selectRealityTiles (RealityTile.ts:290)
selectRealityChildren (RealityTile.ts:232)
selectRealityTiles (RealityTile.ts:319)
selectRealityTiles (RealityTileTree.ts:420)
draw (RealityTileTree.ts:221)
addToScene (MapTileTree.ts:999)
(anonymous) (TiledGraphicsProvider.ts:44)
forEachTileTreeRef (MapTiledGraphicsProvider.ts:39)
addToScene (TiledGraphicsProvider.ts:44)
createScene (Viewport.ts:2319)
renderFrame (Viewport.ts:2417)
renderLoop (ViewManager.ts:404)
```

**Comment by mdastous-bentley** [comment]
A second imodel ([exton1_fixed.zip](https://github.com/iTwin/itwinjs-core/files/10841144/exton1_fixed.zip)) was published using a slightly modified DGN file, and problem suddenly disappeared.

**Comment by mdastous-bentley** [comment]
@pmconne repro steps updated, can you reproduce now?

**Comment by pmconne** [comment]
> A second imodel ([exton1_fixed.zip](https://github.com/iTwin/itwinjs-core/files/10841144/exton1_fixed.zip)) was published using a slightly modified DGN file

Do you know, or can you find out, how specifically the DGN file was modified?

**Comment by mdastous-bentley** [comment]
> Do you know, or can you find out, how specifically the DGN file was modified? I see that the ecef location and project extents differ between the two iModels.

@pmconne Here are the details:
1.	I opened it in MicroStation (10.17.01.58) with no workspace.
2.	I fit the view. I noticed a polygon surrounding the area.
3.	I deleted the polygon.
4.	I key-in a “compress design”.
5.	Save
6.	Save Settings

**Comment by pmconne** [comment]
The project extents are pretty silly. My inclination is to not investigate further.
![image](https://user-images.githubusercontent.com/22944042/221631684-aa9930ec-5fd2-4984-88f6-35bd81acc192.png)

**Comment by mdastous-bentley** [comment]
So basically you're saying the Mstn connector has created an invalid iModel ?

**Comment by pmconne** [comment]
More likely, the user submitted to the connector a DGN with some junk floating out in the middle of the ocean and the connector didn't complain about it, instead expanding the project extents to encompass it.
Did the DGN file come from a user?

**Comment by pmconne** [comment]
A rogue reality mesh blew out the project extents.
Ideally something earlier in the pipeline would have identified the error and prevented it from manifesting as a display issue.
