### ISSUE TITLE
VirtualizedPropertyGrid minimizes down to one line when its height is changed

### ISSUE THREAD

**Issue by tcobbs-bentley** [iTwin/itwinjs-core#5156]
**Describe the bug**
After changing from using `PropertyGrid` to `VirtualizedPropertyGridWithDataProvider`, I discovered that every time the element containing the `VirtualizedPropertyGridWithDataProvider` changes height (thus passing a new value for the `height` prop), the grid minimizes down to only showing the top line. `ProperyGrid` did not do this when its panel had a height change.

My property grid does not specify orientation, but I tested setting that to Orientation.Horizontal, and it did not fix the problem. Additionally, when I specify a new width for the property grid, the problem does not occur.

**To Reproduce**

1. Include a `VirtualizedPropertyGridWithDataProvider` in your UI.
2. Select an element to display in the property grid.
3. Tap on the only visible line ("Selected Item(s)") to expand it.
4. Change the `height` prop being passed into the property grid.

**Expected behavior**
The property grid should resize to reflect the new height, but it should **not** minimize down to only showing the "Selected Item(s)" line.

**Screenshots**
Before height change:
![IMG_0301](https://user-images.githubusercontent.com/77415528/222202575-f7ccf9b6-1847-4d7a-9825-d96686aad7ed.PNG)

After height change:
![IMG_0302](https://user-images.githubusercontent.com/77415528/222202657-c3b9dc83-fa87-4204-9897-0992f8b729ed.PNG)

**Desktop (please complete the applicable information):**

- OS: iOS
- Browser: Safari WKWebView inside native app
- Version: 16.3.1
- iTwin.js Version: 3.6.1

**Additional context**
This happens inside a native iOS mobile app. I assume it will also happen in a browser-based desktop or mobile app, but I have not tested that. The app in question is the sample app for the iTwin Mobile SDK. I have not yet pushed the changes to that app to use `VirtualizedPropertyGridWithDataProvider`, but I will be doing so shortly. One that happens, my actual code will be [here](https://github.com/iTwin/mobile-samples/blob/main/cross-platform/react-app/src/frontend/BottomPanels/ElementPropertiesPanel.tsx).

**Comment by grigasp** [comment]
@tcobbs-bentley, have you tried to reproduce this in a sandbox?

**Comment by tcobbs-bentley** [comment]
No.

**Comment by tcobbs-bentley** [comment]
@grigasp I've never made a sandbox before, so I don't know what is needed to share them with others if they are not automatically shared. I created a sandbox here:

https://www.itwinjs.org/sandbox/TravisCobbs/Element%20Properties

Instructions for sandbox:

1. Resize the bottom panel to be taller (not necessary, but helpful).
2. Select an element.
3. Expand the property grid so it is visible.
4. Hit the "Press me" button.

**Comment by grigasp** [comment]
The sandbox recreates the data provider on each component rerender (e.g. when size changes), which in turn causes a complete rerender of the property grid, dropping any categories' state. Using `React.useMemo` to memoize the provider should solve the problem.

**Comment by tcobbs-bentley** [comment]
The sandbox I created created the data provider in a different location than the iTwin Mobile sample app, but adding useMemo to the mobile sample did indeed fix the problem. I apologize for the false alarm.
