### ISSUE TITLE
The link provided doesn't work.

### ISSUE THREAD

**Issue by meimeiho** [iTwin/itwinjs-core#5189]
Hi developer,

The link provided doesn't work at the moment. It shows 404 and 'The 'iTwin/itwinjs-core' repository doesn't contain the 'ui/appui-react/src/appui-react/ui-items-provider/UiItemsProvider.ts' path in 'release/3.5.x'. '

Cheers
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: UiItemsProvider---appui-react-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/reference/appui-react/uiprovider/uiitemsprovider/

**Comment by calebmshafer** [comment]
@ben-polinsky any idea what's going on? The link seems to be going to `release/3.5.x` instead of going to `release/3.6.x` where that path does exist.

**Comment by ben-polinsky** [comment]
@williamkbentley which flag is this?

**Comment by williamkbentley** [comment]
Its in LaunchDarkly - `edit-docs-base-url`.
