### ISSUE TITLE
ViewState.lookAt returns InvalidUpVector when camera is looking directly down

### ISSUE THREAD

**Issue by ImVeryLost** [iTwin/itwinjs-core#5255]
**Describe the bug**
When trying to setup the view to look straight down (the equivalent of `StardardViewId.Top`),  `ViewStatus.InvalidUpVector` is returned.
Looking at the `lookAt` implementation, its due to the `upVector` being the same as `targetPoint` to `eyePoint` vector.

(Side note - this scenario seems problematic not only for `lookAt` - e.g. in the `Camera Visualizer` sample, the camera plane fails to be constructed for the same scenario)

Scenario ilustrated using Camera Visualizer sample:
![image](https://user-images.githubusercontent.com/61872067/226592088-ba8b572d-185b-4029-9a2e-afafb3e4cd4b.png)

**To Reproduce**
Example of lookAt parameters used:
```
view3d.lookAt({
    eyePoint: [
      20.40488933620268,
      3.509489688064754,
      48.1222892966759
    ],
    targetPoint: [
      20.40488933620268,
      3.509489688064754,
      2.1124999999999687
    ],
    upVector: [
      0,
      0,
      1
    ],
    lensAngle: 90
  });
```
In the example above, the parameters were gathered after applying `StandardViewId.Top`: 
```
eyePoint = view.getEyePoint();
upVector = view.getUpVector(eyePoint);
lensAngle = view.getLensAngle();
targetPoint = view.getTargetPoint();
```

**Expected behavior**

ViewState is sucessfully updated.

**Additional context**
I’m not sure if I can safely assume that `upVector` is the same as `targetPoint` to `eyePoint` vector only in this specific scenario, and thus its safe to just set StandardViewId.Top.
Note that the same issue appears if the view matches `StandardViewId.Bottom`.

What is the proper way to setup a “looking down” or "looking up" view from `LookAtUsingLensAngle` args?

**Comment by pmconne** [comment]
`getUpVector` (undocumented) gives you the up vector in world space at a given position. Within the project extents, this is unit Z.

`LookAtArgs.upVector` (as documented) is the camera's up (y) vector in view space.
