### ISSUE TITLE
Implement frontend telemetry using OpenTelemetry

### ISSUE THREAD

**Issue by paulius-valiunas** [iTwin/itwinjs-core#5278]
Right now we have `IModelHostOptions.enableOpenTelemetry` / `Tracing` for backends and `TelemetryManager` / `TelemetryClient` for frontends. The latter ones have nothing to do with OpenTelemetry, so these concepts are often misunderstood and mixed up. We should streamline all our telemetry efforts and provide an OpenTelemetry-based solution for the frontend.

Since no implementations of `TelemetryClient` are known to me, we should start by gathering the requirements and expectations for frontend telemetry from application teams.

**Comment by ben-polinsky** [comment]
https://github.com/iTwin/itwinjs-core/issues/5722

**Comment by paulius-valiunas** [comment]
I guess if `TelemetryClient` is removed there is no real need for this. We could still look into implementing logging/tracing in the frontend but that would be an entirely new feature rather than a fix for an existing one.
