### ISSUE TITLE
Investigate Möller-Trumbore ray-triangle intersection speedup

### ISSUE THREAD

**Issue by dassaf4** [iTwin/itwinjs-core#5292]
Scalable Mesh team reports 37.5% savings using this algorithm (and inlining) to short-circuit solving the system equation in native code. Geomlibs should be able to realize some savings over the current implementations in:

* iTwin: `BarycentricTriangle.intersectRay3d`, `PolygonOps.intersectRay3d`
* imodel-native: `DPoint3dDVec3dDVec3d::TransverseIntersection`, `DTriangle3d::TransverseIntersection`, `bsiDRay3d_intersectTriangle`
* PowerPlatform: `DPlane3dByVectors::TransverseIntersection`, `bsiDRay3d_intersectTriangle`

**Comment by dassaf4** [comment]
https://github.com/iTwin/itwinjs-core/pull/5399
https://github.com/iTwin/imodel-native/pull/256
https://dev.azure.com/bentleycs/PowerPlatform/_git/PPBase/pullrequest/331375

**Comment by saeeedtorabi** [comment]
The new method is implemented, tested, and merged for all 3 repos.
