### ISSUE TITLE
Materials lost when transform a SnapshotDb to another by using core-transform

### ISSUE THREAD

**Issue by fatalstar** [iTwin/itwinjs-core#5307]
**Describe the bug**
I try to transform a SnapshotDb to another, but materials lost. 
And then, I try to transform it to an empty SnapshotDb，materials get lost and error. 

**To Reproduce**

1. Convert House_Model.dgn to a local house.bim file. And do same thing with testY1.dgn.
2. Build an iModelTransformer with core-transformer@3.4.4
3. Excute iModelTransformer.processAll( *house.bim*, *testY1.bim*, *no options*), 
4. When transform done, excute targetDb.saveChanges( )
5. Open the targetDb in view, and could see the materials lost.

**Expected behavior**
Materials exist and be correct.

**Screenshots**
The house.bim view :
![image](https://user-images.githubusercontent.com/38130258/228467363-3a2c096e-189b-404f-98be-8eec52698fcf.png)

The result.bim view: (materials get lost)
![image](https://user-images.githubusercontent.com/38130258/228467928-45e24888-3fa7-47ab-9a2d-3281af9e4eb2.png)

If transform to an empty db, and view: (roof material lost, wall and steps meterial error)
![image](https://user-images.githubusercontent.com/38130258/228468242-3d8850b4-8c40-4571-8222-5ba883c46167.png)

**Desktop (please complete the applicable information):**
- iTwin.js Version [3.4.4]

**Additional context**

**Comment by fatalstar** [comment]
> Did you try with the latest version (3.6)? @MichaelBelousov

I have tested core-transform@3.6.3 just now and materials still get lost.

**Comment by MichaelBelousov** [comment]
@fatalstar I'm sorry for missing this. The transformer has moved to [a separate repository](https://github.com/iTwin/imodel-transformer), so I will make an issue there and close this one if that's OK. Texture loss should have been fixed by #5059.

**Comment by fatalstar** [comment]
> @fatalstar I'm sorry for missing this. The transformer has moved to [a separate repository](https://github.com/iTwin/imodel-transformer), so I will make an issue there and close this one if that's OK. Texture loss should have been fixed by #5059.

Sure, thanks for that!
