### ISSUE TITLE
Add documentation for ECSqlReader

### ISSUE THREAD

**Issue by mattbjordan** [iTwin/itwinjs-core#5349]
Create documentation for [ECSqlReader](https://github.com/iTwin/itwinjs-core/blob/master/core/common/src/ECSqlReader.ts) and any other related functions **and** take it out of beta.

[ECSqlReader](https://github.com/iTwin/itwinjs-core/blob/master/core/common/src/ECSqlReader.ts) is currently marked as in beta and does not have proper documentation. The `createQueryReader` methods in [ECDb](https://github.com/iTwin/itwinjs-core/blob/7fe9d6941bcc4ffd386f5edbf3dcabb5e468b115/core/backend/src/ECDb.ts#L288), [IModelDb](https://github.com/iTwin/itwinjs-core/blob/7fe9d6941bcc4ffd386f5edbf3dcabb5e468b115/core/backend/src/IModelDb.ts#L496), and [IModelConnection](https://github.com/iTwin/itwinjs-core/blob/7fe9d6941bcc4ffd386f5edbf3dcabb5e468b115/core/frontend/src/IModelConnection.ts#L261) replaces the old `.query` methods and returns a ECSqlReader.

**Comment by ColinKerr** [comment]
Here is additional stuff to add to docs
Discussed in https://github.com/iTwin/itwinjs-core/discussions/4606

Originally posted by Adu2120 November 7, 2022
Can you please describe the indexOrName parameter of all bind function in QueryBinder?

Also please describe the respective index of the name.

**Comment by mattbjordan** [comment]
Will be making ECSqlReader public in a separate PR and step. Need to discuss if there is anything else to do first.
See #5569
