### ISSUE TITLE
Update @azure/storage-blob for xml2js CVE

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#5373]
[xml2js CVE](https://github.com/advisories/GHSA-776f-qx25-q3cc) affects current releases of @azure/storage-blob.
[@azure issue](https://github.com/Azure/azure-sdk-for-js/issues/25499)
Temporarily ignored in #5372. Revert that change once a patched release becomes available.

**Comment by aruniverse** [comment]
Closed; all current cve issues have been resolved as of https://github.com/iTwin/itwinjs-core/pull/5677
