### ISSUE TITLE
doc build fails to resolve the following doc tags

### ISSUE THREAD

**Issue by aruniverse** [iTwin/itwinjs-core#5403]
doc build fails to resolve the following doc tags
- $core-electron
- $core-mobile

_Originally posted by @aruniverse in https://github.com/iTwin/itwinjs-core/pull/5298#discussion_r1168898573_

**Comment by yashincontrol** [comment]
We have a quick fix for the invalid link errors in the bemetalsmith release/5.0 branch. Will merge that into master as soon as the other breaking changes are done.

**Comment by aruniverse** [comment]
no worries, just need to retroactively fix netversion.md before release

**Comment by yashincontrol** [comment]
Core is using bemetalsmith 5.0.2 now, so this issue should be fixed.
