### ISSUE TITLE
Adding ESRI feature geometries as world decorations give degenerated triangles asserts

### ISSUE THREAD

**Issue by mdastous-bentley** [iTwin/itwinjs-core#5467]
New development is being to display allow ESRI feature to selected.  To achieve this, the feature geometry is fetched from the ESRI backend and display as a decoration. 

Some geometry will gives asserts, and other will no be displayed at all on screen.

**Assert details:**
Message:
Programmer Error

Callstack:
assert (Assert.ts:46)
addTriangle (MeshBuilder.ts:246)
addFromPolyfaceVisitor (MeshBuilder.ts:122)
addFromPolyface (MeshBuilder.ts:91)
loadIndexedPolyface (MeshBuilderMap.ts:101)
loadPolyfacePrimitiveList (MeshBuilderMap.ts:83)
loadGeometry (MeshBuilderMap.ts:68)
createFromGeometries (MeshBuilderMap.ts:49)
toMeshBuilderMap (GeometryAccumulator.ts:164)
toMeshes (GeometryAccumulator.ts:171)
saveToGraphicList (GeometryAccumulator.ts:180)
finishGraphic (GeometryListBuilder.ts:175)
finish (GeometryListBuilder.ts:50)
renderGraphics (MapFeatureInfoDecorator.ts:206)
decorate (MapFeatureInfoDecorator.ts:214)
addFromDecorator (ViewContext.ts:187)
addDecorations (Viewport.ts:3322)
renderFrame (Viewport.ts:2490)

1. checkout the 'geo/MapFeatureInfo_hlite' branch.
2. Open 'philly_area_outline.bim' in dislay-test-app
3. Open the 'PhillyPolyF_assert1' saved view
4. Use the temporary 'drop' toolbar icon to enable the selection tool.
5. Click the highlighted polygon:
![image](https://user-images.githubusercontent.com/8309609/235507533-e5964011-8327-4e97-b726-f4fdfb451553.png)
6. An assert will appear.

Sometimes, the polygon get initially displayed, but zoom-in out, will trigger an assert:
1. Open 'philly_area_outline.bim' in dislay-test-app
2. Open the 'PhillyPolyF_assert2' saved view
3. Use the temporary 'drop' toolbar icon to enable the selection tool.
4. Click the highlighted polygon:
![image](https://user-images.githubusercontent.com/8309609/235508029-f670aade-d4ac-4d04-a827-aa873ac1c6a1.png)
5. Zoom out.
6. An assert will appear.

In some rare cases, no polygon is displayed:
1. checkout the 'geo/MapFeatureInfo_hlite' branch.
2. Open 'philly_area_outline.bim' in dislay-test-app
3. Open the 'PhillyPolyF_assert1' saved view
4. Use the temporary 'drop' toolbar icon to enable the selection tool.
5. Click the highlighted polygon:
![image](https://user-images.githubusercontent.com/8309609/235530522-7120cbd5-f087-413f-83fc-abf8d5996a34.png)
6. An assert will appear.

Dataset:
[philly_area_outline.zip](https://github.com/iTwin/itwinjs-core/files/11367251/philly_area_outline.zip)

**Comment by dassaf4** [comment]
When I looked at this issue last week, the below input caused `MeshBuilder.createTriangle` to return a degenerate `Triangle`.
```
position: {x: -8370467.98428443, y: 4859292.3676143885, z: 0}, sourceIndex: 0
position: {x: -8370467.93876954, y: 4859292.655171589, z: 0}, sourceIndex: 1
position: {x: -8370466.809313181, y: 4859292.809271909, z: 0}, sourceIndex: 2
```
And immediately thereafter, this degenerate `Triangle` trips the assert in `MeshBuilder.addTriangle`.

**Comment by mdastous-bentley** [comment]
Updated description

**Comment by mdastous-bentley** [comment]
I managed to work around most issues by lowering the geometries resolution output by the ESRI server (i.e maxAllowedOffset). 

I still get inconsistent decoration display for some polygons though (Step to reproduce #2).  Depending on the view pixel size, the decoration will sometime appear, and sometime not (without throwing any assert)

**Comment by mdastous-bentley** [comment]
@markschlosseratbentley this is blocking PR [5327](https://github.com/iTwin/itwinjs-core/pull/5327), does anyone can help understanding why some ESRI geometries cannot be displayed as decorations?

**Comment by DStradley** [comment]
@mdastous-bentley the reason for the degenerate triangle assert is for triangles that are too small to be visible on the current view (and therefore waste bandwidth all through the system, including gl).  The vertices that @dassaf4 listed above are of that category (I can tell just by looking at the numbers in this case, because they are the same to 7 digits and WebGL is single precision).  So it makes sense to me that lowering the resolution output would probably get rid of the too tiny triangles, and sounds like it did. (I gather you no longer see any asserts?)

What do you mean by "Step to reproduce #2", do you mean using saved view PhillyPolyF_assert2?
What do you see here, are the decorations that sometimes appear and sometimes not tiny in size (about a pixel)?

**Comment by mdastous-bentley** [comment]
> What do you mean by "Step to reproduce #2", do you mean using saved view PhillyPolyF_assert2? What do you see here, are the decorations that sometimes appear and sometimes not tiny in size (about a pixel)?

@DStradley  For some reasons, decorations wont display in the view at all (I dont get any error or assert).. interestedly zoom-in one step with the mouse wheel will make the decoration appears.

If you need to reproduce, let me know.
