### ISSUE TITLE
PolyfaceQuery.sweepLinestringToFacetsXYReturnChains unexpected output

### ISSUE THREAD

**Issue by dassaf4** [iTwin/itwinjs-core#5507]
User states this method produces two unexpected spikes in z-coordinates on this input, consisting of a linestring and two meshes: [linestring_drape.txt](https://github.com/iTwin/itwinjs-core/files/11456522/linestring_drape.txt)

Output consists of two linestrings below. User states entries 23 and 26 in the first linestring are unexpected:
{
    "0": -8365354.40647523,
    "1": 4852793.72391395,
    "2": -31.755184061248592,
    "3": -8365345.452249724,
    "4": 4852797.780250252,
    "5": -31.838332371431417,
    "6": -8365321.29976544,
    "7": 4852808.72152024,
    "8": -31.887235312354765,
    "9": -8365311.694367033,
    "10": 4852812.264060729,
    "11": -31.904040163776045,
    "12": -8365279.99985307,
    "13": 4852823.95322699,
    "14": -31.710407942126093,
    "15": -8365274.02435133,
    "16": 4852827.20992831,
    "17": -31.67226221355585,
    "18": -8365268.375529689,
    "19": 4852830.2885980345,
    "20": -31.636201889653567,
    "21": -8365268.383727771,
    "22": 4852830.284129989,
    "23": -41.96804154027708,
    "24": -8365268.384860523,
    "25": 4852830.283512628,
    "26": -43.395652929644115,
}
{
    "0": -8365268.375529689,
    "1": 4852830.2885980345,
    "2": -31.636036452102932,
    "3": -8365250.50004448,
    "4": 4852840.03093345,
    "5": -31.64511431897961,
    "6": -8365224.37153723,
    "7": 4852862.03204164,
    "8": -31.646300954448527,
    "9": -8365203.30013189,
    "10": 4852890.80255174,
    "11": -31.63008942901338,
    "12": -8365188.12882827,
    "13": 4852916.18856048,
    "14": -31.611144526394117,
    "15": -8365178.85732679,
    "16": 4852947.49787083,
    "17": -31.574975729665287,
    "18": -8365118.17202385,
    "19": 4853297.82288451,
    "20": -31.111879695897475,
}

**Comment by EarlinLutz** [comment]
Note that each mesh has a small apron going all the way around, including one where they meet.

The zinger is going down one of the aprons, so I think it is basically correct.   

(BTW, the test data provide has a different (longer) path and is shifted away from the meshes.  That's probably not important -- I see the zinger with the shorter drape line in the test file.)

**Comment by EarlinLutz** [comment]
On close examination of the shared vertical "apron" facets where the two meshes abut:
* one of the meshes has a purely vertical apron with identical Y coordinates
* the other has a slight tilt --perhaps 12 mm  difference between its top and bottom Y coordinates

Hence it makes sense that if pure vertical drape lines are omitted, the "zingers" appear only on the not-quite-vertical facets.



These are the coordinates on the shared
First mesh:
   [-8364045.3830771279,4852558.4155464275,-30.901505957975687],
   [-8364656.8793034079,4852558.4155464275,-30.923498994492491],
   [-8364656.8793034079,4852558.4033827782,-42.682958787273805],
   [-8364045.3924079612,4852558.4033827782,-42.660965750756993]],

Second mesh:
   [-8364045.3830771279,4852558.4155464275,-30.901582613181247],
   [-8364656.8793034079,4852558.4155464275,-30.923439892957671],
   [-8364656.8793034079,4852558.4155464275,-42.682940273449134],
   [-8364045.3924079612,4852558.4155464275,-42.661082993672707]],

**Comment by EarlinLutz** [comment]
This is the tiny gap between lower points on two aprons that both appear from a distance to be vertical

![Image](https://github.com/iTwin/itwinjs-core/assets/69321059/525dce84-6838-45ec-852c-547c14ee8f8f)

**Comment by dassaf4** [comment]
PR: https://github.com/iTwin/itwinjs-core/pull/5684
