### ISSUE TITLE
CurvePrimitive.appendPlaneIntersectionPoints returns detail fractions outside [0,1] for an Arc3d

### ISSUE THREAD

**Issue by dassaf4** [iTwin/itwinjs-core#5508]
On the below inputs, this method outputs two `CurveLocationDetail` objects with fractions 450 (unexpected) and 0.8 (OK).

```
const xValue = 3833.1784065712636;
const plane = Plane3dByOriginAndUnitNormal.create(new Point3d(xValue, 0.0, 0.0), Vector3d.unitX());

```
```
{
  "arc": {
    "center": [406.4764924993565, 30034.313000056925, 0],
    "vectorX": [30000, 0, 0],
    "vectorY": [0, 30000, 0],
    "sweepStartEnd": [270.00000000052296, 270.47554405008026]
  }
}
```

**Comment by EarlinLutz** [comment]
The definition of appendPlaneIntersectionPoints in CurvePrimitive.ts says
                   "Derived classes are free to implement extended intersections (e.g. arc)" in CurvePrimitive.ts:
The whole comment is
  /**
   * Compute intersections of the curve with a plane.
   * * The intersections are appended to the result array.
   * * The base class implementation emits strokes to an AppendPlaneIntersectionStrokeHandler object, which uses a
   * Newton iteration to get high-accuracy intersection points within strokes.
   * * Derived classes should override this default implementation if there are easy analytic solutions.
   * * **Derived classes are free to implement extended intersections (e.g. arc!!!)**
   * @param plane The plane to be intersected.
   * @param result Array to receive intersections
   * @returns Return the number of CurveLocationDetail's added to the result array.
   */

As a secondary note, a test program here is showing intersection fractions as 364.721556998938 and 364.721556998938.
Trying a different xValue of 606.4764924993589 gets the parameters to 0.8032372452793054 and 377.7105937374266.
The various coordinates have been copied around a few times and I'm assuming some values got lost, but this is not a problem.

For both xValue cases, the returned intersections are indeed accurately on the intersection of the arc and the plane.

**Comment by EarlinLutz** [comment]
![Image](https://github.com/iTwin/itwinjs-core/assets/69321059/586fb456-4659-4b58-ac4f-f46c17625dcc)



![Image](https://github.com/iTwin/itwinjs-core/assets/69321059/c442a6c8-d20d-4205-810f-4d88339a4287)

**Comment by dassaf4** [comment]
Closing as WAD.
