### ISSUE TITLE
Support snapping to elements inside orthogonal view attachments

### ISSUE THREAD

**Issue by a-gagnon** [iTwin/itwinjs-core#5585]
**Describe the bug**
AccuSnap seems to work fine against drawing models and 3d views, but we get unexpected jumps when targeting a sheet model.

**To Reproduce**
1. Open [this sandbox](https://www.itwinjs.org/sandboxes/gagnon-a/snapping-to-sheet-models)
2. Once it's up and running, start the `Test measure tool` and try to snap in a drawing view. It should work as expected.
3. Use the `2D View Selector` in the bottom drawer and select a sheet view and move the mouse over some of those elements. Notice the measurement line jumps unexpectedly, and that snapping sprites are nowhere to be seen. 

**Expected behavior**
I would expect AccuSnap to work properly.

**Desktop:**
- OS: Windows 10
- Browser: Chrome
- Version: 113.0.5672.127
- iTwin.js: 3.7.6 (version of the sandbox)

**Comment by Maxime-Brassard** [comment]
Have you tried on a sheet or on a drawing? It behaves well with drawings and is buggy specifically on sheets.

**Comment by pmconne** [comment]
I tried both a sheet and a drawing.

**Comment by Maxime-Brassard** [comment]
Ok, I'll get you a screenshot of the problem.

**Comment by Maxime-Brassard** [comment]
![BugSnap](https://github.com/iTwin/itwinjs-core/assets/125395992/df59adc5-e1e7-448e-85ab-3e8efa575049)

**Comment by pmconne** [comment]
Sprite is visible before your first click. Not sure how it's supposed to behave when you click on nothing as  your first data point. @bbastings should be able to help.

**Comment by Maxime-Brassard** [comment]
It sometimes snaps on the overlay stuff like the circles and the triangles but never on the geometry underneath. 
Might be a hint to where the problem could be located.

**Comment by pmconne** [comment]
Right, the drawing is being displayed onto the sheet via a view attachment. The snapping logic on the backend is unaware of this so it's only able to snap to geometry in the sheet itself.
As I recall, this did work in our old C++ codebase (e.g., in "Gist"), because there was no split between backend and frontend. Now, snapping happens on the backend and we have to pass what information we think it might need from the frontend to do the snapping. In this case we are not providing enough information.

**Comment by Maxime-Brassard** [comment]
And is this information that you might provide at some point or I should find an alternative?

**Comment by Maxime-Brassard** [comment]
The snapping does not work even if we start inside the drawing attachment, I can do another gif for you if you'd like to see it in action. The problem really is that not only we cannot snap in sheets, but also that the snap goes very far when it does trigger.
A real use case, in civil, would be of the user using a measurement tool to verify the width of something like a bridge or a road in a 2d sheet that they opened in the 2d-sheet-viewer. It could also be to use the area measure tool to verify the area of a specific element in that sheet. 
Unless we can snap to linears and borders like we usually can outside sheets, it is going to be very hard for them to get accurate measurements without zooming in a lot.
As for the urgency, I would not say it is critical but we are currently developing tools that will end up depending on this.
Let me know if you need any more details, I'll be happy to provide them.

**Comment by pmconne** [comment]
Thanks. I am curious why an engineer who requires high-precision measurements would attempt to perform those measurements inside a sheet vs in the drawing itself. Can you elaborate?

Do your workflows involve measuring the distance between a thing on the sheet (e.g., an annotation) and a thing inside a drawing (e.g., a bridge)? In what coordinate system (units) would  the user expect the distance to be reported - that of the sheet (paper space) or of the drawing?

When measuring between two elements inside the drawing attachment, in what coordinate system would the user expect the distance to be reported?

**Comment by simnorm** [comment]
> > We have already made something that takes care of transforming the coordinates from the sheets into world coordinates for the purpose of the value that gets displayed in the measurement tooltip and in the widget.
> 
> Please link to this code.

https://github.com/iTwin/viewer-components-react/pull/524/commits
