### ISSUE TITLE
ViewCreator3D should fit view

### ISSUE THREAD

**Issue by DanishMehmood-bit** [iTwin/itwinjs-core#5619]
I'm creating a default view through ViewCreator3D like this
![image](https://github.com/iTwin/itwinjs-core/assets/64415995/5e2c9591-a618-488b-afe0-56055a53af35)

now the problem is by default the iModel is not zoomed in, it is always zoomed out, I tried passing different values in VsAspects but none worked. This is how view looks
![image](https://github.com/iTwin/itwinjs-core/assets/64415995/6d7c56b5-8a7e-4388-a8f2-db7b73a4aa73)

Currently I'm using a hacky way which I've seen many teams in Bentley doing is to use FitViewTool when all tiles are loaded, this is how I'm achieving the desired functionality
![image](https://github.com/iTwin/itwinjs-core/assets/64415995/7b4e0f3e-1426-4854-8823-fed4b3f0ab8e)

This works perfectly fine but I think this should be the job of ViewCreator3D to fit the view instead of us doing it.

If you are wondering how I'm using the viewport then I'm creating a frontstage and passing in my view like this
![image](https://github.com/iTwin/itwinjs-core/assets/64415995/f82175c3-f293-4270-97f6-12bb27745405)

**Comment by pmconne** [comment]
As [discussed here](https://github.com/iTwin/studio/pull/588#discussion_r1224230105), `ViewCreator3d` does appear to try to fit to the extents of the models.
It already knows  their extents, so waiting for tile trees to load should not be necessary.

**Comment by pmconne** [comment]
> extents based zoom

ViewCreator3d has a list of **models**. Each model has an extents that is equal to the extents of its corresponding tile tree. Therefore there is no distinctions between "tile-tree based zoom" and "extents-based zoom", except one can be computed synchronously with information already available to the `ViewCreator3d` while the other requires hacky code to asynchronously wait for the tile trees to load.

**Comment by pmconne** [comment]
@DanishMehmood-bit please provide the code you used when attempting to pass an aspect ratio to `ViewCreator3d`.
Your [current code](https://github.com/iTwin/studio/blob/47cf82179ae8ff811b7ae8d71f8a1cb0cc28ee3c/packages/apps/itwin-studio-visualizer/frontend/frontstages/Visualizer.tsx#L28) makes no such attempt.
