### ISSUE TITLE
Migrate from Puppeteer to Playwright

### ISSUE THREAD

**Issue by aruniverse** [iTwin/itwinjs-core#5679]
We are using an outdated version of Puppeteer and the library has fallen behind newer chrome test drivers like Playwright.
We have already started updating to Playwright in many of our other packages.

- Investigate switching to Playwright. 
  - This might affect Certa
- Update tests as needed

**Comment by tm-zub** [comment]
@anmolshres98 , did we completed what was required from this issue?

**Comment by anmolshres98** [comment]
> @anmolshres98 , did we completed what was required from this issue?

yup, should be completed

**Comment by tm-zub** [comment]
Thanks @anmolshres98, marking this as done
