### ISSUE TITLE
Unable to download briefcase using Node 18 (Works in Node 16)

### ISSUE THREAD

**Issue by beolson** [iTwin/itwinjs-core#5741]
**Describe the bug**
I can download a briefcase when using Node 16.20.0, but the exact same code will not work when running Node 18.16.0.  
I don't get any errors, it just hangs and does not return from the BriefcaseManager.downloadBriefcase function - 

**To Reproduce**
My implementation is here: [src/ModelExtract/BriefcaseAccessor.ts](https://github.com/beolson/Things/blob/d1a3e9bf28ae6eb31926d53df4f3eaf4969f4674/itwins_extract/src/ModelExtract/BriefcaseAccessor.ts)

**Expected behavior**
Expect it to behave the same running under Node 18.16 as when running under Node 16.20

- NODEJS v18.16.0
- Ubuntu 22.04.1 (WSL)
- I am using the following libraries/versions - 
  - "@bentley/backend-itwin-client" : "2.19.53",
  - "@bentley/itwin-client": "2.19.53",
  - "@bentley/imodeljs-backend" : "2.19.53",
  - "@bentley/imodelhub-client": "2.19.53",
  - "@bentley/imodeljs-common": "2.19.53"

**Comment by pmconne** [comment]
Please consult our [support matrix](https://www.itwinjs.org/learning/supportedplatforms/#supported-nodejs-versions).
2.19.x is quite old (in fact, it's at [end of life](https://www.itwinjs.org/learning/api-support-policies/#version-support-status) and does not officially support versions of Node later than 14.
Node 18 is supported by iTwin.js 3.5 and later.

**Comment by beolson** [comment]
This got me pointed in the right direction.  

I got pointed in the wrong direction originally by this document - https://www.itwinjs.org/learning/tutorials/develop-agent/.  It points to this [repository](https://github.com/iTwin/agent-starter) that uses the old packages.
