### ISSUE TITLE
Promote TentativeOrAccuSnap

### ISSUE THREAD

**Issue by bsy-nicholasw** [iTwin/itwinjs-core#5773]
@bbastings The [MeasurePerpendicularTool](https://github.com/iTwin/viewer-components-react/blob/master/packages/itwin/measure-tools/src/tools/MeasurePerpendicularTool.ts) from measure-tools-react uses the `TentativeOrAccuSnap` API, which is marked internal.

Promote this or should the tool use something else?

**Comment by bbastings** [comment]
> @bbastings The [MeasurePerpendicularTool](https://github.com/iTwin/viewer-components-react/blob/master/packages/itwin/measure-tools/src/tools/MeasurePerpendicularTool.ts) from measure-tools-react uses the `TentativeOrAccuSnap` API, which is marked internal.
> 
> Promote this or should the tool use something else?

You can promote this to public, it's just a convenient wrapper for public AccuSnap and TentativePoint methods.
