### ISSUE TITLE
CurveCurve.closeApproachProjectedXYPairs does not work with Path/CurveChain

### ISSUE THREAD

**Issue by a-gagnon** [iTwin/itwinjs-core#5781]
**Is your feature request related to a problem? Please describe.**
I'm trying to get approaches between a closed line string (XY footprint of an element's bounding box) and a `Path`, and the implementation of the `CurveCurve.closeApproachProjectedXYPairs` does not support it.
Under the hood, the class `CurveCurveCloseApproachXY` extends `NullGeometryHandler` which might be part of the problem.

**Describe the solution you'd like**
I think if the class extended `RecurseToCurvesGeometryHandler` instead, it would properly dispatch the child curve primitives to the algorithm and everything would work. (There might be caveats that I am not aware of!)

**Describe alternatives you've considered**
As a workaround, I'm passing each child primitives individually and collecting results, but I would rather have the CurveCurve API take care of that, especially since its signature is of type `AnyGeometryQuery`.

Thanks!
Alex

**Comment by saeeedtorabi** [comment]
We merged this
https://github.com/iTwin/itwinjs-core/pull/5883

Now curve chain (path and loop) is supported by _CurveCurve.closeApproachProjectedXYPairs_

We also created a new API _CurveCurve.closestApproachProjectedXYPair_ to return the closest approach pair (only 1 pair is returned using this function).

Also bunch of improvements and bug fixes is done. We are working to make more improvements.

**Comment by saeeedtorabi** [comment]
Remaining work for this issue:

1- improve CPU/memory using techniques such as test the range around curves or return as soon as we found an intersection for an arc).

2- Study and if possible improve string-string, arc-arc, and arc-string.

3- Improvement and tests for path and loop.

4- Not sure if I need to test but test regions and bag of curves.
