### ISSUE TITLE
downloadBriefcase requires "imodels:modify" scope

### ISSUE THREAD

**Issue by beolson** [iTwin/itwinjs-core#5836]
**Describe the bug**
I am trying to download a Briefcase, and I am trying to use the least permissive scope to do so.  I found [documentation ](https://www.itwinjs.org/learning/imodelhub/permissions/#read-imodel) that suggests the only permission needed is "Read IModel" - but it only works when I add imodels:modify to my scopes.  

**To Reproduce**

1 - acquire an accessToken

```
  const oidcClient = new ServiceAuthorizationClient({
    clientId: clientId,
    clientSecret: clientSecret,
    scope: "itwins:read projects:read imodels:read insights:read",
  });

  const token = await oidcClient.getAccessToken();
```

2 - use token to download briefcase.  

```
const bc = await BriefcaseManager.downloadBriefcase({
  iTwinId: this.props.projectId,
  iModelId: this.props.iModelId,
  accessToken: token,
  //  asOf: IModelVersion.latest(),
  fileName: this.props.briefcaseFile,
});
```

3 - this fails for me.  But will work if I add the "imodels:modify" scope in step 1.  

**Expected behavior**
Should be able to call the BriefcaseManager.downloadBriefcase method using a token with the "imodels:read" scope.

**Comment by aruniverse** [comment]
The documentation you are referring to is talking about [RBAC](https://en.wikipedia.org/wiki/Role-based_access_control) not [OIDC Scopes](https://auth0.com/docs/get-started/apis/scopes/openid-connect-scopes). 

Looks like [BriefcaseManager.downloadBriefcase](https://github.com/iTwin/itwinjs-core/blob/df0dc354e1/core/backend/src/BriefcaseManager.ts#L206) attempts to download the briefcase in [read/write mode](https://github.com/iTwin/itwinjs-core/blob/df0dc354e1/core/backend/src/BriefcaseManager.ts#L239) which might explain why you need the `imodels:modify` scope

**Comment by beolson** [comment]
I assume that under the covers ITwinsJS is calling this: https://developer.bentley.com/apis/imodels-v2/operations/acquire-imodel-briefcase/ - and this does state that it requires the imodels:modify scope.  

Is there a way to get a briefcase without a modify scope?  I only intend to open it as a SnapshotDb - and would prefer my application not request a token with a modify scope

**Comment by austeja-bentley** [comment]
hello @beolson, [BriefcaseManager.downloadBriefcase](https://github.com/iTwin/itwinjs-core/blob/8b15602ef9d534a5931574284de462f9cff9b234/core/backend/src/BriefcaseManager.ts#L191C7-L191C7) documentation mentions that read-only Briefcases have an id equal to a special value ([which is equal to 0](https://github.com/iTwin/itwinjs-core/blob/8b15602ef9d534a5931574284de462f9cff9b234/core/common/src/BriefcaseTypes.ts#L48)). Looking at the code it looks like if you supply that special value to the function [it should not attempt to acquire a new Briefcase](https://github.com/iTwin/itwinjs-core/blob/8b15602ef9d534a5931574284de462f9cff9b234/core/backend/src/BriefcaseManager.ts#L206C14-L206C14) so the `imodels:modify` scope should not be needed. [This test](https://github.com/iTwin/itwinjs-core/blob/8b15602ef9d534a5931574284de462f9cff9b234/full-stack-tests/backend/src/integration/BriefcaseManager.test.ts#L126C15-L126C15) downloads a Briefcase with `briefcaseId: BriefcaseIdValue.Unassigned`.
