### ISSUE TITLE
RenderGraphics only render when drawn as a GraphicType.Scene

### ISSUE THREAD

**Issue by Rock2000** [iTwin/itwinjs-core#5876]
**Describe the bug**
When taking geometry returned from the backend that we want to show dynamically on the frontend, we create a RenderGraphic from it and then in our decorate method call 
   context.addDecoration(GraphicType.WorldOverlay, this._dynamicParkingLotGraphic );

We want to use overlay because this is for a manipulator and we want to ensure they see the dynamic results above anything else. But neither WorldOverlay or WorldDecoration draws the graphic. Only if I use GraphicType.Scene do I see my graphics drawn.

**To Reproduce**
For the render graphic, we first generate the geometryStream on the backend. Then we return to the frontend this:
 
      const requestProps: DynamicGraphicsRequest2dProps = {
        type: "2d",
        id: "Booster:ParkingLotDynamic",
        categoryId: props.category,
        geometry: { format: "json", data: geomStream },
        placement: { origin: { x: 0, y: 0 }, angle: 0},
        toleranceLog10,
      };
 
      return iModel.generateElementGraphics(requestProps);
 
On the frontend we take that received drawingGraphic  and create the render graphic
  const renderGraphic = await readElementGraphics(drawingGraphic, this.iModel, Id64.invalid, false);
  this._dynamicParkingLotGraphic = IModelApp.renderSystem.createGraphicOwner(renderGraphic);
 
and then in decorate() we do this
  context.addDecoration(GraphicType.WorldOverlay, this._dynamicParkingLotGraphic);
 

**Expected behavior**
The graphic should be drawn using WorldOverlay, and should be on top of any other graphics

**Desktop (please complete the applicable information):**

- OS: Win10
- iTwin Studio
- Version 20203.08.07-2
- iTwin.js Version 4.1.0-dev.62

**Comment by pmconne** [comment]
It's something to do with the symbology overrides. Scene graphics use the symbology overrides (including which categories are visible) that are applied to the rest of the elements in the view.
Decorations use an empty symbology overrides (see `Target.decorationsState` created via `BranchState.createForDecorations`).
Features that have an invalid subcategory Id always draw, but your graphics contain valid subcategory Ids. Since no subcategories are considered visible while drawing the decorations, all your geometry gets hidden.

**Comment by pmconne** [comment]
Please describe how you expect symbology overrides to apply to 1) the graphics for the original persistent element and 2) the temporary decoration graphics representing that element during dynamics - hiding/unhiding based on subcategory, class, etc; overriding colors, transparency, line weight/pattern, etc.

If you just want the decoration to draw using the same symbology as defined in the iModel, ignoring any overrides applied to the persistent elements in the view, then that's an easy fix: we can make `BranchState.createForDecorations` set `ignoreSubCategory=true` on the `FeatureSymbology.Overrides`. Having it hide everything that has a valid subcategory isn't very useful anyway.
But, the element might contain geometry on different subcategories, and the view might have some of those turned off, so I'm not sure you want dynamics to display geometry from all subcategories.

**Comment by Rock2000** [comment]
I would think overrides would apply verbatim to the persisted element. As for the dynamics, you are far ahead of us. I have not heard of any cases where we need to override a specific element yet. I know we want to be able to change the symbology of a 'level' (I guess that is now a subcategory?) but that doesn't sound like it would use an override. I'd be OK with just using the persisted symbology. Is there a way to not assign the subcategory to this geometry? If so, then in cases where we need to 'override' we can just create whatever geometry/symbology we need manually and have no subcategory.
