### ISSUE TITLE
unable to snap bounding box

### ISSUE THREAD

**Issue by abhijitpatil181171** [iTwin/itwinjs-core#5896]
i have created bounding box and gltf graphic . i also have enable the snap but when i hover my cursor on both gltf as well as bounding box i am unable to snap points out of them .any suggestion to enable snap on them
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: AccuSnap---core-frontend-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/reference/core-frontend/locatingelements/accusnap/

**Comment by pmconne** [comment]
You need to make a pickable graphic and tell AccuSnap what its snappable geometry looks like.
https://www.itwinjs.org/reference/core-frontend/views/decorator/getdecorationgeometry/
If problems persist, show your code.

**Comment by abhijitpatil181171** [comment]
thanks
*Abhijit Patil | Member of Technical Staff*
*Centre for Computational Technologies - CCTech*
Office 403 | Pushpak Business Hub | Wakad | Pune | 411057 | India
Mob : +91- 9158377653  | Ph: +91 7447477868 | www.cctech.co.in
*CCTech – "Transforming human life by democratization of technology"*
