### ISSUE TITLE
Issues with the clearOverriddenElements method (not clearing all the element overrides)

### ISSUE THREAD

**Issue by pratiknesarkar99** [iTwin/itwinjs-core#5969]
https://github.com/iTwin/itwinjs-core/blob/2d6ddd4f695dd04a6fecbe22b1342566dcd4b63a/core/frontend/src/EmphasizeElements.ts#L274

After initial investigation - the "**clearOverriddenElements**" method from the _"@itwin/core-frontend"_ package is not working as expected when it is passed ids. In normal cases - this method is behaving properly - but in case of the last node in the selected visualization this method fails to perform the intended functionality. Instead, it completely skips that last node and any sub-nodes inside those nodes. 

After some investigation - there is another method called "hideElements" in the same package (although this does not serve our purpose) but when same set of ids are passed to that method, it is able to perform the intended action on **all the passed ids** 
without skipping any. This implies that the **ids being passed are correct**, but the function they are being passed to is not behaving correctly producing this bug. 

Hence, I insist that itwin/core-frontend package team look into the above-mentioned function.

**Comment by pmconne** [comment]
> Hence, I insist that itwin/core-frontend package team look into the above-mentioned function.

Well, if you insist... :) But we're going to need repro steps.

**Comment by pratiknesarkar99** [comment]
HI Paul, 

Here is the snippet that you requested. The mentioned method tries to emphasize or clear a given set of overridden ecIds.
_Note: The behaviour of the clearOverriddenElements method remains unchanged with/without ecIds being provided to the method_

For the below implementation, these are the inputs that the method gets during runtime when clicked on the hideAll action button:
queryNodes =  [
    {
        "id": "-90.0",
        "label": "-90.0",
        "color": "#6AB9EC",
        "subItems": [
            {
                "id": "0x40000000036",
                "color": "#6AB9EC",
                "label": "50-EX-101-B",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            },
            {
                "id": "0x40000000038",
                "color": "#6AB9EC",
                "label": "50-EX-101-C",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            },
            {
                "id": "0x4000000003e",
                "color": "#6AB9EC",
                "label": "50-EX-101-D",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            },
            {
                "id": "0x40000000044",
                "color": "#6AB9EC",
                "label": "50-EX-101-E",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            },
            {
                "id": "0x40000000057",
                "color": "#6AB9EC",
                "label": "50-EX-101-A",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            },
            {
                "id": "0x40000000086",
                "color": "#6AB9EC",
                "label": "50-VH-101",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            },
            {
                "id": "0x40000000066",
                "color": "#6AB9EC",
                "label": "50-EX-102",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            },
            {
                "id": "0x40000000073",
                "color": "#6AB9EC",
                "label": "50-TW-102",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            }
        ],
        "isVisible": false
    },
    {
        "id": "0.0",
        "label": "0.0",
        "color": "#B1C854",
        "subItems": [
            {
                "id": "0x40000000032",
                "color": "#B1C854",
                "label": "50-E-104-B",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            },
            {
                "id": "0x40000000034",
                "color": "#B1C854",
                "label": "50-E-104-A",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            }
        ],
        "isVisible": false
    },
    {
        "id": "90.0",
        "label": "90.0",
        "color": "#F7706C",
        "subItems": [
            {
                "id": "0x4000000054a",
                "color": "#F7706C",
                "label": "50-P-104-A",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            },
            {
                "id": "0x4000000054c",
                "color": "#F7706C",
                "label": "50-P-104-B",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            },
            {
                "id": "0x40000000551",
                "color": "#F7706C",
                "label": "50-P-101-A",
                "subItems": [],
                "isVisible": false,
                "isDisabled": false
            }
        ],
        "isVisible": false
    }
],
emphasize = true,
toolbarAction="HideAll"

**Code snippet**

`export const onToolbarActionButtonClick = async (
  queryNodes: DataVizTreeNodeItem[],
  emphasize: boolean,
  toolbarAction: ToolbarActions
) => {
  const isolateFeatureApp = FeatureAppearance.fromTransparency(1);
  const emphasizeFeatureApp = FeatureAppearance.fromJSON({
    // Default de-emphasize using grey & mostly treansparent coloring
    rgb: new RgbColor(0xe4, 0xe4, 0xe4),
    transparency: 0.8,
    nonLocatable: true
  });
  if (!IModelApp?.viewManager?.selectedView) {
    return;
  }
  const vp = IModelApp.viewManager.selectedView;
  vp.isFadeOutActive = emphasize;
  if (emphasize) {
    EmphasizeElements.getOrCreate(vp).defaultAppearance = emphasizeFeatureApp;
  } else {
    EmphasizeElements.getOrCreate(vp).defaultAppearance = isolateFeatureApp;
  }
  let isFirst = true;

  const emph = EmphasizeElements.getOrCreate(vp);
  emph.wantEmphasis = emphasize;
  emph.clearOverriddenElements(vp);

  switch (toolbarAction) {
    case ToolbarActions.ShowAll:
    case ToolbarActions.ShowHideNodeElement:
    case ToolbarActions.EmphasizeIsolate: {
      queryNodes.map((x) => {
        const ecIds = x.subItems.filter((p) => p.isVisible && p.id !== "null").map((q) => q.id);
        emph.overrideElements(ecIds, vp, ColorDef.create(x.color), undefined, isFirst);
        if (emphasize) {
          emph.emphasizeElements(ecIds, vp);
        }
      });
      isFirst = false;
      break;
    }
    case ToolbarActions.InvertAll: {
      queryNodes.map((x) => {
        const ecIds = x.subItems.filter((p) => p.isVisible && p.id !== "null").map((q) => q.id);
        if (ecIds.length > 0) {
          emph.overrideElements(ecIds, vp, ColorDef.create(x.color), undefined, isFirst);
        } else {
          if (!emphasize) {
            emph.overrideElements(["0"], vp, ColorDef.black, undefined, isFirst);
          }
        }
        if (emphasize) {
          emph.emphasizeElements(ecIds, vp);
        }
      });
      isFirst = false;
      break;
    }
    case ToolbarActions.HideAll: {
      queryNodes.map((x) => {
        const ecIds = x.subItems.filter((p) => p.id !== "null").map((q) => q.id);
        emph.clearOverriddenElements(vp, ecIds);
      });
      isFirst = false;
      break;
    }
  }

  if (isFirst) {
    // if no elements have been overriden yet
    EmphasizeElements.getOrCreate(vp).overrideElements(
      ["0"],
      vp,
      ColorDef.black,
      undefined,
      isFirst // override everything if it is the very first item
    );
  }
};`


**Results before HideAll action performed**
![image](https://github.com/iTwin/itwinjs-core/assets/46311365/46bf8ed9-acc5-4a51-b31d-601bdb9a6817)

**Results after HideAll action performed**
![image](https://github.com/iTwin/itwinjs-core/assets/46311365/63d9cf6d-a05f-4fcb-a7da-c267568a487f)

**Comment by bbastings** [comment]
If the goal is to reset everything back to defaults, EmphasizeElements.clear will do that...

You would call clearOverridenElements to remove overrides established by overrideElements only. It seems like you are expecting this to also clear emphasized elements or a defaultAppearance change, those are independent.

**Comment by bbastings** [comment]
Should also mention that I'm not sure what you are trying to do here, "0" is not a valid element id...

emph.overrideElements(["0"], vp, ColorDef.black, undefined, isFirst);

**Comment by pratiknesarkar99** [comment]
Update on this issue fix: After some conversation with @bbastings - it was evident that the method is purposely intended not to reset to a view where no elements are highlighted, thus it does not clear all the elements just using the **clearOverriddenElements** 
and we also need to call another method **clearAlwaysDrawnElements** to also clear the list of always drawn elements before using a kind of smart hack as suggested by Brien. 

This hack allows the user to clear all the elements and reset the view to default appearance (view with no elements highlighted), which in our case is the required functionality.
The hack goes as follows: 

// if no elements have been overridden yet
EmphasizeElements.getOrCreate(vp).overrideElements(
["0"],
vp,
ColorDef.black,
undefined,
isFirst // override everything if it is the very first item
); 

Using the mentioned methods and the kind of hack, solved our requirement, thus closing this issue with a detailed descripition for anyone else facing the same kind of issue.
