### ISSUE TITLE
BlankConnection.create causes undefined name and/or error

### ISSUE THREAD

**Issue by Alfonso-Martello** [iTwin/itwinjs-core#6000]
**Describe the bug**
The BlankConnectionProps interface requires a `name` prop to be provided.
https://github.com/iTwin/itwinjs-core/blob/a5ea75963f709e854612c5f1f0a1302ef6bd8a9f/core/frontend/src/IModelConnection.ts#L45

When you create a new BlankConnection via `BlankConnection.create(blankConnectionProps)`, the name property is not passed into the IModelConnection constructor.
```
    return new this({
      rootSubject: { name: props.name },
      projectExtents: props.extents,
      globalOrigin: props.globalOrigin,
      ecefLocation: props.location instanceof Cartographic ? EcefLocation.createFromCartographicOrigin(props.location) : props.location,
      key: "",
      iTwinId: props.iTwinId,
    });
```
https://github.com/iTwin/itwinjs-core/blob/a5ea75963f709e854612c5f1f0a1302ef6bd8a9f/core/frontend/src/IModelConnection.ts#L712 

The IModelConnection constructor assumes the name is defined and passed in as a prop.
https://github.com/iTwin/itwinjs-core/blob/a5ea75963f709e854612c5f1f0a1302ef6bd8a9f/core/frontend/src/IModelConnection.ts#L218

Therefore, getting the name of the BlankConnection results in an "Assert: Programmer Error" during development.
https://github.com/iTwin/itwinjs-core/blob/a5ea75963f709e854612c5f1f0a1302ef6bd8a9f/core/common/src/IModel.ts#L370

**To Reproduce**

1. Add these lines to any code in development mode:
```
  const blankConnectionProps: BlankConnectionProps = {
    name: "I will be an error",
    location: Cartographic.fromDegrees({ longitude: -75.686694, latitude: 40.065757, height: 0 }),
    extents: new Range3d(-1000, -1000, -100, 1000, 1000, 100)
  }
  const iModelConnection = BlankConnection.create(blankConnectionProps);
  console.log(iModelConnection.name);
```
2. Run the code.
3. See error.

Note: The error is not reproducible in the sandbox. The sandbox runs in production mode, which strips away the assert. In the sandbox, you will instead see that the name is undefined despite being provided. Checkout the sandbox [Blank-Connection-Invalid-Name](https://www.itwinjs.org/sandboxes/AlfonsoMartello/Blank-Connection-Invalid-Name) for an example.

**Expected behavior**
The BlankConnection should use the name provided.

**Screenshots**
Error in development mode:
![image](https://github.com/iTwin/itwinjs-core/assets/113918602/f5ac57ad-bc56-49cf-a403-f51e979c55aa)

**Desktop (please complete the applicable information):**

- OS: Windows 11
- Browser: Any
- iTwin.js Version: Reproduced on 3.7.7 - 4.x. Probably present on earlier versions.

**Comment by pmconne** [comment]
Do you intend to submit a PR to fix it?

**Comment by Alfonso-Martello** [comment]
Sure, I'll make a PR
