### ISSUE TITLE
PresentationManager.getElementProperties error

### ISSUE THREAD

**Issue by beolson** [iTwin/itwinjs-core#6021]
**Describe the bug**

Trying to get the presentation properties for all elements in a model.  I use an IModel query to get all element Ids, then iterate over the resulting list and call getElementProperties on each elementId.  

This works until it it throws the following error:

```
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
```
It seems to be random where it throws it - sometimes it will succeeded on 200 elements before throwing an error, sometimes it will succeeded on 2000 elements - but it always throws this error.  

**To Reproduce**
This code block demonstrates the problem:

```
        const queryReader = iModelDb.createQueryReader("SELECT ECInstanceId, ECClassId FROM bis.Element");
        const elementIds: Array<string> = [];
        for await (const row of queryReader) {
            elementIds.push(row[0])
        }

        console.log(elementIds.length)

        for await (const elementId of elementIds) {

            console.log(`Reading Element presentation ${elementId}`);
            // when it errors, it will throw on the next line
            var pres = await new PresentationManager({}).getElementProperties({ imodel: iModelDb, elementId: elementId, })

            console.log(`Got presentation for element ${elementId}`);

            this._recordCount++;
        }
```

**Expected behavior**
Dont throw the error

**Screenshots**
NA

**Desktop (please complete the applicable information):**

- OS: Windows 10 running in WSL
- Browser NA - running in a terminal CLI
- iTwin.js Version 
ITwin libraries in the application (not all used by this example):
    "@itwin/node-cli-authorization": "1.0.1",
    "@itwin/core-backend": "4.1.6",
    "@itwin/core-bentley": "4.1.6",
    "@itwin/core-common": "4.1.6",
    "@itwin/core-geometry": "4.1.6",
    "@itwin/core-transformer": "3.7.12",
    "@itwin/imodels-access-backend": "4.1.0",
    "@itwin/service-authorization": "1.0.3",
    "@itwin/ecschema-metadata": "4.1.6",
    "@itwin/core-quantity": "4.1.6",
    "@itwin/presentation-backend": "4.1.6",
    "@itwin/presentation-common": "4.1.6"

**Additional context**

**Comment by beolson** [comment]
noticed something just as I was hitting submit on the issue.  I noticed I was creating a new instance of PresentationManager inside my for of loop.  A quick test shows that it seems to work if I move the creation of that outside my loop.  

I will test a little more to verify

```
        const pm = new PresentationManager({})

        for await (const elementId of elementIds) {

            console.log(`Reading Element presentation ${elementId}`);
            var pres = await pm.getElementProperties({ imodel: this.iModelDb, elementId: elementId, })

            console.log(`Got presentation for element ${elementId}`);

            this._recordCount++;
        }```

**Comment by grigasp** [comment]
Thanks @beolson, I'm glad you figured out the solution.

I believe you may have ran out of resources with your initial implementation - `PresentationManager` implements `IDisposable` interface and expects its `dispose()` method to be called when you don't need it anymore. Without that, it keeps some native resources allocated indefinitely and, since you created a large number of managers, you could've just ran out of memory.

BTW, calling `dispose()` is required on your single instance in the new implementation too.
