### ISSUE TITLE
SQLite warning log spam when creating new Standalone iModels

### ISSUE THREAD

**Issue by karolis-zukauskas** [iTwin/itwinjs-core#6066]
**Describe the bug**
When creating a new standalone iModel with `StandaloneDb.createEmpty(...)` I get 259 log messages with severity warning and the message `"no such table: ..."`. Everything seems to work after creating the standalone iModel, so I believe the spam of warnings is unnecessary.

**To Reproduce**
Execute: `StandaloneDb.createEmpty("D:\\temp.bim", { rootSubject: { name: "test" } });`

**Expected behavior**
If everything is fine (I assume it is), don't show ~260 warnings (looks like something is wrong and obfuscates actual warnings/errors).

**Screenshots**
![image](https://github.com/iTwin/itwinjs-core/assets/36916096/9da6754d-c67c-4f5b-b001-24a972c14327)

**Desktop (please complete the applicable information):**

- OS: Windows 11
- Browser Electron
- Version ^26.0.0
- iTwin.js Version 4.2.0-dev.28

**Comment by nick4598** [comment]
You can add `Logger.setLevel(NativeLoggerCategory.SQLite, LogLevel.None);` as a line before StandaloneDb.createEmpty and that should suppress all of these warnings. Would that work for you?

**Comment by karolis-zukauskas** [comment]
@nick4598, I don't want to supress logging because what if there are actual errors/warnings being logged that I want to take care of? It just feels like the implementation is "cheating" and instead of doing some proper check if tables exist it executes an empty query and catches the error - somewhere in that call stack the log happens. It shouldn't be that way ..

**Comment by karolis-zukauskas** [comment]
I guess we could disable logging and re-enable it right after the `StandaloneDb.createEmpty(...)` call, but still feels a bit odd.
