### ISSUE TITLE
Display Test App no longer works

### ISSUE THREAD

**Issue by laurynas111** [iTwin/itwinjs-core#6079]
It seems that display-test-app no longer works with latest changes.
The App never finishes loading when started as an Electron app.

1. Pull latest code
2. Run `rush update`
3. Run `rush rebuild`
4. Navigate to test-apps/display-test-app folder and run `npm run start`

**Expected behavior**
The app loads and iModels can be opened

**Additional context**
App works when checkout reverted to cf5f5c8b099e2d1545a13e4b7eeb5467a78db98c commit

**Comment by pmconne** [comment]
@laurynas111 does exception call stack look like the following reported by @mlemuzic-bentley? If not, please provide call stack.
![image](https://github.com/iTwin/itwinjs-core/assets/22944042/88a6e070-b85b-410e-9ff2-61837d2150a8)
@mlemuzic-bentley reverted #6073 and the problem was resolved. @mcote01?
I failed to reproduce it.

**Comment by pmconne** [comment]
> I don't see the "rush copy:config" step in there. Isn't that needed?

Should only be needed after you've pulled changes into the config repo.

**Comment by pmconne** [comment]
@mlemuzic-bentley @laurynas111 please try the following:
```
diff --git a/test-apps/display-test-app/src/frontend/App.ts b/test-apps/display-test-app/src/frontend/App.ts
index 3df13f86f4..4bbb145a58 100644
--- a/test-apps/display-test-app/src/frontend/App.ts
+++ b/test-apps/display-test-app/src/frontend/App.ts
@@ -232,7 +232,7 @@ export class DisplayTestApp {
       /** API Version. v1 by default */
       // version?: ApiVersion;
       /** API Url. Used to select environment. Defaults to "https://api.bentley.com/reality-management/reality-data" */
-      baseUrl: `https://${process.env.IMJS_URL_PREFIX}api.bentley.com`,
+      baseUrl: `https://${process.env.IMJS_URL_PREFIX ?? ""}api.bentley.com`,
```
