### ISSUE TITLE
Deprecated tool

### ISSUE THREAD

**Issue by HalimSalameh** [iTwin/itwinjs-core#6090]
"Debugger for Chrome" is deprecated. JS debugger is now built-in in VS code. You should consider removing it from the "suggested tools" list.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Development-prerequisites---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/tutorials/development-prerequisites/

**Comment by aruniverse** [comment]
Would you like to contribute a PR to update the documentation? :)

**Comment by HalimSalameh** [comment]
Yes I would! My first contribution!
https://github.com/iTwin/itwinjs-core/pull/6091
