### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by Lionel-Lim** [iTwin/itwinjs-core#6104]
The following line has typo error (Duplicated Point and Vector types):
Many arguments which might be strongly typed as Point3d, Vector3d, Point3d, Vector3d are weakly typed as XYandZ or XandY.

Revised line would be:
Many arguments that could be strongly typed as Point3d, Vector3d, Point2d, or Vector2d are weakly typed as XYandZ or XandY.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Point-and-Vector-operations---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/geometry/pointvector/

**Comment by aruniverse** [comment]
would you like to man an open source contribution? :)
