### ISSUE TITLE
ViewportComponent from a sheet view

### ISSUE THREAD

**Issue by jzbuchalski** [iTwin/itwinjs-core#6124]
**Bug:**
We are duplicating the selected view in a ViewportComponent nested in a widget.  The ViewportComponent takes as props the view state.  We are passing in a cloned view state.  The component works for spatial views, but for **sheet views**, we get the exception:

  public attachToViewport(_args: AttachToViewportArgs): void {
    if (this.isAttachedToViewport)
      throw new Error("Attempting to attach a ViewState that is already attached to a Viewport");

**Issue:**
  public override attachToViewport(args: AttachToViewportArgs): void {
    super.attachToViewport(args);  **// VewState.attachToView is called initially**
    assert(undefined === this._attachments);
    this._attachments = this._attachmentsInfo.createAttachments(this); **// ViewState.attachToView is called a second time**
  }

**Callstack:**
![image](https://github.com/iTwin/itwinjs-core/assets/17307464/655cd6a9-545d-44e9-9187-81a4f357c928)

I will investigate creating a codesandbox.

**Comment by pmconne** [comment]
When we clone the SheetViewState we need to clone (or otherwise not attempt to reuse) the AttachmentInfo's ViewStates.

**Comment by ben-polinsky** [comment]
@mergify backport release/4.2.x
