### ISSUE TITLE
Add BeAsyncEvent

### ISSUE THREAD

**Issue by karolis-zukauskas** [iTwin/itwinjs-core#6186]
**Is your feature request related to a problem? Please describe.**
Implement `BeAsyncEvent<T>` that has the same interface as `BeEvent<T>` but supports/respects async functions (awaits Promises).

**Describe alternatives you've considered**
Async code is all around, it only seems natural to have async aware `BeEvent` in the core and not have to implement similar types on every project.

**Comment by pmconne** [comment]
Please provide examples of why it is useful for the event dispatcher to await each event listener's callback. i.e., if you and I both subscribe to SomeEvent, why would it be useful for my listener to have to wait to be notified of the event until after your listener completes whatever potentially long-running async work it wants to do?

To me that makes no sense. `BeEvent` is about notifying any number of listeners of an event's occurrence, at the moment it occurs. Each listener can respond in whatever manner it sees fit, and should not interfere with or delay notification of other listeners. The notifier does not care - it's job is complete once it has notified all listeners.

If I misunderstand your proposal, please clarify.

**Comment by karolis-zukauskas** [comment]
I think you are right @pmconne, the purpose of `BeEvent` should only be to notify of an event that happened (should not care how its handled). Perhaps the thing I need (awaiting the completion of all handlers) is not general enough or at least the name of BeAsyncEvent doesn't fit.

In my use case, I'll just go with an array of async handlers that are invoked and awaited.
