### ISSUE TITLE
Support 3d markers (2.5D points)

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#6195]
**Is your feature request related to a problem? Please describe.**
Implementing #6194.

**Describe the solution you'd like**
#6194 requires the ability to draw a potentially large number of mostly static billboard images efficiently.

**Describe alternatives you've considered**
Using decorators - not efficient (need to update + redraw constantly)
Using 2d canvas markers - does not participate in depth test.

**Additional context**
This type of marker is available in and used by one of our applications today, using custom tile server and custom extension to the display system. We want to eliminate both of those. Additionally, other servers also supply these markers, which we cannot currently display.

Requested by @alarkbentley and @mdastous-bentley.

**Comment by pmconne** [comment]
We already have:
- Marker - a 2d canvas decoration that is visually very similar to what is being requested but does not render via WebGL so does not participate in depth test with 3d geometry; and
- ParticleCollectionBuilder - an efficient way to draw many instances of a single billboard image.

We could probably enhance our particle systems to support a texture atlas instead of a single billboard. We'd need to produce a texture atlas from the collection of billboard images. It will be simpler if all of the images have the same dimensions - packing the atlas would be trivial and each instance could refer to its image by a single integer index - but need to determine if that's an acceptable constraint.

**Comment by markschlosseratbentley** [comment]
@danieliborra

**Comment by danieliborra** [comment]
There are other teams interested in this, e.g. @MarcBedard8's annotation service and IOT.
We had some recent initial conversations about how to structure and render this type of data in an efficient way (100Ks of points), using standard (GIS) formats if possible.

I'd start by collecting a list of technical requirements from the different teams and develop a single solution that covers all use cases. I'd suggest to discuss this on the next Tiling Services meeting (all the ones involved in this are included in the meeting).

**Comment by markschlosseratbentley** [comment]
@AJMigliore

**Comment by danieliborra** [comment]
I added this to the [iTwin Graphics Service Backlog](https://github.com/orgs/iTwin/projects/37).

I'd also check how Open City Planner and Cesium.js implemented this, to get some ideas.

**Comment by markschlosseratbentley** [comment]
@danieliborra FYI

**Comment by markschlosseratbentley** [comment]
Initial research work: https://github.com/iTwin/itwinjs-core/pull/6439

**Comment by danieliborra** [comment]
A few months ago @evelynpreslar-bentley developed and presented an example for the iTX team that shown how to load and visualize a GeoJson dataset with 2.5D points and 3D lines in iTwin Viewer => https://github.com/iTwin/itwin-graphics-backlog/issues/268 (the code is linked in that issue)

And @Josh-Schifter also shown another example a few comments above.
