### ISSUE TITLE
Raster text ignores surface transparency

### ISSUE THREAD

**Issue by a-gagnon** [iTwin/itwinjs-core#6239]
**Describe the bug**
The defaultAppearance we set when calling `EmphasizeElements.emphasizeElements` does not always get applied to 3D text graphic. 
It works fine when we're zoomed in close, but as we move out, the text goes back to its original style.

Please refer to the attached video below

**To Reproduce**
1. Open an iModel that has 3D text graphics. (The dataset I'm using is in QA if need be)
2. Emphasize some elements of the model with a default apperance.

**Expected behavior**
Default appearance should be applied regardless of zoom level

**Desktop (please complete the applicable information):**
- OS: Windows 11
- Browser: Chrome
- Version: 119.0.6045.160 (Official Build) (64-bit) (cohort: Stable) 
- iTwin.js Version: 4.2.1

**Additional context**
Here's a video of the behavior:

https://github.com/iTwin/itwinjs-core/assets/3418768/b2a648a2-2ed2-46bc-83cb-22235f5d4273

**Comment by pmconne** [comment]
To be specific: text rendered as textured quads ("raster glyphs") ignores transparency feature overrides.
That is computed [here](https://github.com/iTwin/itwinjs-core/blob/528bbdd42a1e66c699144962b64b9fb8d31940a2/core/frontend/src/render/webgl/glsl/Surface.ts#L489).
