### ISSUE TITLE
There is no official full form of 'NPM'

### ISSUE THREAD

**Issue by YashodipD** [iTwin/itwinjs-core#6282]
In our list of glossaries- I see below 

**Npm -	[Node Package Manager](https://www.npmjs.com/). A tool for distributing JavaScript packages.**

There is no official full form of NPM. NPM is just NPM. To describe, sometimes people say that it is the **default package manager for the JavaScript runtime environment Node.js**

Found on page https://www.itwinjs.org/learning/glossary - "Glossary of terms in iTwin.js"

**Comment by ben-polinsky** [comment]
Perhaps I am misunderstanding, but we do not state there is an "official full form" of NPM? What is your issue with the wording here?

**Comment by YashodipD** [comment]
yes, with the wording. My only point was there no meaning to NPM acronym. However, whenever we write NPM with Node Package Manager. Reader misunderstands that as a full form of NPM acronym. 

If you think that it is not worth fixing. I will close / delete the issue right away.

**Comment by YashodipD** [comment]
https://en.wikipedia.org/wiki/NPM

![image](https://github.com/iTwin/itwinjs-core/assets/113993668/17f6cabc-b640-40e2-b77d-6cdc2a8c019d)

**Comment by ben-polinsky** [comment]
Ahhhh I understand the acronym :) Sure, if you want to raise a PR with improved wording that is fine.

**Comment by YashodipD** [comment]
https://github.com/iTwin/itwinjs-core/pull/6304

**Comment by YashodipD** [comment]
https://github.com/iTwin/itwinjs-core/pull/6308
