### ISSUE TITLE
Clicking on the Camera tool repeatedly results in the view to zoom out a little bit each time.

### ISSUE THREAD

**Issue by mcayer-Bentley** [iTwin/itwinjs-core#6385]
**Describe the bug**
When turning the camera ON and OFF reapeatedly, the view is zoomed out a little bit each time. Please see screen capture attached. 
The original view is when I open the iModel.
![original view](https://github.com/iTwin/itwinjs-core/assets/106612924/7c3471e2-3aea-4efb-95fa-34188501154e)
This one is the zoom level we see after 6 clicks on the camera.
![after 6 clicks on the camera](https://github.com/iTwin/itwinjs-core/assets/106612924/bcea81ad-ca9d-4e3d-9654-fb2e72a98d7c)

**To Reproduce**

1. Open an iModel in iTwin.js viewer (i.e. Design Review)
2. Click on the "Turn Camera OFF" and then "Turn Camera ON". Do it few times.
RESULT: The view zooms out a little bit each time we click on the camera.

**Expected behavior**
The view should not zoom out each time we click on the Camera tool.
**Screenshots**

**Desktop (please complete the applicable information):**

- iTwin.js Version [e.g. 2.5.3]

**Additional context**

**Comment by pmconne** [comment]
Why is this a problem (i.e., in what real workflow do users repeatedly turn camera off and on)?

**Comment by mcayer-Bentley** [comment]
You are right, probably not willing to happen in a real workflow. This was reported by one of our QA who tests limit cases.
