### ISSUE TITLE
Documentation Issue: `Raise an issue in our repo` hover preview broken

### ISSUE THREAD

**Issue by anmolshres98** [iTwin/itwinjs-core#6391]
When hovering over `Raise an issue in our repo` hyperlink, the preview shown is broken:
<img width="1305" alt="image" src="https://github.com/iTwin/itwinjs-core/assets/98850418/c84016d4-adc9-4c56-9097-2c957e7737f9">

**Comment by anmolshres98** [comment]
PR to address this: https://dev.azure.com/bentleycs/iModelTechnologies/_git/BeMetalsmith/pullrequest/400165

**Comment by ben-polinsky** [comment]
This has been fixed for a while
