### ISSUE TITLE
AccuDraw dialog/widget is not working correctly in polar mode.

### ISSUE THREAD

**Issue by YashodipD** [iTwin/itwinjs-core#6478]
### Describe the bug

AccuDraw have 2 modes - rectangular and polar. It works correctly for rectangular mode. Works correctly means - input fields are auto focused as per current position of mouse pointer relative to compass axis. If mouse pointer is on Y - axis of accudraw compass, it focuses on y input fields. If pointer moves to another direction i.e x, automatically input focus goes on x input field. 

same thing does not happen for polar mode. When I activated arc tool from editor package from iTwin core.  

Note- while testing all the tools are used from here - https://github.com/iTwin/itwinjs-core/tree/master/editor

### To Reproduce

Prerequisite - import tools from editor package - https://github.com/iTwin/itwinjs-core/tree/master/editor
To produce the incorrect behavior of AccuDraw widget/dialog in below are the steps.   
1.  From the sketch tools activate the `Create Arc` tool. (should work with any editor tool)
2. click on viewport for 2 times to radius of the arc. 
this is current state of accudraw compass and input fields
![image](https://github.com/iTwin/appui/assets/113993668/2ab1746d-efb5-462f-aa3b-a0d73b246db6)

3. user manually needs to go to input and activate the compass focus and enter the values which is wrong. 
![image](https://github.com/iTwin/appui/assets/113993668/33b69c9d-bd7d-4d63-aa98-3ace51270457)

### Expected Behavior

Like it happens in rectangular mode of AccuDraw. 

Respective input fields should be activated based on current position of cursor in polar mode.

### Desktop (please complete the applicable information)

Version: 1.0.16 (a9f230f) 
Build: iTwin Desktop Platform (Mango) 2024.02.06-1 
iTwin.js: 4.4.0-dev.10 
iTwinUI: 3.2.3 
AppUI: 4.6.1 
React: 17.0.2 
Node.js: 18.16.1 
Electron: 26.6.1 
Build Tools Commit: 60d5287

DrawingProduction: 0.0.0 - our app name

**Comment by Josh-Schifter** [comment]
At least in our experiments, there is a difference between the itwin editor tools and MicroStation.
1. Start Arc Tool using 'Start, Center' mode
2. Enter first point.  Now compass shows 'active' in rectangular mode and focus auto hops between X and Y (good)
3. Enter second point.  Now compass shows 'inactive' in polar mode.  Focus is on NEITHER distance nor angle field. (bad)

In MicroStation, accudraw stays 'active' after the second point and focus goes to the distance field.  I can switch to angle using <tab>.  In itwin, I need to use my mouse to put focus into one of the accudraw input fields before I can use <tab>.
