### ISSUE TITLE
SectionDrawing.insert(iModelDb: IModelDb, documentListModelId: string, name: string) inserts a DrawingModel, not a SectionDrawingModel

### ISSUE THREAD

**Issue by Alfonso-Martello** [iTwin/itwinjs-core#6511]
**Describe the bug**
The `SectionDrawing` class extends the `Drawing` class. The Drawing class provides a helper method [`insert(iModelDb: IModelDb, documentListModelId: string, name: string): string`](https://www.itwinjs.org/reference/core-backend/elements/drawing/insertstatic/) to create/insert both a `Drawing` element and a `DrawingModel` at the same time.

The `SectionDrawing` class inherits this method. Calling `SectionDrawing.insert(iModelDb: IModelDb, documentListModelId: string, name: string)` causes a `SectionDrawing` element and a `DrawingModel` to be inserted. I would have expected a `SectionDrawingModel` to be inserted instead.

**To Reproduce**

1. Have a test iModel with an existing DocumentListModel.
2. Call `SectionDrawing.insert(iModelDb: IModelDb, documentListModelId: string, name: string)`.
3. Query the iModel for a BisCore.Element and a BisCore.Model with the ECInstanceId returned from the function call in step 2.
4. See that the element is of the expected class (`SectionDrawing`), but the model is not (`DrawingModel`).

**Expected behavior**
Calling `SectionDrawing.insert(iModelDb: IModelDb, documentListModelId: string, name: string)` should insert a `SectionDrawing` and a `SectionDrawingModel`.

**Comment by pmconne** [comment]
Show your code.
In particular, explain on what basis you drew the conclusion that "the element is of the expected class (SectionDrawing), but the model is not (DrawingModel)."

**Comment by Alfonso-Martello** [comment]
I will start with why I thought this was a bug. If I am misunderstanding something we can close this issue.

The current behavior of `SectionDrawing.insert(iModelDb: IModelDb, documentListModelId: string, name: string)` is to insert a SectionDrawing being sub-modeled by a DrawingModel.

Reason 1: The [documentation](https://www.itwinjs.org/reference/core-backend/elements/sectiondrawing/#sectiondrawing) explicitly states that a SectionDrawing is sub-modeled by a SectionDrawingModel.
Reason 2: My understanding is that when possible we want to use the most specific class to define our element/model. In my opinion, SectionDrawingModel is the more specific class about what the model is and how it is used. It does not really add any functionality, but adds meaning.

I see the existing section drawing test also uses a DrawingModel. If it is expected that SectionDrawings are modeled by DrawingModels, then my next question is under what circumstances are SectionDrawingModels used?
[Here](https://github.com/iTwin/itwinjs-core/pull/6513) is my PR adding a unit test showing the behavior I would have expected.

**Comment by pmconne** [comment]
Thanks @Alfonso-Martello - that's very helpful.
I've adjusted your PR to fix the problem.
