### ISSUE TITLE
Backend crashes if `elements.getElementProps()` is called after closing iModel connection

### ISSUE THREAD

**Issue by EimantasMorkunas** [iTwin/itwinjs-core#6517]
**Describe the bug**
If backend tries to query element props by calling `IModelDb.elements.getElementProps()` after the briefcase was closed, the backend crashes.

**To Reproduce**
The issue is reproducible when user closes the iModel while backend is performing some long running operations (e.g. computing geometry cuts).

Simplified example:

Backend
```ts
class SomeIpcImpl extends RpcInterface implements SomeIpcInterface {
  public async stubLongRunningTask(rpcProps: IModelRpcProps, elementId: string) {
    const db = IModelDb.findByKey(rpcProps.key);
    setTimeout(() => {
      db.elements.getElementProps(elementId);
    }, 500);
  }
```

Frontend
```ts
await SomeIpcInterface.getClient().stubLongRunningTask(iModelConnection.getRpcProps(), "0xffffff");
await iModelConnection.close();
```

**Expected behavior**
`elements.getElementProps()` (or any DB access) throws if iModel is already closed.

**System info:**

- OS: iOS/Android.
- Browser: WebView.
- Version: any.
- iTwin.js version: 4.3.2.

**Additional context**
iModel.js 2.19.x used to throw NotFound exception in such case.

**Comment by vincasrazmabentley** [comment]
This is a regression in iTwin.js 4.x (compared to iModel.js 2.19.x) and is blocking the SYNCHRO Field release, is this something that could be fixed?
@tcobbs-bentley @pmconne or others

**Comment by pmconne** [comment]
`IModelDb._nativeDb` used to get set to `undefined` after closing the iModel. `tryGetElementJson` would do `iModel.nativeDb.getElement` producing a null reference exception on `nativeDb`, and return `undefined` from its `catch` block.

#5620 changed that, removing `_nativeDb`. Now `IModelDb.nativeDb` is always defined, even after the iModel is closed. Presumably the native code was not updated to validate that the iModel is open, and this leads to a crash somewhere. It's likely that other entry points into native code are also failing to handle the case where the iModel is closed.

Here's the [discussion](https://github.com/iTwin/itwinjs-core/pull/5620#discussion_r1230498207) about that change. Here's a [trivial test](https://github.com/iTwin/itwinjs-core/pull/6534) reproducing the crash. On `release/2.19.x`, the test instead produces a `NotFound` exception.

**Comment by pmconne** [comment]
@khanaffan @nick4598 @aruniverse a bunch of methods in IModelJsNative.cpp are missing a `RequireDbIsOpen`. We either have to add those, or adjust the TypeScript code to perform similar checks, or revert the change that removed `IModelDb._nativeDb`.

**Comment by kabentley** [comment]
We should add the `RequireDbIsOpen` test in the all native code methods that take a db arg and expect it to be valid.

**Comment by EimantasMorkunas** [comment]
@pmconne Is there an ETA on the release that will fix this?

**Comment by pmconne** [comment]
@EimantasMorkunas 4.5.0 was published yesterday.
