### ISSUE TITLE
should ClassRegistry.register() be a public instead of internal ?

### ISSUE THREAD

**Issue by YashodipD** [iTwin/itwinjs-core#6589]
**Describe the bug**
If I want to register individual entityClass, there is no way.  Only way is to register that class as module using ClassRegistry.registerModule().

**Expected behavior**
Make a ClassRegistry.register() api public.

**Comment by YashodipD** [comment]
https://github.com/iTwin/itwinjs-core/discussions/6588

**Comment by pmconne** [comment]
Submit a PR.
