### ISSUE TITLE
BriefcaseTxns should provide more context with onChanged events.

### ISSUE THREAD

**Issue by Ellord207** [iTwin/itwinjs-core#6607]
**Is your feature request related to a problem? Please describe.**
When reacting to the `onElementsChanged` and `onModelsChanged` events from [BriefcaseTxns](https://www.itwinjs.org/reference/core-frontend/imodelconnection/briefcasetxns/), we are finding that each listener needs to query for the classes of the elements/models that triggered the event as a filter, or is just dumbly reacting to it anyways.  This creates unnecessary traffic for the backend.

**Describe the solution you'd like**
The events should also include information about what class of elements/models was changed.  Preferably, in a way that relates the changed element/model id with the class. 

**Describe alternatives you've considered**
Nothing worth mentioning.

**Additional context**
We see changes come it 2 forms, small focused changes from editing workflows, and large sets of changes from a pull of the iModel.

**Comment by pmconne** [comment]
Describe more specifically what you are trying to achieve and why the current events do not suffice for those purposes.

**Comment by Ellord207** [comment]
# What the current problem is

Say in an editing app, there are 3 different UI widgets that are populated based on elements in the iModel.  Each one of those widgets has subscribed to the `onElementsChanged` event.

Each time there is an element inserted, they will each individually need to query the backend with a similar request.  This request is either:
1. Something like `SELECT ECClassId FROM Bis.Elements WHERE ECInstanceId IN [InsertedElements]` (to avoid complicated queries).  The results are then filtered and the complicated query is triggered only on the necessary elements.
2. Just repopulating their full list (in cases where the query is simple).

We have similar, situations for models as well.  This creates repeated coded and unnecessary backend traffic.

Similarly, in the cases of delete or modify.  Assuming the ids of the elements in the widgets are cached in the UI, this means we need to test each item of a list/table for an id in the modified or deleted sets.  While having these sets sorted does help, having to repeat this process for each widget does not lend itself to scaling.

It would help if there was a centralized API to provide more context about changed elements, and allow the listeners to only handle events they find relevant, without each needing to make similar searches.

# Example Solutions

## What I think this would ideally look like is:
When subscribing to the onChangeElements/Models event, the listener would provide a list of ECClasses.  The API would only raise the event to that specific listener if the changes contain elements of or children of the ECClasses given when subscribing.  The `ChangedEntities` object passed to that subscriber callback would only contain the ids of elements of those classes.  Perhaps this would be architecturally similar to a [Bucket Sort](https://en.wikipedia.org/wiki/Bucket_sort).

## Alternative solutions 
### Optimally for small changes (common case for editing workflow)
Reworking `ChangedEntities` to have a insert/modify/delete arrays as Compressed Elements ids (as they currently are), and each array has an accompanying class array (ex. insertClasses) which is a compressed array of Class Id.
```
{
  insert: [0x02],
  insertClass: [Bis.LineStyle],
  modify: [0x01]
  modifyClass: [Bis.DisplayStyle2d]
}
```
When decompressed, each array and it's accompanying class array are related by their shared index.
This would double the data transferred during the event, but would trivialize smaller changesets on the frontend.  Unfortunately, in the cases of large changes, it would require traversing the entire unsorted array to find particular classes, which may end-up actually being less efficient.

 ### For large changes (a use case common to none editing workflows)
Reworking `ChangedEntities` to have an insert/modify/delete arrays as Compressed Elements ids (as they currently are), each array has an accompanying class array (ex. insertClasses) which is a compressed *sorted* array of *unique* Class Ids.  Meaning each class id in the accompanying classes array would be listed once, and would communicate that each there is at least one element of that class in set of element ids.
```
{
  insert: [0x01, 0x02, 0x03],
  insertClass: [Bis.GeometryElemend2d],
}
```
While this is the least obviously helpful, it would reduce a common query.  I would suggest, before adopting this suggestion,  a wider analysis more real users data (in the form of their changesets) than I personal have access to.

**Comment by pmconne** [comment]
Thanks. To summarize (leaving out implementation details):
- Transaction events received on the frontend should provide access to the class full names (**not** class **Ids**) of each changed entity.
- It should be easy and (relatively) efficient to filter the changed entities based on their classes (including subclasses - e.g., "all `GeometricElement3d`s and subclasses thereof").

Did I miss anything?

**Comment by Ellord207** [comment]
Perfect.  Thank you.

**Comment by pmconne** [comment]
[WIP](https://github.com/iTwin/itwinjs-core/pull/6676).

**Comment by pmconne** [comment]
@Ellord207 @Josh-Schifter this will be included in the next nightly build. See [NextVersion.md](https://github.com/iTwin/itwinjs-core/blob/master/docs/changehistory/NextVersion.md#transaction-metadata) for details.
