### ISSUE TITLE
Documentation Issue: Grammar mistake

### ISSUE THREAD

**Issue by HalimSalameh** [iTwin/itwinjs-core#6639]
On the page linked below, there is this statement after the second paragraph:
    `Txns are stored in a "local" table, so they are don't attempt to track themselves.`
I am not sure what the statement is supposed to mean, so I can't suggest a correction, but it certainly needs correction, more specifically, "are don't".

Found on page https://www.itwinjs.org/learning/interactiveediting - "Interactive Editing Applications"

**Comment by ben-polinsky** [comment]
Thanks! 

@pmconne @calebmshafer (git blame is obscured by format changes) - any context we could add, in addition to the grammatical correction?

**Comment by pmconne** [comment]
#6640.
