### ISSUE TITLE
Annotations in drawings and sheets display in real-time only if they are drawn inside the project extents

### ISSUE THREAD

**Issue by Alfonso-Martello** [iTwin/itwinjs-core#6672]
**Describe the bug**
Annotations added to a drawing or sheet do not display unless they are inside of the project extents.

Observe the gif linked below for the current behavior (blue is the project extents, red is the viewed extents, and the green cube is the world origin (0,0,0)):
[house-model-drawing-gif](https://bentley-my.sharepoint.com/:i:/p/alfonso_martello/Ed5eG_JsGOlNm5c7S4uOTf0Br_U75JJQqiMWk8zQEkEb4g?e=fPUCTi)

The House model was used to create the above gif. It just so happens that the project extents for the house model are near the world origin. However, this issue becomes much more apparent on models that are not near the world origin. Observe the Bay Town Process Plant model below:
![image](https://github.com/iTwin/itwinjs-core/assets/113918602/eb94c3f7-3aff-4e7d-a607-258906a4c026)
The project extents are not near the world origin. Below is another linked gif showing annotations only appearing within the project extents for a drawing in the Bay Town Process Plant model:
[process-plant-model-drawing-gif](https://bentley-my.sharepoint.com/:i:/p/alfonso_martello/ESwOYxXccltGsourhg-ENU0BbgzvPGPtgqTYXsBNQlSMoA?e=4HpSVA)

The examples I showed are all drawings. However, the same behavior occurs in sheets. If the sheet is not located within the project extents, then annotations do not appear until the iModel is re-opened.

**Questions**
My assumption is that the above behavior is a bug. If it is not, I have a few questions:
1.	Why do annotation elements in drawings/sheets need to be in the project extents if the elements are not spatial elements?
2.	Is it expected that drawings/sheets need to be within the model’s project extents (as in, we should be moving our models and sheets to the project extents)?

**To Reproduce**
I have provided .bim files with drawings like the ones in the gifs. The drawings were created in our channel, so I’m not sure how useful they will be. Let me know if you would like me to port a reproduction branch to the Display Test App so the above behavior can be recreated.

[house .bim](https://bentley-my.sharepoint.com/:u:/p/alfonso_martello/Eat1X-MfXA5CgTbqwDuZ7JIBvpVZXxglc-zAx1jvNA_tDA?e=0679y0): The saved drawing view is called "drawing2".
[process-plant .bim](https://bentley-my.sharepoint.com/:u:/p/alfonso_martello/EcoSc754x05Eh9nQ8-BOFvgB-PlqwJydoa6GHawDSy8M8Q?e=5GQeE4): The saved drawing view is called "drawing2".

**Expected behavior**
I should be able to add annotations to my drawings/sheets freely and have those annotations display after I add them, regardless of the spatial project extents.

**Desktop (please complete the applicable information):**

- OS: Windows 11
- Browser: Electron
- Version: 29.1.0
- iTwin.js Version: 4.4.7

**Additional context**
A few definitions that I think support the case the drawing annotations should not be constrained to the spatial project extents.

- Project extents are “the volume, in spatial coordinates, inside which the entire project is contained” (as per the [documentation](https://www.itwinjs.org/reference/core-common/imodels/imodel/projectextents/#projectextents)).
- Drawings usually have no correlation to spatial coordinates (as per the [documentation]( https://www.itwinjs.org/learning/display/drawingsandsheets/#drawings))
- Sheets have precise physical dimensions correlating to actual physical paper sizes (as per the [documentation]( https://www.itwinjs.org/learning/display/drawingsandsheets/#sheets)).

**Comment by pmconne** [comment]
Don't make me guess at what your code looks like please.

**Comment by Alfonso-Martello** [comment]
I'll add a reproduction to DTA

**Comment by pmconne** [comment]
Are you using a [GraphicalEditingScope](https://www.itwinjs.org/reference/core-frontend/imodelconnection/graphicaleditingscope/)?

**Comment by Alfonso-Martello** [comment]
> Are you using a [GraphicalEditingScope](https://www.itwinjs.org/reference/core-frontend/imodelconnection/graphicaleditingscope/)?

Yes

**Comment by Alfonso-Martello** [comment]
I have created a [PR](https://github.com/iTwin/itwinjs-core/pull/6680) adding the editor tools, a drawing creation tool, and an origin/extents decoration tool to DTA.

I have sent you an email with more in-depth reproduction instructions and some additional .bim files. The email is also titled "Annotations in drawings and sheets display in real-time only if they are drawn inside the project extents".

The issue does seem related to GraphicalEditingScope. If I am not in editing scope, I can freely add annotations. If I am in editing scope, annotations only appear if drawn inside the project extents.
