### ISSUE TITLE
Text Annotation orientation should rotate about the anchor point

### ISSUE THREAD

**Issue by Josh-Schifter** [iTwin/itwinjs-core#6688]
I expect the property TextAnnotation.orientation to rotate the text geometry about the anchor point.  Currently, it is rotating about the lower left.

**To Reproduce**
Please use the following branch which includes some changes to DisplayTestApp to make it easier to see the bug:
https://github.com/iTwin/itwinjs-core/tree/text-rotation-bug

The keyin sequence below assumes you are using [house.bim](https://bentley-my.sharepoint.com/:u:/p/josh_schifter/EVCf6j_XEQVNhPZ95d_P2KgBdQ44sscW1ESNM5efAxvEng?e=EskLJC) for categoryId and font name.  But any bim file with a 2d view can be used.

1. Start Display Test App, Open an .bim file, choose a 2d view.
2. Enter the following sequence of key-ins:
        dta text init 0x200000000c8
        dta text font arial
        dta text text abcdefghi
        dta text center
        dta text anchor vertical bottom
        dta text rotation 30
        dta text rotation 45
        dta text rotation 90
3. Observe that the text is rotating about the lower left instead of the bottom, middle as expected.

**Expected behavior**
Text should rotate about the anchor point

**Screenshots**
![image](https://github.com/iTwin/itwinjs-core/assets/38294200/77d01b3e-f9ec-4bfd-bc2d-1b48ecfdbfcb)

**Desktop (please complete the applicable information):**
- OS: Windows
- iTwin.js Version 4.6.0-dev.19

**Comment by Josh-Schifter** [comment]
@pmconne

**Comment by pmconne** [comment]
@Josh-Schifter please review [the fix](https://github.com/iTwin/itwinjs-core/pull/6693). Note, I changed your `anchor` keyins to be less verbose - just `dta text anchor left`, `dta text anchor bottom`, etc.
