### ISSUE TITLE
`TorusPipe.createAlongArc` returns pipe with wrong angular sweep

### ISSUE THREAD

**Issue by dovydasjaru** [iTwin/itwinjs-core#6691]
**Describe the bug**
TorusPipe creates a solid that is offset from the curve.

**To Reproduce**
code snippet:
`TorusPipe.createAlongArc(curve, diameter / 2, true)`

diameter = 0.009525
curve as json => {"center":[-0.0035718750000000004,0,0],"sweep":[0,90.0050353193204],"vector0":[-0.001190625,0.127,0],"vector90":[0.001190625,7.776507174585693e-18,0.127]}

**Expected behavior**
TorusPipe creates a solid that is along the curve.

**Screenshots**
![image](https://github.com/iTwin/itwinjs-core/assets/36199182/1c4cb867-8cef-48f6-9202-5f991a623ec6)
In the screenshot there are four curves making a full circle. But it is visible that part of TorusPipe is outside the curve.

**Desktop:**
- OS: Windows 11
- Node version v18.17.1
- iTwin.js Version 4.4.9

**Comment by dassaf4** [comment]
Ultimately the code is failing ungracefully because your `Arc3d` is not circular, and `TorusPipe` assumes circularity. In the meantime, you can probably avoid the issue by ensuring your input arc is circular.
