### ISSUE TITLE
Documentation Issue: Search on "Category" leads to 404

### ISSUE THREAD

**Issue by simihartstein** [iTwin/itwinjs-core#6735]
Clicking on category class after searching for "category" leads to a 404

Found on page [ https://www.itwinjs.org/reference/core-backend/imodels/category - "undefined"](https://www.itwinjs.org/reference/core-backend/categories/category/)

![image](https://github.com/iTwin/itwinjs-core/assets/6485888/d6fa98ef-2fec-44a0-8a04-99d342e80f2e)

**Comment by ben-polinsky** [comment]
Thanks. Fixed.
