### ISSUE TITLE
TextAnnotation Width + Anchor point bugs

### ISSUE THREAD

**Issue by claudiaareneee** [iTwin/itwinjs-core#6768]
**Describe the bug**

I've noticed the following issues/possible issues with the [`TextAnnotation`](https://github.com/iTwin/itwinjs-core/blob/1c2c71ee5c0ddd43c5e686b7cebf098830c1d2be/core/common/src/annotation/TextAnnotation.ts) class:

1. **Document width + anchor point**: I noticed that changing the width via `dta text width` does cap the width and word wraps as expected. However, this doesn't seem to be registered by the anchor point or the computed text range. I would expect the anchor point to adjust to the text block width. 
  
  ![image](https://github.com/iTwin/itwinjs-core/assets/25939215/ccf9e4e6-dc63-4363-b951-66fd27ecdf52)

2. **Document width + justification**: for this one, if I have multiple lines and try to justify them to the right or to the center, they align themselves based off the previous line. While this makes my test strings super poetic, this is a bug, right? Also the anchor point is thrown way off to the side, which is intriguing to me.

  ![image](https://github.com/iTwin/itwinjs-core/assets/25939215/ef28d52a-2600-4429-a06b-3d7dd4dee9ef)

3. **Anchor point + placement origin**: when changing the anchor point, I expect the anchor point to remain fixed at the element/graphics's origin, and for the text to move relative to the anchor point. Let me know if I'm misunderstanding the use of the anchor point. 

  ![image](https://github.com/iTwin/itwinjs-core/assets/25939215/da7654e5-2ae3-4bd5-bf4d-751ef54501a8)

4. **The debug tools**: Also, this one's not a super big deal, but I noticed when rotating the text element, the debug graphics don't reflect that rotation. That may be intentional, but just thought I would point that out in case it wasn't. 

  <img src="https://github.com/iTwin/itwinjs-core/assets/25939215/1680eb98-6f06-4c7d-a4ec-a19785a9e237" alt="drawing" width="300"/>

**To Reproduce**

I'm running display test app. Last pull, Friday 5/24/2024.

For all of these, I started with these base key-ins:
```txt
dta text init "0x20000000087"
dta text font arial
dta text center
dta text width 20
dta text text "It was the best of times. It was the worst of times."
```

0. Set `debugAnchorPointAndRange` to `true`: https://github.com/iTwin/itwinjs-core/blob/8434bf71c4c37ba43a3ed1ef9c2c65308e4c92fa/core/backend/src/TextAnnotationGeometry.ts#L201

1. **Document width + anchor point**: 
    Additional Key-ins: _no extra, I just used the above key-ins_

2. **Document width + justification**: 
    Additional Key-ins:
    ```txt
    dta text justify center
    ```

3. **Anchor point + placement origin**: 
    Additional Key-ins:
    ```txt
    dta text anchor right
    dta text anchor left
    ```

4. **The debug tools**: 
    Additional Key-ins:
    ```txt
    dta text rotation 45
    ```

**Expected behavior**

Summed up in the description.

**Screenshots**

Summed up in the description.

**Desktop (please complete the applicable information):**

- OS: Windows
- Browser: Electron
- iTwin.js Version: ^4.6.0 ish, I'm using display test app, last pull, Friday 5/24/2024.

**Additional context**

**Comment by pmconne** [comment]
#4 is intentional. The debug graphics are primarily intended to visualize the offset and orientation relative to the anchor point and bounding box. If we applied the same transform to the debug graphics as we do to the text, it would be difficult to determine what point we were translating and/or rotation relative to, because that point would move.
