### ISSUE TITLE
TextBlock fraction alignment should default to 'middle'

### ISSUE THREAD

**Issue by Josh-Schifter** [iTwin/itwinjs-core#6777]
**Is your feature request related to a problem? Please describe.**
Currently, TextBlock does not support the concept of fraction alignment from MicroStation.  Presumably it was removed for simplicity which is fine with me.  The issue is that presently we only support bottom alignment which I'm pretty sure is much less desirable compared to middle alignment.

**Describe the solution you'd like**
Support middle fraction alignment only.  If there is some use case for bottom, then at least provide a way to use middle.

**Additional context**
This is needed for dimensioning where bottom will look terrible.

![image](https://github.com/iTwin/itwinjs-core/assets/38294200/f76f81fd-5206-4542-b138-78872539f2c3)

I used the following keyins to create the first text in the image.

dta text init 0x200000000c8
dta text font arial
dta text text "first line"
dta text paragraph
dta text text "abc "
dta text fraction 1 2
dta text text " def"
dta text paragraph
dta text text "third line"

**Comment by pmconne** [comment]
Do the fractions look as desired when using the diagonal separator?

**Comment by Josh-Schifter** [comment]
> Do the fractions look as desired when using the diagonal separator?

No.  Still bottom aligned.

![image](https://github.com/iTwin/itwinjs-core/assets/38294200/603f2d7c-6349-4a4f-9441-ebfd9e322df8)

**Comment by pmconne** [comment]
Fixed in #6769
