### ISSUE TITLE
Animated gif in a docs page not displayed

### ISSUE THREAD

**Issue by toddsouthenbentley** [iTwin/itwinjs-core#6786]
There's supposed to be an animated gif in this documentation page: https://www.itwinjs.org/learning/display/tiles but it's showing as a broken link in my browser.

Looking at the Developer Tools, it seems to be a problem with `Gifffer`:
![image](https://github.com/iTwin/itwinjs-core/assets/48103957/aff2e0c0-4e5d-4951-99cb-d52700ca78c5)

**Comment by pmconne** [comment]
GIF displays fine when Tiles.md is viewed locally in Chrome.
`![Composing a view from multiple models](./assets/office-models.gif)`
@ben-polinsky?

**Comment by ben-polinsky** [comment]
Fixed.
