### ISSUE TITLE
Provide a text annotation layout API for use on front-end

### ISSUE THREAD

**Issue by Alfonso-Martello** [iTwin/itwinjs-core#6793]
**Is your feature request related to a problem? Please describe.**
I am working on creating a caret API for drawing production. A caret is a marker used to indicate a location within a text block for performing actions (like insert). The caret API needs to know its location in the layout, but the layout function/classes are marked as internal.

**Describe the solution you'd like**
Please explicitly export `layoutTextBlock` and `TextBlockLayout` and remove the `@internal` tag. 

**Describe alternatives you've considered**
Normally, I could access this internal code for development in the short-term. However, I am working in iTwin Studio, and iTwin Studio has a build time check that disallows deep iTwin.js imports such as “import X from @itwin/core-backend/lib/cjs/TextAnnotationLayout”.

**Comment by Alfonso-Martello** [comment]
@pmconne, I assume this is a simple change of removing the `@internal` tag and adding the mentioned classes/functions to the export list. If you do not have any objections to or questions about making the above class and function available, I will submit a PR making the necessary changes.

**Comment by pmconne** [comment]
Yeah I kept them internal in part because they are messier than they should be for public APIs, and in part because I suspect you will want your caret to reside on the front-end whereas these are backend-only APIs.

I briefly had a public API in core-common that would provide a representation of the layout usable on the frontend but I had no use for it at that time so removed it to reduce API surface area.

Why don't we talk about what your API will look like and how it will use the layout.

**Comment by pmconne** [comment]
Yeah that's basically what the core-common representation of the layout was, removed in [this commit](https://github.com/iTwin/itwinjs-core/pull/6572/commits/99114eb49044457e185789486049b10a995dc58c#diff-82d7b519d69272ac46ac8c86a821bb55f9a680b72b27db4016d4664aaac2ad5c).

Please make sure you have read [this](https://dmitripavlutin.com/what-every-javascript-developer-should-know-about-unicode/) and are routinely testing with emojis, Asian characters, combining characters, etc.

**Comment by Alfonso-Martello** [comment]
That commit looks close to what I need. Currently, `layoutTextBlock` is `@internal` and the results are not persisted. I would need that function exposed or the calculated result persisted/returned somewhere not internal.

That article was a very informative read, thank you for sharing it. I will account for special characters and make sure to test with various tricky characters.

**Comment by Alfonso-Martello** [comment]
Yes.

> Are you volunteering to resurrect a cleaned-up version of the API in that commit and add an IPC function to allow your front-end to obtain a layout result for a text annotation?

I read this as a request to
1. Resurrect and clean-up that API and make a PR here. The goal will be to make `layoutTextBlock` public.
2. Then, in my own application, I will make an IPC to obtain the layout result from `layoutTextBlock`. 

If you are suggesting something else, please let me know. In the meantime, I will start on the PR.
