### ISSUE TITLE
UI Admin input editor closes when I move the mouse. 

### ISSUE THREAD

**Issue by mathieu-fournier** [iTwin/itwinjs-core#6803]
**Describe the bug**
I am showing an input. 
![image](https://github.com/iTwin/itwinjs-core/assets/82905333/bdfe0bba-1eaf-477f-b11a-c379210330a8)
And it closes when I move the mouse. 

In my case, it should ignore mouse movements. 
It should close when doing another action. Ex : clicking a widget, a button, exiting the active tool, etc..
Excluding mouse movements and view-ralted actions. Like zooming.
So, I would like to control when it closes, because not every event should close it. 

**To Reproduce**

1. Create a input editor. Ex : 

``` 
const propertyDescription: PropertyDescription = { name: "a name", displayLabel: "a display label", typename: "number" };
IModelApp.uiAdmin.showInputEditor(30, propertyDescription, IModelApp.uiAdmin.cursorPosition, commitAInput, closeAInput);
```

2. Open it and move the mouse. 
3. Notice that commit has been called when the mouse moved and the input is now closed. 

Thanks

**Comment by pmconne** [comment]
@GerardasB

**Comment by GerardasB** [comment]
I can not reproduce the described behavior in our test app: https://github.com/iTwin/appui/commit/5a25c4cae4019433cfe298d0e34f3b01c2155c1d
Once the input editor is opened via `showInputEditor` it stays open until `hideInputEditor` is called.

There seem to be no explicit `hideInputEditor` calls from any of `itwinjs-core` or `appui` event handlers. Could you verify if `hideInputEditor` is called in your app?

**Comment by mathieu-fournier** [comment]
I did a checkout to a previous version where it happened, and I cannot reproduce either.
Must have been fixed with a new version of something, but I dont have the lockfile to compare. 
Thanks for the answer anyway (:
