### ISSUE TITLE
Warning message only in Firefox

### ISSUE THREAD

**Issue by muthubentley** [iTwin/itwinjs-core#6817]
**Describe the bug**
User is getting the below message in console . This is output only in Firefox browser.
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. Capabilities.ts:261:25

**To Reproduce**

1. Go to Firefox browser
2. Launch my iTwins
3. Check the console log

**Expected behavior**
Though there is no impact to the behavior , Since it is mentioned as something deprecated . User is concerned if this could be a issue in future. Warning message should not be output.

**Comment by pmconne** [comment]
There is no way to tell a browser not to output a warning message to the browser console.
We use the `WEBGL_debug_renderer_info` extension to detect GPUs that have known bugs so we can apply workarounds to make them function properly. Many of our users have laptops containing lower-end Intel GPUs that exhibit these bugs; without applying these workarounds, iModels do not display correctly on their devices.

Secondarily, we use the extension to detect when the user has no GPU, or has not configured their browser to use it, to warn them of potential severe performance degradation and provide guidance on resolving the problem.

Only Mozilla has deprecated this extension, and they have not removed it, nor have they provided an alternative. It causes no problem.

**Comment by muthubentley** [comment]
Thanks @pmconne
