### ISSUE TITLE
Allow to Disable Element Tooltips 

### ISSUE THREAD

**Issue by mathieu-fournier** [iTwin/itwinjs-core#6832]
A informational tooltip appears automatically when the mouse is still for a short period of time. 
We need a way to disable these.
They appear on top of everything and should just not appear at all. 
![image](https://github.com/iTwin/itwinjs-core/assets/82905333/c146e542-fdac-4b16-a2e2-0e9952162848)

We can costumize them with tooltip provider.
But even if we costumize them to be empty, an empty tooltip box still appears. 

I'm not 100% sure, but I think[ this line](https://github.com/iTwin/itwinjs-core/blob/392898afb80fd2ac3e68fe00b7c676b0fbb747c2/core/frontend/src/HitDetail.ts#L300C1-L301C1) is where the tooltip is 'activated'.

The solution should be someting that ressembles : 
`IModelApp.viewManager.disableTooltips = true.` 
`IModelApp.uiAdmin.updateFeatureFlags({ showTooltips: false });`

Thanks.

**Comment by GerardasB** [comment]
[NotificationManager](https://www.itwinjs.org/reference/core-frontend/notifications/notificationmanager/) already has a getter `isToolTipSupported` that is used by `AccuSnap` APIs that you could override.
Alternatively, you could override `_showToolTip` of your notification manager (I assume you are using [AppNotificationManager](https://www.itwinjs.org/reference/appui-react/notification/appnotificationmanager/)).

**Comment by mathieu-fournier** [comment]
These are readonly and private properties, I cant change them. 
![image](https://github.com/iTwin/itwinjs-core/assets/82905333/151ff366-3e32-45a6-9c07-07e64602d6c8)

**Comment by mathieu-fournier** [comment]
We can hide the tooltip by doing a wrapper over the base class like this, but I dont really like that we are overwriting the frameworks implementation. 
![image](https://github.com/iTwin/itwinjs-core/assets/82905333/edcdab1f-9a2e-4ddf-b6bb-b412004f023f)

**Comment by mathieu-fournier** [comment]
Fixed by #6934
