### ISSUE TITLE
Error while importing schemas

### ISSUE THREAD

**Issue by FelixGirard** [iTwin/itwinjs-core#6912]
**Describe the bug**
In itwin version 4.7.0, we are able to import our schemas. On version 4.7.2, we get no error and it is stuck at this location:

![image](https://github.com/iTwin/itwinjs-core/assets/7445146/78fcc616-4549-4e48-8dc2-d5ddfbca2df2)

**Expected behavior**
I would not expect it to be infinitely stuck... At least a clear error would be nice.

**Desktop:**

- OS: Windows
- Browser electron
- iTwin.js Version 4.7.2

Please pm me for any additional information.

**Comment by aruniverse** [comment]
Thank you for bringing this up, unfortunately we are no longer supporting 3.x as of a month ago. Please let us know if this issue still persists on the latest 4.x ver

**Comment by FelixGirard** [comment]
Sorry I had 3 by mistake. It's actually 4.7.2

**Comment by pmconne** [comment]
> Please pm me for any additional information.

Can you just provide the information in the issue directly?
If it's sensitive, transfer the issue to the private itwinjs-backlog repository.

**Comment by pmconne** [comment]
> Can you just provide the information in the issue directly?
> If it's sensitive, transfer the issue to the private itwinjs-backlog repository.

@FelixGirard
