### ISSUE TITLE
Documentation Issue: Dead link

### ISSUE THREAD

**Issue by BeChaRem** [iTwin/itwinjs-core#6995]
The link for "Localization in iTwin.js" is wrong. It should lead to https://github.com/iTwin/itwinjs-core/blob/master/docs/learning/frontend/Localization.md . Weird thing is that the url in the code seems right.

Found on page https://www.itwinjs.org/presentation/advanced/localization - "Localization"

**Comment by ben-polinsky** [comment]
Hi. Seems like forward slashes should be used. To avoid having to move up in the folder structure, check out https://github.com/iTwin/itwinjs-core/blob/master/core/backend/src/Category.ts#L195 for an example of how you can link relative to the docs root using `$docs`
