### ISSUE TITLE
Black Color Text Rendering Issue in TextAnnotation2d Causing Unusual Line Segment

### ISSUE THREAD

**Issue by SaurabhTalele-Bentley** [iTwin/itwinjs-core#7048]
**Describe the bug**
When creating text using the TextAnnotation2d tool with black color, an unexpected line segment appears on the canvas. This issue is specific to the black color and does not occur with other colors. The line segment becomes part of the text’s geometry, resulting in an unusual and unintended graphic representation. This problem is observed in the Display Test app and other applications built on top of it.
**To Reproduce**
Steps to reproduce the behavior (Display Test App):
1. Open the model in 2D view in the display text app
2. get the category id
3. keyins:
	a. dta text init <Category id>
	b. dta text font <Font name eg. "Arial">
	c. dta text color black
	d. dta text text "Any text"
	e. dta text center (Optional if the canvas is blank)
**Expected Behavior:** 
The text should render correctly without any additional line segments.

**Screenshots**
Default Text output
![Screenshot 2024-08-08 105537](https://github.com/user-attachments/assets/beb9f73f-8ce7-431d-abef-1800df2d168f)

Output of Red Color
![Screenshot 2024-08-08 105825](https://github.com/user-attachments/assets/1aae2630-bb27-4f1c-8af4-c4e99d2b5fb1)

After setting the color to black:
![bug black](https://github.com/user-attachments/assets/a3a85f1a-1e4a-4f1f-8e63-3138ae234d5d)

Code Output:
![image](https://github.com/user-attachments/assets/ae5ec673-70c4-4241-ac34-2cc9e3def6f8)

**Additional context**
This issue does not occur with other colors. The problem seems to be isolated to the black color rendering in the TextAnnotation2d tool.

Code to regenerate
[TextAnnotationProblem.zip](https://github.com/user-attachments/files/16539339/TextAnnotationProblem.zip)

**Comment by pmconne** [comment]
Please refine your repro steps and expected/observed behaviors. You provide 3 screenshots, but your repro steps only ask that I place one string of black text. You provide a TextAnnotationProblem.js script, but don't tell me what I'm supposed to do with it.

Bad repro steps tell me to open any iModel, use any font, type any text, and assume I will observe the same result as you.
Good repro steps provide a .bim file and provide exact key-ins with specific fonts, text, etc and the output you observe vs what you expect.
Good repro steps mean that we don't have to waste time here on GitHub to determine whether we're both testing the same problem, instead of fixing the problem.

**Comment by SaurabhTalele-Bentley** [comment]
Steps to repro:
1. Open the attached .bim file in Display Test app 
2. switch the view to `:ef:7ca66`
3. zoom to any blank area to see the text clearly.
4. input the key-ins.
- `dta text init 0x1447`
- `dta text font "Arial"`
- `dta text color black`
- `dta text text "Hello"`
- `dta text center`

**Expected Output**
A text `Hello` in the center of the view without any line segment.

![image](https://github.com/user-attachments/assets/0f52d9ec-a3c0-4063-92b5-53bc0b2e507a)

**Actual output**
Text `Hello` with a line segment in the center (as we put `text center` key-in)

![image](https://github.com/user-attachments/assets/1372ff12-54be-49ce-9d18-c203ce11d91c)


You can find the bim file in the zip below:
[HouseModelBim.zip](https://github.com/user-attachments/files/16542007/HouseModelBim.zip)

**Comment by pmconne** [comment]
Thanks, those repro steps are :man_cook: :kiss: 
Fixed in #7054.
4.8 is about to go out the door. If this fix is not included in 4.8.0 I can get it backported to 4.8.1.
