### ISSUE TITLE
Multi-sentence property docs are truncated on at least one page

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#7051]
**Describe the bug**
For a property with documentation comment exceeding one sentence, only the first sentence is accessible via the deployed docs site. The property shows as a link, but clicking it does not reveal the rest of the sentences in the documentation comment.

**To Reproduce**

1. Got to https://www.itwinjs.org/reference/core-backend/imodelhost/imodelhostoptions/
1. Observe `maxTileCacheDbSize` displays the first sentence of its doc comment.
1. Click on it `maxTileCacheDbSize` link.

**Expected behavior**
Clicking the link takes me to a dedicated page containing the full documentation for that property.

**Actual behavior**
Clicking the link takes me to https://www.itwinjs.org/reference/core-backend/imodelhost/imodelhostoptions/#maxtilecachedbsize which is the same page I'm on and reveals no more information.

**Screenshots**
![image](https://github.com/user-attachments/assets/9dabac53-2b24-4acb-8f1e-bd62961f63dd)

**Desktop (please complete the applicable information):**

- iTwin.js Version [e.g. 2.5.3]

**Additional context**
Same behavior is observed with all other property links on the `IModelHostOptions` doc page. The links on other pages, like `IModelHost`, appear to function as expected.

**Comment by ben-polinsky** [comment]
Thanks, I'll take a look

**Comment by ben-polinsky** [comment]
Bug related to how we parse interface members. Fixed. 

https://www.itwinjs.org/reference/core-backend/imodelhost/imodelhostoptions/ (might have to hard refresh) 
https://www.itwinjs.org/reference/core-backend/imodelhost/imodelhostoptions/maxtilecachedbsize/
