### ISSUE TITLE
Documentation Issue: Insert variable into localized strings

### ISSUE THREAD

**Issue by arome** [iTwin/itwinjs-core#7106]
Is there an option available in the Localization interface that allows us to insert variable into a localized string?
i.e.: I want to translate everything in this sentence except for the fileName that I'll be providing.

`The file ${fileName} already exists. Do you want to replace it or keep both files?`)

Found on page https://www.itwinjs.org/reference/core-common/localization/localization

**Comment by arome** [comment]
I found that its possible to be done by putting a double curly braces {{ variable }}.

**Comment by williamkbentley** [comment]
correct. the options in `getLocalizedString` come from i18next. you can use their [interpolation](https://www.i18next.com/translation-function/interpolation) and other functions, such as plurals and formatting
