### ISSUE TITLE
Issue with locate when creating graphics on a worker

### ISSUE THREAD

**Issue by matmarchand** [iTwin/itwinjs-core#7117]
**Describe the bug**
Locate features is inconsistent when graphics are created on a worker. The same graphics will be locatable if they are created on the main thread. Only locate is affected, the display is fine.

**To Reproduce**
Code was inspired from the graphic in worker examples. See branch: https://github.com/iTwin/itwinjs-core/tree/MathieuM/workerExample

1. In display test app, open blank connection
2. In the tool bar click on the "smiley face icon". This will trigger the graphics creation on a worker.
3. A green, blue and red circles will display in the view.  
4. Locate on the green circle will work.
5. Locate will only work on the top part of the blue circle.
6. Locate will not work on the red circle

**Expected behavior**
The same graphic will work when created on the main thread.  I expect same behavior when creating them in a worker thread.

**Screenshots**
Top of blue circle is locatable
![image](https://github.com/user-attachments/assets/d4ab7851-a313-49e4-b9c9-d294ac104417)
Bottom of blue circle is not locatable
![image](https://github.com/user-attachments/assets/dcdc259a-bfea-4d01-b27b-49a7296fed9e)

**Comment by pmconne** [comment]
> The same graphic will work when created on the main thread.

I don't see code on your branch that creates the same graphic on the main thread.

**Comment by pmconne** [comment]
When I run your branch and follow your instructions, I get a blue circle - no green or red circles - and the blue circle is locatable at every point on its perimeter. What am I missing?

**Comment by matmarchand** [comment]
Sorry about that, I updated the code with 3 circles and also with the main thread part.  One geometry will locate fine, from my observation you need more than one to start having troubles.
