### ISSUE TITLE
Raise SheetViewState.computeFitView from internal

### ISSUE THREAD

**Issue by Ellord207** [iTwin/itwinjs-core#7222]
[SheetViewState.computeFitView](https://github.com/iTwin/itwinjs-core/blob/c7ce913cd0a65d00306372850b057a2de5673fcb/core/frontend/src/SheetViewState.ts#L557) has the internal tag, and is the only override of ViewState.computeFitView with the internal tag.  Can the method please be raised from internal, or help me understand why it is marked that way and the alternatives.

We are using it in our workflows when generating view definition of new Sheet models.  It is particularly helpful when the Model is new and empty.

**Comment by pmconne** [comment]
At one point we thought it would make sense to mark overridden methods as `@internal` to keep them from cluttering the docs, since all the useful documentation is on the base class method. That was misguided. Please submit a PR.
