### ISSUE TITLE
Documentation Issue: WorkerProxy completely missing documentation

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#7237]
Doc page:
![Image](https://github.com/user-attachments/assets/44f5b17e-fe36-4c48-9c7e-11b7e6a11136)

Source code:
```ts
/** A proxy for a [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Worker) that provides the operations specified by
 * the methods of `T`.
 * To use a worker proxy, define a worker script that provides [[registerWorker]] with an implementation of `T`, and obtain a proxy
 * via [[createWorkerProxy]] on the main thread. The proxy can then be used to asynchronously invoke methods of `T` on the worker.
 * See [this article]($docs/learning/frontend/WorkerProxy.md) for more details and examples.
 * @beta
 */
export type WorkerProxy<T> = WorkerInterface<T> & {
```

The [article](https://github.com/iTwin/itwinjs-core/blob/master/docs/learning/frontend/WorkerProxy.md) is very detailed with lots of example code, none of it surfaced in the doc site.

Found on page https://www.itwinjs.org/reference/core-frontend/utils/workerproxy - "undefined"

**Comment by ben-polinsky** [comment]
Fix incoming

**Comment by ben-polinsky** [comment]
Done. We were not showing any comments beyond tags (`@see`, etc). In addition, because the same `DeclarationReflection.kind` is used for any `type = ` type, the badge now displays "Type" instead of "Type Alias".
