### ISSUE TITLE
AccuSnap Hints on SectionDrawings

### ISSUE THREAD

**Issue by Ellord207** [iTwin/itwinjs-core#7245]
**Describe the bug**

While viewing a section drawing, Tools with AccuSnap does not give hints for geometry coming from the spatial view.

**To Reproduce**

1. Create and load a ViewStete of SectionDrawing
2. Start a tool with AccuSnap (such as the measure tool)
3. Observe AccuSnap hints on geometry not in the spatial view
4. Observe NO AccuSnap hints on geometry from the Spatial View.

You can reference the SectionDrawings and ViewDefintions in this [iModel](https://qa-developer.bentley.com/my-itwins/8d6e2269-0816-4b63-a404-0ddd996497cc/83c0afdf-ccf7-4782-8b0d-0b7680d8ee5b/home/).  If requested, I can provide access or a local snapshot.  I have confirm this bug is Observable in DTA with the ViewDefinitions `section-with-annotations` and `test-section-drawing` in this iModel.

**Expected behavior**
I would expect AccuSnap to provide hints on the geometry from the spatial view.

**Screenshots**
Here is a video it happening.  In the video, the view is a sheet with an attached SectionDrawing.  The result is the same if you just view the section drawing directly.

https://github.com/user-attachments/assets/bcf4e1a5-2114-4081-9f46-b89b48a94fca

**Desktop (please complete the applicable information):**
- iTwin.js Version 4.9.0 (not specific to this version)

**Additional context**
I am able to Select the geometry with the SelectTool, just no AccuSnap Hints.

**Comment by pmconne** [comment]
#5633 added support for snapping to geometry inside ViewAttachments in sheets. It did not do anything to support snapping to geometry inside a section drawing's attached spatial view. The solution would presumably be very similar.

**Comment by Ellord207** [comment]
> [@Ellord207](https://github.com/Ellord207) can you please describe what specifically you are trying to accomplish? Like, are you trying to draw a leader between a dimension and the dimensioned element? Are you trying to measure distances between things in the sheet and in the spatial view or drawing? etc.

We expect the users will need snapping to:
1. Drawing leaders for dimensions, bubble properties, and other such annotations inside the SectionDrawing
2. Snap and offset annotations from existing annotations for a clean layout.
3. Measuring distances of elements inside the SectionDrawing
4. Drawing annotations and markup on a Sheet with one or more attached views of SectionDrawings
5. There is a fringe case where the user will want to measure between annotations in a Sheet/SectionDrawing and elements in the spatial view for layout purposes.

While we are hoping to automate a lot of these eventually, but manual editing will still need to be supported.

**Comment by Ellord207** [comment]
The provided fix works for uses cases 1-3, but does not allow for uses 4 & 5.  When using an authoring tool, AccuSnap hints are present when viewing a Section Drawing, but when viewing that same Section Drawing as an attachment on a sheet, the AccuSnap hints are not Present.

https://github.com/user-attachments/assets/76d85983-36b4-4e28-864a-dd08c410b4f7

While this use case is less urgent, it is something we will need to support.

**Comment by pmconne** [comment]
> when viewing that same Section Drawing as an attachment on a sheet, the AccuSnap hints are not Present.

Ok, I'll try to get that working before tomorrow's demo.

**Comment by pmconne** [comment]
@Ellord207 try now, close if satisfied.

**Comment by Ellord207** [comment]
Works as expected.  Thank you.
