### ISSUE TITLE
SectionDrawing geometry disappearing when zooming out

### ISSUE THREAD

**Issue by Ellord207** [iTwin/itwinjs-core#7302]
**Describe the bug**

A SectionDrawing, geometry can appear/disappear based on zoom levels.  See video and screenshots for more information.

**To Reproduce**

I wasn't able to find the exact steps to reproduce outside of this particular iModel.  Seems to happen only with larger iModels.  A few general observations about this in **Addition Context**.

You can reference to the SectionDrawings and ViewDefintions in this [iModel](https://qa-developer.bentley.com/my-itwins/8d6e2269-0816-4b63-a404-0ddd996497cc/b7be722c-40fd-4ab8-a438-c77ee31f9063/home/). If requested, I can provide access or a local snapshot. I have confirmed this bug is observable in DTA with the ViewDefinitions `test2d-1` and `test2d-2` in this iModel.

**Expected behavior**
I'd expect all geometry to be visible at all reasonable zoom levels.

**Screenshots**

https://github.com/user-attachments/assets/2db7d377-255f-43be-b5c3-7ba2254d827a

Image of iModel used to create SectionDrawing.  Including the depth of the range used to create the SectionDrawing in case it is relevant.

![Image](https://github.com/user-attachments/assets/d8c48f8a-2f63-43da-8da9-d64bc7a28e39)

Image of same iModel with a range drawn around the area clipped to create the Section Drawing.  The front plane of the SectionDrawing is aligned with the Top of the range.

![Image](https://github.com/user-attachments/assets/35058bdc-5fd3-4466-9e14-1ec326f48e1f)

**Desktop (please complete the applicable information):**

- OS: Windows: 10
- Browser: Electron
- Version: 29.1.0
- iTwin.js Version: 4.10.0-dev.20

**Additional context**
I find it interesting that the geometry appearing is all in the same model.  Some geometry will not disappear no matter how far I zoom out.  Some of it is at the same depth as well.

**Comment by pmconne** [comment]
> I can provide access or a local snapshot. 

Please do (.bim file).

**Comment by pmconne** [comment]
This isn't a section drawing problem, it's a clipping problem. The disappearing geometry is reproducible in the spatial views you created for your section drawings. You've got geometry precisely coplanar with your clipping planes.

**Comment by Ellord207** [comment]
Thanks for figuring that out.  I was calculating the clip range based on the model extents.  After adding a 1% margin, the issue went away.
