### ISSUE TITLE
Property is named `extendType` when it should be `extendedType`

### ISSUE THREAD

**Issue by DonataSnieskaite** [iTwin/itwinjs-core#7361]
An object of type `QueryPropertyMetaData`, (specifically one returned from `ECSqlReader.getMetaData()`) according to [ConcurrentQuery.ts](https://github.com/iTwin/itwinjs-core/blob/d8b4364092ea7f00c0340179a51ff1ae126395f8/core/common/src/ConcurrentQuery.ts#L4), should have a property `extendType`. 

However, if you try to access it, it will be undefined:
![Image](https://github.com/user-attachments/assets/cf5b52b2-8096-46ea-80bd-6c2b93ee8e42)
![Image](https://github.com/user-attachments/assets/1f402976-cdba-4ba1-af34-3f64a752b0fe)

Instead, the property can be accessed by calling `extendedType`:
![Image](https://github.com/user-attachments/assets/7a5549a4-2e92-4cc3-a71d-ec9f855a42f2)
![Image](https://github.com/user-attachments/assets/5979b579-4135-4aae-91f6-521c00a5f684)

**Comment by hl662** [comment]
@ColinKerr

**Comment by hl662** [comment]
For added info, using metadata.extendedType will cause a build error, because it doesn't match the interface definition of QueryPropertyMetadata.
