### ISSUE TITLE
CloudSqlite.DbAccess.createBlobContainer() overrides containerType to be "property-store"

### ISSUE THREAD

**Issue by arbrumbaugh** [iTwin/itwinjs-core#7370]
**Describe the bug**
Base class `CloudSqlite.DbAccess` overrides all subclasses that call into `createBlobContainer()` by creating a `BlobContainer` of containerType = "property-store".

See [CloudSqlite.DbAccess.createBlobContainer()](https://github.com/iTwin/itwinjs-core/blob/master/core/backend/src/CloudSqlite.ts#L920C102-L920C133)

**To Reproduce**
Attempt to create a new Workspace CloudContainer by following the code snippet here [Creating workspace resources](https://www.itwinjs.org/learning/backend/workspace/#creating-workspace-resources). 
In [EditorImpl.initializeContainer()](https://github.com/iTwin/itwinjs-core/blob/master/core/backend/src/internal/workspace/WorkspaceImpl.ts#L491C105-L491C131), it attempts to create the `BlobContainer` with containerType = "workspace" but that gets overridden to be "property-store".

**Expected behavior**
Can create a BlobContainer of types other than "property-store".

**Desktop (please complete the applicable information):**

- iTwin.js Version 4.9.3 (but looks like the issue is also on latest)

**Comment by pmconne** [comment]
Introduced in #6646. Unclear why - `metadata.containerType` is a required input. Should be trivial fix (just need unit test).
