### ISSUE TITLE
Bing Maps Copyright Duplicates

### ISSUE THREAD

**Issue by jason-crow** [iTwin/itwinjs-core#7406]
When opening the copyright dialog from the itwinjs logo in the bottom left of the viewport, the bing maps section should appear like this:
![Image](https://github.com/user-attachments/assets/1a912abf-aa6d-44ff-90fa-42342a3e06d0)
After 4.10 it appears like this:
![Image](https://github.com/user-attachments/assets/576eacaf-d765-4ea3-96e1-b917957ef1b6)

**To Reproduce**
![Image](https://github.com/user-attachments/assets/97ef1fc7-302f-4403-a9f0-db23596ee3d6)

- iTwin.js Version 4.10.x

**Comment by pmconne** [comment]
Broken by #7233, specifically [here](https://github.com/iTwin/itwinjs-core/pull/7233/files#diff-1739e480816899876f147038a5de1b56beaee853ffcce314cb545a864913c507).
PR modified 627 files, effectively unreviewable.
