### ISSUE TITLE
Documentation Issue: Rounding

### ISSUE THREAD

**Issue by MDOTEngSupport** [iTwin/itwinjs-core#7460]
{Describe the problem here}
"roundFactor value is rounded to a multiple of the round factor if it is a nonzero value and the applyRounding trait is set. e.g. if the roundFactor is set to 2, 42.2 would be rounded to 42 and 43.2 to 44." 

Should 43.2 round to 43 instead of 44?

Found on page https://www.itwinjs.org/bis/ec/ec-format - "Format"

**Comment by ben-polinsky** [comment]
Hi. The example is correct. The value is rounded to the closest multiple of the `roundFactor` - 43.2 is closer to 44 than it is to 42.

**Comment by ColinKerr** [comment]
I reviewed the tests we had for this attribute and I found that we were lacking formatting tests for this option.  I have filed an issue to add tests: https://github.com/iTwin/itwinjs-core/issues/7462

Thank you for raising this question!
