### ISSUE TITLE
Opening a `BlankConnection` doesn't raise `IModelConnection.onOpen` event

### ISSUE THREAD

**Issue by grigasp** [iTwin/itwinjs-core#7498]
**Describe the bug**

Docs of the `IModelConnection.onOpen` event say: "Event called immediately after *any* IModelConnection is opened". However, opening a `BlankConnection` using its `create` method doesn't raise this event.

**To Reproduce**

```ts
const spy = sinon.spy();
IModelConnection.onOpen.addListener(spy);
const conn = BlankConnection.create({ name: "blank", extents: Range3d.createNull(), location: Cartographic.createZero() });
expect(spy).to.be.calledOnce;
```

**Expected behavior**

Based on the docs, I'd expect the event to be raised.

I'm willing to make the change if I get an agreement from the core team that this is in fact a bug and it needs fixing.

**Comment by pmconne** [comment]
> I'm willing to make the change if I get an agreement from the core team that this is in fact a bug and it needs fixing.

It is and it does.
